<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-08 15:32:53
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: 51.22 K (0.34%)
Current PnL: -30.51 L (-16.73%)
CY Booked + Current PnL: -28.43 L (-15.59%)
-------------------
Total profit:  2.32 L
Total loss:  -32.83 L
-------------------
Total Booked + Current PnL: 14.44 L (10.35%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.32%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.46%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.14,6.17,14.50,21.57,15084.0,6045.0,104025.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.43,XR,ATH,FINANCE
59,PIDILITIND,1.77,4.60,13.16,18.37,19424.0,6490.0,147600.0,1670.26,-26.75,68.0,X-LC,5.36,5.0,0.33,0.97,15.89,X40,ATH,CHEMICALS
53,M&M,-1.20,8.07,14.17,23.38,21236.0,11187.0,149868.0,3802.40,-8.52,60.0,X-LC,7.58,25.0,0.53,0.98,13.62,X40N,ATH,AUTO
51,KOTAKBANK,0.37,1.75,19.02,21.11,26798.0,2424.0,140896.0,453.24,-12.87,53.0,X-LC,7.42,12.0,0.09,0.92,7.75,X40,ATH,BANKS
83,TTKPRESTIG,-2.78,-32.56,48.41,0.09,32904.0,-32808.0,67969.0,770.00,57.74,55.0,M-SC,17.29,250.0,-1.00,0.45,21.03,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,11.51,2.49,20.05,23.03,36798.0,4458.0,183529.0,216.00,99.56,85.0,H-SC,9.72,166.0,0.12,1.20,56.52,XR,NTT,BANKS
16,CERA,5.97,-24.40,63.87,23.89,84938.0,-42917.0,132986.0,9475.00,-26.97,75.0,H-SC,11.10,153.0,-0.51,0.87,27.80,OX40N,NTT,CERAMICS
11,BERGEPAINT,5.63,-4.95,31.85,25.32,78026.0,-12768.0,244981.0,680.00,-10.05,75.0,X-MC,12.92,68.0,-0.16,1.60,27.50,XY24,NTT,PAINTS
43,INDIGOPNTS,5.35,-30.80,44.54,0.02,53802.0,-53764.0,120795.0,1408.00,84.15,74.0,M-SC,21.00,222.0,-1.00,0.79,37.05,OX40N,NTT,PAINTS
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.70,1.40,60.57,OX40N,ATH,CABLES

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-4.35,-58.06,300.99,68.16,167958.0,-77264.0,55802.0,2215.45,-66.13,61.0,H-SC,27.15,141.0,-0.46,0.37,32.94,SR,ATH,IT
88,VOLTAS,-2.87,3.64,40.10,45.20,79687.0,6978.0,198720.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.30,8.92,XY25,NTT,AC
83,TTKPRESTIG,-2.78,-32.56,48.41,0.09,32904.0,-32808.0,67969.0,770.00,57.74,55.0,M-SC,17.29,250.0,-1.00,0.45,21.03,OX40N,NTT,DURABLES
6,AWL,-2.43,-28.79,134.55,67.02,341379.0,-102590.0,253719.0,485.00,-61.66,62.0,X-SC,20.06,81.0,-0.30,1.66,20.01,XY24,NTT,FMCG
66,REPCOHOME,-2.33,-12.77,117.61,89.82,293930.0,-36586.0,249919.0,880.00,-56.78,53.0,H-SC,5.86,161.0,-0.12,1.64,20.14,XY24,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.11,0.22,38.79,39.09,39324.0,218.0,101377.0,804.02,-20.60,55.0,M-MC,19.77,193.0,0.01,0.66,43.41,AR,ATH,AUTO
9,BANDHANBNK,-0.73,-0.85,94.07,92.42,259809.0,-2372.0,276187.0,400.00,137.07,73.0,H-SC,14.35,174.0,-0.01,1.81,52.14,XY24,NTT,BANKS
74,STARHEALTH,0.52,0.65,46.30,47.26,131011.0,1839.0,282962.0,761.00,58.79,63.0,H-SC,9.58,173.0,0.01,1.85,46.54,XY24,NTT,INSURANCE
91,ZYDUSLIFE,-0.03,-0.87,36.82,35.63,76494.0,-1823.0,207751.0,1286.17,-13.51,59.0,H-MC,3.55,120.0,-0.02,1.36,9.23,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.70,1.40,60.57,OX40N,ATH,CABLES
72,SIS,-1.98,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,70.0,H-SC,10.65,168.0,-0.33,0.65,47.96,OX40N,NTT,MISC
16,CERA,5.97,-24.40,63.87,23.89,84938.0,-42917.0,132986.0,9475.00,-26.97,75.0,H-SC,11.10,153.0,-0.51,0.87,27.80,OX40N,NTT,CERAMICS
50,KANSAINER,4.16,-26.46,54.30,13.47,107685.0,-71352.0,198315.0,340.00,-36.88,71.0,H-SC,15.99,162.0,-0.66,1.30,38.52,XY24,NTT,PAINTS
43,INDIGOPNTS,5.35,-30.80,44.54,0.02,53802.0,-53764.0,120795.0,1408.00,84.15,74.0,M-SC,21.00,222.0,-1.00,0.79,37.05,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.7,1.4,60.57,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,11.51,2.49,20.05,23.03,36798.0,4458.0,183529.0,216.00,99.56,85.0,H-SC,9.72,166.0,0.12,1.20,56.52,XR,NTT,BANKS
74,STARHEALTH,0.52,0.65,46.30,47.26,131011.0,1839.0,282962.0,761.00,58.79,63.0,H-SC,9.58,173.0,0.01,1.85,46.54,XY24,NTT,INSURANCE
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.70,1.40,60.57,OX40N,ATH,CABLES
68,SATIN,4.38,17.88,28.81,51.83,93827.0,49390.0,325674.0,274.00,5.12,82.0,H-SC,16.93,159.0,0.53,2.13,58.65,XY24,NTT,FINANCE
55,MASFIN,-0.14,6.17,14.50,21.57,15084.0,6045.0,104025.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.43,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.70,1.40,60.57,OX40N,ATH,CABLES
55,MASFIN,-0.14,6.17,14.50,21.57,15084.0,6045.0,104025.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.43,XR,ATH,FINANCE
75,SURYODAY,11.51,2.49,20.05,23.03,36798.0,4458.0,183529.0,216.00,99.56,85.0,H-SC,9.72,166.0,0.12,1.20,56.52,XR,NTT,BANKS
73,SONACOMS,0.11,0.22,38.79,39.09,39324.0,218.0,101377.0,804.02,-20.60,55.0,M-MC,19.77,193.0,0.01,0.66,43.41,AR,ATH,AUTO
91,ZYDUSLIFE,-0.03,-0.87,36.82,35.63,76494.0,-1823.0,207751.0,1286.17,-13.51,59.0,H-MC,3.55,120.0,-0.02,1.36,9.23,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.27,-22.23,56.24,21.51,105815.0,-53775.0,188149.0,1872.35,-18.11,33.0,X-LC,12.33,8.0,-0.51,1.23,1.27,X40,ATH,IT
45,INFY,1.42,-19.73,67.23,34.24,168862.0,-61718.0,251170.0,1972.00,-36.87,39.0,X-LC,15.83,3.0,-0.37,1.65,2.35,X40,NTT,IT
79,TCS,-0.29,-29.71,80.07,26.57,260738.0,-137635.0,325638.0,4311.59,-40.35,39.0,X-LC,14.23,2.0,-0.53,2.13,1.63,X40,ATH,IT
88,VOLTAS,-2.87,3.64,40.10,45.20,79687.0,6978.0,198720.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.30,8.92,XY25,NTT,AC
28,GODREJCP,0.56,-6.71,41.63,32.12,57715.0,-9975.0,138639.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.85,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-2.87,3.64,40.10,45.20,79687.0,6978.0,198720.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.30,8.92,XY25,NTT,AC
84,UNITDSPR,0.08,-5.91,28.36,20.77,62477.0,-13846.0,220298.0,1644.00,-16.49,42.0,X-MC,2.52,64.0,-0.22,1.44,5.09,X40N,NTT,BREWERIES
65,RELIANCE,-0.07,-7.87,36.01,25.30,66669.0,-15822.0,185141.0,1952.00,-10.42,59.0,X-LC,3.38,21.0,-0.24,1.21,10.01,XY25,BTT,REFINERIES
39,ICICIGI,-1.20,-3.17,23.25,19.34,45051.0,-6341.0,193768.0,2252.93,-18.61,55.0,X-MC,4.60,66.0,-0.14,1.27,8.22,X40,ATH,INSURANCE
19,COLPAL,1.40,-16.56,69.60,41.51,152939.0,-43625.0,219740.0,3726.84,0.87,65.0,X-MC,5.11,62.0,-0.29,1.44,22.85,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.27,-22.23,56.24,21.51,105815.0,-53775.0,188149.0,1872.35,-18.11,33.0,X-LC,12.33,8.0,-0.51,1.23,1.27,X40,ATH,IT
79,TCS,-0.29,-29.71,80.07,26.57,260738.0,-137635.0,325638.0,4311.59,-40.35,39.0,X-LC,14.23,2.0,-0.53,2.13,1.63,X40,ATH,IT
45,INFY,1.42,-19.73,67.23,34.24,168862.0,-61718.0,251170.0,1972.00,-36.87,39.0,X-LC,15.83,3.0,-0.37,1.65,2.35,X40,NTT,IT
84,UNITDSPR,0.08,-5.91,28.36,20.77,62477.0,-13846.0,220298.0,1644.00,-16.49,42.0,X-MC,2.52,64.0,-0.22,1.44,5.09,X40N,NTT,BREWERIES
28,GODREJCP,0.56,-6.71,41.63,32.12,57715.0,-9975.0,138639.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.85,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,1.18,-60.00,280.77,52.31,163026.0,-87096.0,58064.0,1176.00,-57.41,57.0,X-SC,24.39,92.0,-0.53,0.38,29.82,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.88,-53.44,190.41,35.20,114065.0,-68765.0,59905.0,2096.00,-21.44,49.0,X-SC,26.14,91.0,-0.60,0.39,18.81,X40,NTT,FOOTWEAR
60,QUESS,-0.12,-8.30,89.63,73.90,87776.0,-8861.0,97932.0,424.00,-50.41,74.0,X-SC,13.57,80.0,-0.10,0.64,33.50,XY24,NTT,MISC
28,GODREJCP,0.56,-6.71,41.63,32.12,57715.0,-9975.0,138639.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.85,X40N,ATH,FMCG
51,KOTAKBANK,0.37,1.75,19.02,21.11,26798.0,2424.0,140896.0,453.24,-12.87,53.0,X-LC,7.42,12.0,0.09,0.92,7.75,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.02,-19.02,47.02,19.06,129528.0,-64691.0,275475.0,452.00,-55.52,50.0,X-LC,15.57,1.0,-0.50,1.80,6.86,X40,NTT,FMCG
79,TCS,-0.29,-29.71,80.07,26.57,260738.0,-137635.0,325638.0,4311.59,-40.35,39.0,X-LC,14.23,2.0,-0.53,2.13,1.63,X40,ATH,IT
45,INFY,1.42,-19.73,67.23,34.24,168862.0,-61718.0,251170.0,1972.00,-36.87,39.0,X-LC,15.83,3.0,-0.37,1.65,2.35,X40,NTT,IT
81,TMPV,-1.06,-19.09,68.80,36.58,198085.0,-67927.0,287914.0,600.00,-83.62,56.0,X-LC,5.17,4.0,-0.34,1.89,20.00,XY24,NTT,AUTO
59,PIDILITIND,1.77,4.60,13.16,18.37,19424.0,6490.0,147600.0,1670.26,-26.75,68.0,X-LC,5.36,5.0,0.33,0.97,15.89,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.40,-29.81,89.32,32.89,48405.0,-23014.0,54193.0,1800.00,-354.90,69.0,L-MC,5.86,258.0,-0.48,0.36,33.39,XR,NTT,BANKS
12,BOSCH-HCIL,0.10,-36.57,57.63,-0.01,46721.0,-46734.0,81071.0,2282.00,16486.96,62.0,M-SC,4.81,231.0,-1.00,0.53,37.99,OX40N,BTT,AC
72,SIS,-1.98,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,70.0,H-SC,10.65,168.0,-0.33,0.65,47.96,OX40N,NTT,MISC
73,SONACOMS,0.11,0.22,38.79,39.09,39324.0,218.0,101377.0,804.02,-20.60,55.0,M-MC,19.77,193.0,0.01,0.66,43.41,AR,ATH,AUTO
55,MASFIN,-0.14,6.17,14.50,21.57,15084.0,6045.0,104025.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.43,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,4.38,17.88,28.81,51.83,93827.0,49390.0,325674.0,274.00,5.12,82.0,H-SC,16.93,159.0,0.53,2.13,58.65,XY24,NTT,FINANCE
25,FINCABLES,4.91,44.55,43.83,107.91,93543.0,65779.0,213423.0,1641.55,29.88,82.0,M-SC,18.58,220.0,0.70,1.40,60.57,OX40N,ATH,CABLES
72,SIS,-1.98,-10.37,35.30,21.26,35128.0,-11518.0,99514.0,528.00,2365.80,70.0,H-SC,10.65,168.0,-0.33,0.65,47.96,OX40N,NTT,MISC
75,SURYODAY,11.51,2.49,20.05,23.03,36798.0,4458.0,183529.0,216.00,99.56,85.0,H-SC,9.72,166.0,0.12,1.20,56.52,XR,NTT,BANKS
77,TANLA,-1.60,-36.17,240.35,117.25,415395.0,-97932.0,172829.0,1922.32,-35.52,65.0,H-SC,16.90,147.0,-0.24,1.13,51.32,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.02
1     25       42.40
2     50       72.59

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.05
LC    31.26
MC    25.66
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.46
X40      25.36
X40N     16.60
XR        9.23
OX40N     7.03
XY25      6.74
AR        6.70
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.11
H-SC    22.58
X-MC    20.78
M-SC    10.18
X-SC     9.75
H-MC     2.57
M-MC     1.95
H-LC     1.25
M-LC     0.90
L-SC     0.54
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.36        -12.85   52.66
FINANCE             10.85        -11.23   59.61
IT                  10.30        -43.19  115.28
MISC                 7.12        -23.26   76.81
AUTO                 6.63         -8.23   48.80
BANKS                5.73         -3.89   51.92
PAINTS               5.43        -18.83   39.46
INSURANCE            5.33         -1.73   36.35
PHARMA               4.80         -1.06   33.54
ELECTRICAL           3.97        -16.74   58.29
CHEMICALS            2.11        -25.90  100.93
HEALTHCARE           1.96        -19.97   51.27
AC                   1.83        -14.21   45.18
TRAVEL               1.72        -70.84  156.39
APPARELS             1.71         -2.61   37.61
FOOTWEAR             1.71        -69.38  137.29
DURABLES             1.71        -48.76   84.95
BREWERIES            1.44         -6.29   28.36
REALTY               1.40         -3.56   20.57
CABLES               1.40         30.82   43.83
CERAMICS             1.34        -49.48   94.89
ENGINEERING          1.25        -26.46   84.30
REFINERIES           1.21         -8.55   36.01
CEMENT               1.09        -60.53  180.62
JEWELLERY            1.08        -94.01  161.42
ENTERTAINMENT        0.73        -74.35  178.34
TEXTILES             0.43        -40.57   80.65
HOTELS               0.33       -124.61  203.84

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3405685.0     21
X40       1830734.0     19
XR        1272582.0     13
X40N      1190517.0     13
AR        1159367.0      9
OX40N      718302.0     10
XY25       410371.0      5
SR         290038.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3336230.0     24
X-LC        1855704.0     21
X-MC        1559366.0     15
M-SC        1365693.0     14
X-SC        1314415.0      9
H-MC         306027.0      2
L-SC         207989.0      2
M-LC         154355.0      1
M-MC          86962.0      2
L-MC          48405.0      1
H-LC          42450.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1047704.0      6
X-LC       X40        993111.0     10
H-SC       AR         925418.0      5
M-SC       XY24       822173.0      6
X-SC       XY24       773934.0      4
H-SC       XR         753709.0      7
X-MC       X40        638640.0      7
           X40N       490128.0      4
X-LC       X40N       358891.0      6
X-SC       X40N       341498.0      3
X-LC       XY24       334369.0      2
H-SC       OX40N      319361.0      4
M-SC       OX40N      294001.0      5
H-SC       SR         290038.0      2
X-MC       XY25       232626.0      2
H-MC       XY24       229533.0      1
X-SC       X40        198983.0      2
X-MC       XY24       197972.0      2
M-SC       XR         173838.0      2
M-LC       XR         154355.0      1
X-LC       XY25       130107.0      2
L-SC       OX40N      104940.0      1
           XR         103049.0      1
H-MC       AR          76494.0      1
M-SC       AR          75681.0      1
L-MC       XR          48405.0      1
M-MC       XY25        47638.0      1
H-LC       AR          42450.0      1
M-MC       AR          39324.0      1
X-LC       XR          39226.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds