<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('=================== PORTFOLIO QUALITY ====================')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('=================== PORTFOLIO SNAPSHOT ===================')
  print('Deployed Value: ', format_amt(investment))
  print('Current Value:  ', format_amt(current))
  print('CAGR/XIRR %:    ', '{}%'.format(cagr))
  print('Est FTT Value:  ', format_amt(estimate_st))
  print('Future Upside:  ', '{} ({}%)'.format(
      format_amt(est_st_pnl_amount),
      est_st_pnl_percentage
  ))

  print('=================== PERFORMANCE ==========================')
  print('Current PnL:             {} ({}%)'.format(
      format_amt(curr_pnl_amount), curr_pnl_percentage
  ))
  print('Total Booked PnL:        {} ({}%)'.format(
      format_amt(total_booked_amt), total_booked_percentage
  ))
  print('Booked + Current PnL:    {} ({}%)'.format(
      format_amt(overall_pnl_amount), overall_pnl_percentage
  ))
  print('CY Booked PnL:           {} ({}%)'.format(
      format_amt(cy_booked_amt), cy_booked_percentage
  ))
  print('Prev Year Booked PnL:    {} ({}%)'.format(
      format_amt(py_booked_amt), py_booked_percentage
  ))

  print('=================== TODAY / OPERATIONS ===================')
  print('Today PnL:               {} ({}%)'.format(
      format_amt(today_pnl_amount), today_pnl_percentage
  ))
  print('CY Investment:           ', format_amt(cy_invested))
  print('Reserve:                 ', format_amt(reserve_amt))

  print('=================== P&L DETAIL ============================')
  print('Total Profit:            ', format_amt(total_profit))
  print('Total Loss:              ', format_amt(total_loss))
  print('============================================================')

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-28 10:21:00
=================== PORTFOLIO QUALITY ====================
qualified stocks: 86
with latest results: 86
still star stocks: 46
=================== PORTFOLIO SNAPSHOT ===================
Deployed Value:  1.49 C
Current Value:   1.60 C
CAGR/XIRR %:     3.3%
Est FTT Value:   2.75 C
Future Upside:   1.14 C (71.39%)
=================== PERFORMANCE ==========================
Current PnL:             -35.87 L (-18.69%)
Total Booked PnL:        48.10 L (32.27%)
Booked + Current PnL:    12.23 L (8.21%)
CY Booked PnL:           5.24 L (3.27%)
Prev Year Booked PnL:    42.87 L (28.76%)
=================== TODAY / OPERATIONS ===================
Today PnL:               16.42 K (0.1%)
CY Investment:            1.92 C
Reserve:                  0.00
=================== P&L DETAIL ============================
Total Profit:             3.86 L
Total Loss:               -39.74 L
============================================================

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,-0.12,11.36,6.79,18.92,18125.0,27229.0,266931.0,452.46,-5.58,74.0,X-LC,1.84,12.0,1.50,1.67,20.10,X40,ATH,BANKS
77,UNITDSPR,-1.36,11.47,8.34,20.77,21768.0,26866.0,261010.0,1644.00,-4.95,53.0,X-MC,12.22,64.0,1.23,1.63,25.47,X40N,NTT,BREWERIES
27,GLAXO,2.42,24.75,8.77,35.69,21804.0,49332.0,248616.0,3380.16,-6.45,78.0,X-MC,14.41,56.0,2.26,1.55,47.76,X40,ATH,PHARMA
76,TTKPRESTIG,-2.13,-22.38,28.95,0.09,22647.0,-22550.0,78227.0,770.00,-5.56,46.0,M-SC,8.65,250.0,-1.00,0.49,40.80,OX40N,NTT,DURABLES
85,ZYDUSLIFE,-0.56,24.70,8.67,35.51,22657.0,51758.0,261332.0,1285.01,23.42,61.0,H-LC,15.32,120.0,2.28,1.63,37.53,AR,ATH,PHARMA

In [10]:
# top 5 to accumulate
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 40)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
50,KOTAKBANK,-0.12,11.36,6.79,18.92,18125.0,27229.0,266931.0,452.46,-5.58,74.0,X-LC,1.84,12.0,1.50,1.67,20.10,X40,ATH,BANKS
38,HYUNDAI,0.75,17.41,22.59,43.94,66660.0,43755.0,295087.0,2782.73,21.78,69.0,X-LC,7.56,29.0,0.66,1.84,35.48,X40N,ATH,AUTO
35,HDFCLIFE,0.33,-4.76,47.58,40.56,141000.0,-14817.0,296342.0,811.41,-30.61,51.0,X-LC,15.75,31.0,-0.11,1.85,2.60,X40,ATH,INSURANCE
53,MARUTI,0.38,-1.43,26.90,25.08,79840.0,-4316.0,296802.0,17120.06,-7.53,42.0,X-LC,3.48,33.0,-0.05,1.85,10.73,XR,ATH,AUTO
52,M&M,0.45,4.43,12.50,17.48,39303.0,13346.0,314421.0,3762.88,-8.98,48.0,X-LC,4.91,25.0,0.34,1.96,15.32,X40N,ATH,AUTO

In [11]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,3.71,-9.02,39.40,26.82,129394.0,-32562.0,328411.0,1853.42,-13.43,55.0,X-LC,8.79,8.0,-0.25,2.05,29.88,X40,ATH,IT
72,TCS,3.50,-29.91,81.79,27.42,279802.0,-145977.0,342098.0,4230.71,-43.31,52.0,X-LC,12.67,2.0,-0.52,2.13,18.02,X40,ATH,IT
13,BSOFT,3.14,-46.15,175.96,48.59,133263.0,-64918.0,75735.0,819.60,NaN,45.0,NaN,16.69,172.0,-0.49,0.47,10.72,XR,ATH,IT
45,INFY,2.81,-17.38,72.68,42.66,240702.0,-69675.0,331180.0,1972.00,-40.08,53.0,X-LC,14.98,3.0,-0.29,2.07,15.90,X40,NTT,IT
27,GLAXO,2.42,24.75,8.77,35.69,21804.0,49332.0,248616.0,3380.16,-6.45,78.0,X-MC,14.41,56.0,2.26,1.55,47.76,X40,ATH,PHARMA

In [12]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,WHIRLPOOL,-2.64,-34.76,178.85,81.92,133946.0,-39905.0,74893.0,2270.0,NaN,58.0,NaN,8.94,210.0,-0.30,0.47,8.69,XR,NTT,DURABLES
43,INDIGOPNTS,-2.35,-17.73,21.57,0.02,30978.0,-30942.0,143617.0,1408.0,-21.49,58.0,M-SC,9.48,222.0,-1.00,0.90,62.94,OX40N,NTT,PAINTS
9,BANDHANBNK,-2.17,-18.35,135.67,92.42,308565.0,-51121.0,227438.0,400.0,45.11,39.0,H-SC,8.73,174.0,-0.17,1.42,26.37,XY24,NTT,BANKS
68,SURYODAY,-2.13,-11.68,39.30,23.03,62157.0,-20910.0,158161.0,216.0,-27.55,43.0,H-SC,14.26,166.0,-0.34,0.99,34.25,XR,NTT,BANKS
76,TTKPRESTIG,-2.13,-22.38,28.95,0.09,22647.0,-22550.0,78227.0,770.0,-5.56,46.0,M-SC,8.65,250.0,-1.00,0.49,40.80,OX40N,NTT,DURABLES

In [13]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [14]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.55,63.82,26.91,107.91,65089.0,94231.0,241875.0,1641.55,19.27,65.0,M-SC,27.58,220.0,1.45,1.51,81.97,OX40N,ATH,CABLES
66,SIS,1.37,-1.97,23.70,21.26,25797.0,-2185.0,108847.0,528.00,109.35,52.0,H-SC,19.32,168.0,-0.08,0.68,61.84,OX40N,NTT,MISC
43,INDIGOPNTS,-2.35,-17.73,21.57,0.02,30978.0,-30942.0,143617.0,1408.00,-21.49,58.0,M-SC,9.48,222.0,-1.00,0.90,62.94,OX40N,NTT,PAINTS
76,TTKPRESTIG,-2.13,-22.38,28.95,0.09,22647.0,-22550.0,78227.0,770.00,-5.56,46.0,M-SC,8.65,250.0,-1.00,0.49,40.80,OX40N,NTT,DURABLES
16,CERA,-0.08,-26.03,67.48,23.89,87806.0,-45781.0,130122.0,9475.00,NaN,35.0,NaN,12.32,153.0,-0.52,0.81,26.49,OX40N,NTT,CERAMICS

In [15]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.55,63.82,26.91,107.91,65089.0,94231.0,241875.0,1641.55,19.27,65.0,M-SC,27.58,220.0,1.45,1.51,81.97,OX40N,ATH,CABLES
85,ZYDUSLIFE,-0.56,24.70,8.67,35.51,22657.0,51758.0,261332.0,1285.01,23.42,61.0,H-LC,15.32,120.0,2.28,1.63,37.53,AR,ATH,PHARMA
27,GLAXO,2.42,24.75,8.77,35.69,21804.0,49332.0,248616.0,3380.16,-6.45,78.0,X-MC,14.41,56.0,2.26,1.55,47.76,X40,ATH,PHARMA

In [16]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.55,63.82,26.91,107.91,65089.0,94231.0,241875.0,1641.55,19.27,65.0,M-SC,27.58,220.0,1.45,1.51,81.97,OX40N,ATH,CABLES
67,STARHEALTH,-0.95,11.89,31.62,47.26,99458.0,33418.0,314541.0,761.00,-1.35,47.0,H-SC,15.52,173.0,0.34,1.96,36.00,XY24,NTT,INSURANCE

In [17]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.55,63.82,26.91,107.91,65089.0,94231.0,241875.0,1641.55,19.27,65.0,M-SC,27.58,220.0,1.45,1.51,81.97,OX40N,ATH,CABLES
66,SIS,1.37,-1.97,23.70,21.26,25797.0,-2185.0,108847.0,528.00,109.35,52.0,H-SC,19.32,168.0,-0.08,0.68,61.84,OX40N,NTT,MISC
3,ALKYLAMINE,-0.83,-11.74,118.16,92.54,105291.0,-11854.0,89109.0,4520.85,NaN,65.0,NaN,18.42,142.0,-0.11,0.56,69.21,SR,ATH,CHEMICALS
84,WIPRO,2.17,-17.17,133.04,93.01,275744.0,-42976.0,207264.0,420.00,-30.06,49.0,M-LC,14.08,98.0,-0.16,1.29,7.15,XR,NTT,IT
42,INDIAMART,0.39,-24.27,165.31,100.92,154403.0,-29934.0,93402.0,4675.60,NaN,43.0,NaN,12.99,140.0,-0.19,0.58,1.61,AR,ATH,MISC

In [18]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.23,-24.67,90.76,43.70,169603.0,-61198.0,186870.0,735.00,-35.11,24.0,X-MC,11.66,70.0,-0.36,1.17,0.00,XY24,BTT,FMCG
19,COLPAL,-0.68,-30.42,101.02,39.86,185109.0,-80125.0,183240.0,3683.41,-15.68,26.0,X-MC,5.17,62.0,-0.43,1.14,3.65,XY25,ATH,FMCG
56,PGHH,-0.20,-39.15,116.96,32.01,151954.0,-83600.0,129920.0,17616.87,-55.32,27.0,X-SC,20.07,57.0,-0.55,0.81,0.38,X40,ATH,FMCG
28,GODREJCP,-0.62,-16.55,59.27,32.90,123416.0,-41310.0,208227.0,1460.97,-18.06,31.0,X-MC,10.41,32.0,-0.33,1.30,1.36,X40N,ATH,FMCG
39,ICICIGI,-0.86,-16.60,42.56,18.89,71027.0,-33223.0,166886.0,2244.41,-16.90,33.0,X-MC,10.32,66.0,-0.47,1.04,0.00,X40,ATH,INSURANCE

In [19]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,-0.18,-5.67,40.38,32.43,134923.0,-20068.0,334132.0,5391.45,-21.50,38.0,X-LC,1.79,14.0,-0.15,2.09,5.33,X40N,ATH,FMCG
50,KOTAKBANK,-0.12,11.36,6.79,18.92,18125.0,27229.0,266931.0,452.46,-5.58,74.0,X-LC,1.84,12.0,1.50,1.67,20.10,X40,ATH,BANKS
1,ABBOTINDIA,0.21,-10.73,29.24,15.37,46685.0,-19195.0,159660.0,34390.26,-27.37,44.0,X-MC,1.92,58.0,-0.41,1.00,8.15,X40,ATH,PHARMA
53,MARUTI,0.38,-1.43,26.90,25.08,79840.0,-4316.0,296802.0,17120.06,-7.53,42.0,X-LC,3.48,33.0,-0.05,1.85,10.73,XR,ATH,AUTO
4,ASIANPAINT,-0.42,-5.02,30.93,24.36,97244.0,-16632.0,314400.0,3430.49,-16.82,37.0,X-LC,3.94,30.0,-0.17,1.96,24.58,X40,ATH,PAINTS

In [20]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.23,-24.67,90.76,43.70,169603.0,-61198.0,186870.0,735.00,-35.11,24.0,X-MC,11.66,70.0,-0.36,1.17,0.00,XY24,BTT,FMCG
39,ICICIGI,-0.86,-16.60,42.56,18.89,71027.0,-33223.0,166886.0,2244.41,-16.90,33.0,X-MC,10.32,66.0,-0.47,1.04,0.00,X40,ATH,INSURANCE
36,HINDUNILVR,-0.89,-14.92,45.87,24.10,147012.0,-56221.0,320496.0,2922.00,-42.53,36.0,X-LC,7.26,9.0,-0.38,2.00,0.00,XY25,NTT,FMCG
82,VOLTAS,-0.99,-5.70,53.97,45.20,97583.0,-10932.0,180810.0,1856.00,29.85,34.0,X-MC,6.70,79.0,-0.11,1.13,0.00,XY25,NTT,AC
56,PGHH,-0.20,-39.15,116.96,32.01,151954.0,-83600.0,129920.0,17616.87,-55.32,27.0,X-SC,20.07,57.0,-0.55,0.81,0.38,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,-0.20,-39.15,116.96,32.01,151954.0,-83600.0,129920.0,17616.87,-55.32,27.0,X-SC,20.07,57.0,-0.55,0.81,0.38,X40,ATH,FMCG
2,ACC,0.05,-41.32,197.90,74.81,311384.0,-110784.0,157344.0,3906.00,-41.79,44.0,X-SC,11.33,85.0,-0.36,0.98,5.12,XY24,BTT,CEMENT
1,ABBOTINDIA,0.21,-10.73,29.24,15.37,46685.0,-19195.0,159660.0,34390.26,-27.37,44.0,X-MC,1.92,58.0,-0.41,1.00,8.15,X40,ATH,PHARMA
40,ICICIPRULI,-1.22,-15.81,54.75,30.28,90804.0,-31153.0,165852.0,787.27,-45.99,51.0,X-MC,11.43,78.0,-0.34,1.04,10.50,X40,ATH,INSURANCE
39,ICICIGI,-0.86,-16.60,42.56,18.89,71027.0,-33223.0,166886.0,2244.41,-16.90,33.0,X-MC,10.32,66.0,-0.47,1.04,0.00,X40,ATH,INSURANCE

In [22]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.28,-23.62,68.50,28.70,228954.0,-103355.0,334240.0,452.00,-31.16,35.0,X-LC,10.82,1.0,-0.45,2.09,0.45,X40,NTT,FMCG
72,TCS,3.50,-29.91,81.79,27.42,279802.0,-145977.0,342098.0,4230.71,-43.31,52.0,X-LC,12.67,2.0,-0.52,2.13,18.02,X40,ATH,IT
45,INFY,2.81,-17.38,72.68,42.66,240702.0,-69675.0,331180.0,1972.00,-40.08,53.0,X-LC,14.98,3.0,-0.29,2.07,15.90,X40,NTT,IT
74,TMPV,-0.17,-23.21,90.20,46.05,309860.0,-103847.0,343525.0,600.00,-84.91,34.0,X-LC,5.04,4.0,-0.34,2.14,7.38,XY24,NTT,AUTO
33,HCLTECH,3.71,-9.02,39.40,26.82,129394.0,-32562.0,328411.0,1853.42,-13.43,55.0,X-LC,8.79,8.0,-0.25,2.05,29.88,X40,ATH,IT

In [23]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.56,-26.29,80.29,32.89,45692.0,-20298.0,56909.0,1800.00,318.80,45.0,L-MC,11.62,258.0,-0.44,0.36,40.30,XR,NTT,BANKS
76,TTKPRESTIG,-2.13,-22.38,28.95,0.09,22647.0,-22550.0,78227.0,770.00,-5.56,46.0,M-SC,8.65,250.0,-1.00,0.49,40.80,OX40N,NTT,DURABLES
3,ALKYLAMINE,-0.83,-11.74,118.16,92.54,105291.0,-11854.0,89109.0,4520.85,NaN,65.0,NaN,18.42,142.0,-0.11,0.56,69.21,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.74,-26.39,35.83,-0.01,33709.0,-33725.0,94080.0,2282.00,732.37,60.0,M-SC,16.85,231.0,-1.00,0.59,60.14,OX40N,BTT,AC
80,VALIANTORG,1.01,-37.65,179.33,74.15,182917.0,-61605.0,102000.0,838.00,NaN,52.0,NaN,11.90,145.0,-0.34,0.64,51.79,XR,NTT,CHEMICALS

In [24]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.55,63.82,26.91,107.91,65089.0,94231.0,241875.0,1641.55,19.27,65.0,M-SC,27.58,220.0,1.45,1.51,81.97,OX40N,ATH,CABLES
12,BOSCH-HCIL,0.74,-26.39,35.83,-0.01,33709.0,-33725.0,94080.0,2282.00,732.37,60.0,M-SC,16.85,231.0,-1.00,0.59,60.14,OX40N,BTT,AC
27,GLAXO,2.42,24.75,8.77,35.69,21804.0,49332.0,248616.0,3380.16,-6.45,78.0,X-MC,14.41,56.0,2.26,1.55,47.76,X40,ATH,PHARMA
80,VALIANTORG,1.01,-37.65,179.33,74.15,182917.0,-61605.0,102000.0,838.00,NaN,52.0,NaN,11.90,145.0,-0.34,0.64,51.79,XR,NTT,CHEMICALS
38,HYUNDAI,0.75,17.41,22.59,43.94,66660.0,43755.0,295087.0,2782.73,21.78,69.0,X-LC,7.56,29.0,0.66,1.84,35.48,X40N,ATH,AUTO

In [25]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.82
1     25       48.10
2     50       79.38

In [26]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    40.86
MC    21.17
SC    20.74
Name: CurrAlloc%, dtype: float64

In [27]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      28.20
XY24     23.23
X40N     19.10
XR        9.57
XY25      7.38
OX40N     7.00
AR        4.67
SR        0.88
Name: CurrAlloc%, dtype: float64

In [28]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    37.94
X-MC    18.72
H-SC     8.11
X-SC     7.39
M-SC     5.24
H-LC     1.63
M-LC     1.29
M-MC     1.10
H-MC     0.99
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [29]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.62        -25.69   71.89
IT                  11.98        -33.52  104.09
FINANCE             10.79        -16.68   66.65
AUTO                 8.81         -5.96   43.76
BANKS                6.47         -9.89   57.76
PHARMA               6.18         10.21   14.54
INSURANCE            5.89         -4.85   42.63
MISC                 5.66        -36.17   90.95
PAINTS               5.45        -18.28   39.14
ELECTRICAL           2.77        -17.22   62.50
REFINERIES           2.01        -10.92   51.41
AC                   1.72        -16.25   47.76
BREWERIES            1.63         10.29    8.34
FOOTWEAR             1.57        -75.11  145.32
APPARELS             1.56         -7.58   42.92
CABLES               1.51         38.96   26.91
DURABLES             1.45        -67.08  107.72
TRAVEL               1.36       -104.45  206.83
CERAMICS             1.23        -56.11  103.53
CHEMICALS            1.20        -38.44  150.81
ENGINEERING          1.19        -27.02   85.11
CEMENT               0.98        -70.41  197.90
JEWELLERY            0.91       -119.81  196.17
ENTERTAINMENT        0.68        -76.93  182.45
HEALTHCARE           0.67        -67.57  109.63
TEXTILES             0.38        -53.01   96.64
HOTELS               0.36        -99.06  169.27

In [30]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3710540.0     19
X40       2261366.0     18
XR        1523705.0     13
X40N      1280293.0     12
AR        1051582.0      7
OX40N      672020.0     10
XY25       664870.0      5
SR         274736.0      2

In [31]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2787014.0     19
X-MC        1503883.0     14
X-SC        1092643.0      6
H-SC         849975.0      8
M-SC         327959.0      6
M-LC         275744.0      1
H-MC         254918.0      1
M-MC          69472.0      1
L-MC          45692.0      1
H-LC          22657.0      1

In [32]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1379044.0      9
X-SC       XY24       662695.0      2
H-SC       XY24       535698.0      3
X-LC       XY24       519528.0      2
X-MC       X40        508577.0      6
X-LC       X40N       495896.0      5
X-MC       X40N       457042.0      4
X-LC       XY25       312706.0      2
X-MC       XY25       282692.0      2
M-LC       XR         275744.0      1
X-SC       X40        256178.0      2
X-MC       XY24       255572.0      2
H-MC       XY24       254918.0      1
H-SC       OX40N      221902.0      3
X-SC       X40N       173770.0      2
M-SC       OX40N      152423.0      4
           XY24       117269.0      1
H-SC       XR          92375.0      2
X-LC       XR          79840.0      1
M-MC       XY25        69472.0      1
M-SC       XR          58267.0      1
L-MC       XR          45692.0      1
H-LC       AR          22657.0      1

In [33]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds