<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-12 11:08:18
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.49 C
-------------------
Today PnL: -1.57 L (-1.04%)
Current PnL: -34.02 L (-18.65%)
CY Booked + Current PnL: -31.94 L (-17.51%)
-------------------
Total profit:  2.19 L
Total loss:  -36.20 L
-------------------
Total Booked + Current PnL: 10.93 L (7.84%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.06 C (71.25%)
===================
Deployed:  1.40 C
Current:  1.49 C
CAGR/XIRR %: 3.28%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-3.20,2.97,18.06,21.57,18221.0,2910.0,100890.0,397.04,-11.02,57.0,H-SC,5.46,167.0,0.16,0.68,26.90,XR,ATH,FINANCE
59,PIDILITIND,2.23,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,63.0,X-LC,5.44,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS
83,TTKPRESTIG,12.98,-23.86,31.47,0.09,24146.0,-24050.0,76727.0,770.00,78.01,72.0,M-SC,17.03,250.0,-1.00,0.51,36.62,OX40N,NTT,DURABLES
53,M&M,-0.65,4.64,17.91,23.38,25991.0,6439.0,145120.0,3802.40,-11.30,52.0,X-LC,7.85,25.0,0.25,0.97,10.02,X40N,ATH,AUTO
51,KOTAKBANK,-0.68,1.12,19.76,21.11,27669.0,1554.0,140026.0,453.24,-13.31,50.0,X-LC,7.26,12.0,0.06,0.94,7.09,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,12.98,-23.86,31.47,0.09,24146.0,-24050.0,76727.0,770.00,78.01,72.0,M-SC,17.03,250.0,-1.00,0.51,36.62,OX40N,NTT,DURABLES
68,SATIN,11.26,32.36,14.71,51.83,53794.0,89411.0,365695.0,274.00,18.27,87.0,H-SC,20.51,159.0,1.66,2.45,78.15,XY24,NTT,FINANCE
59,PIDILITIND,2.23,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,63.0,X-LC,5.44,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS
66,REPCOHOME,0.76,-12.80,117.69,89.82,294020.0,-36679.0,249826.0,880.00,-56.78,53.0,H-SC,6.30,161.0,-0.12,1.68,20.10,XY24,NTT,FINANCE
9,BANDHANBNK,0.40,-2.81,97.98,92.42,265265.0,-7825.0,270734.0,400.00,132.04,67.0,H-SC,16.45,174.0,-0.03,1.82,49.14,XY24,NTT,BANKS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
13,BSOFT,-5.07,-38.75,146.17,50.79,125928.0,-54501.0,86152.0,831.70,-21.53,32.0,H-SC,4.83,172.0,-0.43,0.58,1.59,XR,ATH,IT
49,JSWINFRA,-4.47,-6.55,24.59,16.43,50962.0,-14526.0,207248.0,342.00,-19.87,52.0,X-MC,7.23,61.0,-0.29,1.39,17.15,X40N,NTT,REALTY
64,RELAXO,-4.30,-61.53,295.96,52.31,165252.0,-89324.0,55836.0,1176.00,-59.06,47.0,X-SC,24.55,92.0,-0.54,0.37,24.84,X40N,NTT,FOOTWEAR
79,TCS,-4.22,-32.72,88.12,26.57,274668.0,-151575.0,311698.0,4311.59,-42.97,30.0,X-LC,14.54,2.0,-0.55,2.09,0.00,X40,ATH,IT
30,HAPPSTMNDS,-3.89,-54.37,305.12,84.85,178434.0,-69685.0,58480.0,1480.71,-45.69,42.0,H-SC,19.94,152.0,-0.39,0.39,8.30,AR,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.01,-0.15,47.48,47.26,133278.0,-419.0,280704.0,761.00,57.63,60.0,H-SC,10.33,173.0,-0.00,1.88,38.19,XY24,NTT,INSURANCE
91,ZYDUSLIFE,-1.43,-0.53,36.35,35.63,75778.0,-1105.0,208469.0,1286.17,-13.51,58.0,H-MC,3.36,120.0,-0.01,1.40,9.61,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,40.46,48.03,107.91,99602.0,59730.0,207374.0,1641.55,26.33,73.0,M-SC,21.59,220.0,0.60,1.39,56.01,OX40N,ATH,CABLES
72,SIS,-0.08,-11.68,37.30,21.26,36576.0,-12972.0,98060.0,528.00,2330.05,67.0,H-SC,12.10,168.0,-0.35,0.66,45.80,OX40N,NTT,MISC
16,CERA,-0.36,-19.85,54.57,23.89,76938.0,-34913.0,140990.0,9475.00,-22.67,80.0,H-SC,10.17,153.0,-0.45,0.95,35.49,OX40N,NTT,CERAMICS
83,TTKPRESTIG,12.98,-23.86,31.47,0.09,24146.0,-24050.0,76727.0,770.00,78.01,72.0,M-SC,17.03,250.0,-1.00,0.51,36.62,OX40N,NTT,DURABLES
50,KANSAINER,-0.12,-27.55,56.62,13.47,110625.0,-74286.0,195381.0,340.00,-37.71,67.0,H-SC,15.29,162.0,-0.67,1.31,36.47,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,40.46,48.03,107.91,99602.0,59730.0,207374.0,1641.55,26.33,73.0,M-SC,21.59,220.0,0.60,1.39,56.01,OX40N,ATH,CABLES
68,SATIN,11.26,32.36,14.71,51.83,53794.0,89411.0,365695.0,274.00,18.27,87.0,H-SC,20.51,159.0,1.66,2.45,78.15,XY24,NTT,FINANCE

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,40.46,48.03,107.91,99602.0,59730.0,207374.0,1641.55,26.33,73.0,M-SC,21.59,220.0,0.60,1.39,56.01,OX40N,ATH,CABLES
68,SATIN,11.26,32.36,14.71,51.83,53794.0,89411.0,365695.0,274.00,18.27,87.0,H-SC,20.51,159.0,1.66,2.45,78.15,XY24,NTT,FINANCE
55,MASFIN,-3.20,2.97,18.06,21.57,18221.0,2910.0,100890.0,397.04,-11.02,57.0,H-SC,5.46,167.0,0.16,0.68,26.90,XR,ATH,FINANCE
73,SONACOMS,0.40,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,60.0,M-MC,20.20,193.0,0.09,0.70,47.53,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,40.46,48.03,107.91,99602.0,59730.0,207374.0,1641.55,26.33,73.0,M-SC,21.59,220.0,0.60,1.39,56.01,OX40N,ATH,CABLES
55,MASFIN,-3.20,2.97,18.06,21.57,18221.0,2910.0,100890.0,397.04,-11.02,57.0,H-SC,5.46,167.0,0.16,0.68,26.90,XR,ATH,FINANCE
73,SONACOMS,0.40,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,60.0,M-MC,20.20,193.0,0.09,0.70,47.53,AR,ATH,AUTO
91,ZYDUSLIFE,-1.43,-0.53,36.35,35.63,75778.0,-1105.0,208469.0,1286.17,-13.51,58.0,H-MC,3.36,120.0,-0.01,1.40,9.61,AR,ATH,PHARMA
75,SURYODAY,-3.81,-1.68,25.14,23.03,44262.0,-3009.0,176062.0,216.00,90.79,72.0,H-SC,11.88,166.0,-0.07,1.18,48.24,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-3.46,-25.14,62.30,21.51,112835.0,-60809.0,181115.0,1872.35,-21.42,27.0,X-LC,13.79,8.0,-0.54,1.21,0.00,X40,ATH,IT
79,TCS,-4.22,-32.72,88.12,26.57,274668.0,-151575.0,311698.0,4311.59,-42.97,30.0,X-LC,14.54,2.0,-0.55,2.09,0.00,X40,ATH,IT
45,INFY,-3.78,-22.90,74.13,34.24,178818.0,-71666.0,241222.0,1972.00,-39.40,32.0,X-LC,16.49,3.0,-0.40,1.62,0.00,X40,NTT,IT
28,GODREJCP,0.01,-9.97,46.03,31.47,61587.0,-14816.0,133798.0,1469.04,-5.33,37.0,X-LC,6.91,32.0,-0.24,0.90,2.66,X40N,ATH,FMCG
88,VOLTAS,-0.45,1.75,42.70,45.20,83303.0,3348.0,195090.0,1856.00,16.53,37.0,X-MC,2.17,79.0,0.04,1.31,6.59,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.45,1.75,42.70,45.20,83303.0,3348.0,195090.0,1856.00,16.53,37.0,X-MC,2.17,79.0,0.04,1.31,6.59,XY25,NTT,AC
84,UNITDSPR,-0.70,-7.65,30.77,20.77,66536.0,-17906.0,216238.0,1644.00,-18.03,38.0,X-MC,2.52,64.0,-0.27,1.45,3.15,X40N,NTT,BREWERIES
65,RELIANCE,-0.30,-11.16,41.04,25.30,73271.0,-22427.0,178536.0,1952.00,-13.49,47.0,X-LC,3.43,21.0,-0.31,1.20,6.09,XY25,BTT,REFINERIES
39,ICICIGI,-0.99,-4.10,24.44,19.34,46904.0,-8196.0,191913.0,2252.93,-19.34,51.0,X-MC,4.45,66.0,-0.17,1.29,7.19,X40,ATH,INSURANCE
19,COLPAL,-0.79,-19.43,75.63,41.51,160487.0,-51165.0,212200.0,3726.84,-2.49,54.0,X-MC,5.18,62.0,-0.32,1.42,18.63,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,INFY,-3.78,-22.90,74.13,34.24,178818.0,-71666.0,241222.0,1972.00,-39.40,32.0,X-LC,16.49,3.0,-0.40,1.62,0.00,X40,NTT,IT
33,HCLTECH,-3.46,-25.14,62.30,21.51,112835.0,-60809.0,181115.0,1872.35,-21.42,27.0,X-LC,13.79,8.0,-0.54,1.21,0.00,X40,ATH,IT
79,TCS,-4.22,-32.72,88.12,26.57,274668.0,-151575.0,311698.0,4311.59,-42.97,30.0,X-LC,14.54,2.0,-0.55,2.09,0.00,X40,ATH,IT
28,GODREJCP,0.01,-9.97,46.03,31.47,61587.0,-14816.0,133798.0,1469.04,-5.33,37.0,X-LC,6.91,32.0,-0.24,0.90,2.66,X40N,ATH,FMCG
84,UNITDSPR,-0.70,-7.65,30.77,20.77,66536.0,-17906.0,216238.0,1644.00,-18.03,38.0,X-MC,2.52,64.0,-0.27,1.45,3.15,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-4.30,-61.53,295.96,52.31,165252.0,-89324.0,55836.0,1176.00,-59.06,47.0,X-SC,24.55,92.0,-0.54,0.37,24.84,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.66,-54.39,196.46,35.20,115285.0,-69989.0,58681.0,2096.00,-23.03,43.0,X-SC,26.15,91.0,-0.61,0.39,16.38,X40,NTT,FOOTWEAR
60,QUESS,-2.78,-12.09,97.83,73.90,91840.0,-12916.0,93877.0,424.00,-52.62,62.0,X-SC,13.23,80.0,-0.14,0.63,27.97,XY24,NTT,MISC
28,GODREJCP,0.01,-9.97,46.03,31.47,61587.0,-14816.0,133798.0,1469.04,-5.33,37.0,X-LC,6.91,32.0,-0.24,0.90,2.66,X40N,ATH,FMCG
51,KOTAKBANK,-0.68,1.12,19.76,21.11,27669.0,1554.0,140026.0,453.24,-13.31,50.0,X-LC,7.26,12.0,0.06,0.94,7.09,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.60,-19.93,48.68,19.06,132597.0,-67782.0,272384.0,452.00,-55.92,46.0,X-LC,15.56,1.0,-0.51,1.83,5.67,X40,NTT,FMCG
79,TCS,-4.22,-32.72,88.12,26.57,274668.0,-151575.0,311698.0,4311.59,-42.97,30.0,X-LC,14.54,2.0,-0.55,2.09,0.00,X40,ATH,IT
45,INFY,-3.78,-22.90,74.13,34.24,178818.0,-71666.0,241222.0,1972.00,-39.40,32.0,X-LC,16.49,3.0,-0.40,1.62,0.00,X40,NTT,IT
81,TMPV,-1.42,-22.36,75.90,36.58,209705.0,-79550.0,276291.0,600.00,-83.62,47.0,X-LC,5.56,4.0,-0.38,1.85,15.16,XY24,NTT,AUTO
59,PIDILITIND,2.23,4.12,13.68,18.37,20099.0,5810.0,146920.0,1670.26,-27.09,63.0,X-LC,5.44,5.0,0.29,0.99,15.36,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.98,-33.26,99.10,32.89,51067.0,-25676.0,51531.0,1800.00,-342.30,54.0,L-MC,6.92,258.0,-0.50,0.35,26.84,XR,NTT,BANKS
12,BOSCH-HCIL,-0.20,-35.89,55.97,-0.01,45858.0,-45871.0,81934.0,2282.00,16660.87,64.0,M-SC,5.47,231.0,-1.00,0.55,39.46,OX40N,BTT,AC
72,SIS,-0.08,-11.68,37.30,21.26,36576.0,-12972.0,98060.0,528.00,2330.05,67.0,H-SC,12.10,168.0,-0.35,0.66,45.80,OX40N,NTT,MISC
55,MASFIN,-3.20,2.97,18.06,21.57,18221.0,2910.0,100890.0,397.04,-11.02,57.0,H-SC,5.46,167.0,0.16,0.68,26.90,XR,ATH,FINANCE
73,SONACOMS,0.40,3.10,34.91,39.09,36408.0,3132.0,104291.0,804.02,-18.31,60.0,M-MC,20.20,193.0,0.09,0.70,47.53,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SATIN,11.26,32.36,14.71,51.83,53794.0,89411.0,365695.0,274.00,18.27,87.0,H-SC,20.51,159.0,1.66,2.45,78.15,XY24,NTT,FINANCE
25,FINCABLES,-2.08,40.46,48.03,107.91,99602.0,59730.0,207374.0,1641.55,26.33,73.0,M-SC,21.59,220.0,0.60,1.39,56.01,OX40N,ATH,CABLES
75,SURYODAY,-3.81,-1.68,25.14,23.03,44262.0,-3009.0,176062.0,216.00,90.79,72.0,H-SC,11.88,166.0,-0.07,1.18,48.24,XR,NTT,BANKS
72,SIS,-0.08,-11.68,37.30,21.26,36576.0,-12972.0,98060.0,528.00,2330.05,67.0,H-SC,12.10,168.0,-0.35,0.66,45.80,OX40N,NTT,MISC
83,TTKPRESTIG,12.98,-23.86,31.47,0.09,24146.0,-24050.0,76727.0,770.00,78.01,72.0,M-SC,17.03,250.0,-1.00,0.51,36.62,OX40N,NTT,DURABLES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.30
1     25       42.50
2     50       72.71

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.27
LC    31.12
MC    25.64
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.67
X40      25.33
X40N     16.54
XR        9.09
OX40N     7.14
XY25      6.76
AR        6.68
SR        0.82
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.02
H-SC    22.84
X-MC    20.71
M-SC    10.19
X-SC     9.71
H-MC     2.59
M-MC     1.99
H-LC     1.21
M-LC     0.89
L-SC     0.53
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.40        -15.19   55.79
FINANCE             11.11        -11.28   59.69
IT                  10.09        -49.63  124.97
MISC                 7.06        -27.29   82.59
AUTO                 6.65        -10.41   51.81
BANKS                5.71         -6.78   56.16
INSURANCE            5.39         -3.06   38.13
PAINTS               5.37        -22.90   44.25
PHARMA               4.89         -1.78   34.49
ELECTRICAL           3.90        -21.75   65.09
CHEMICALS            2.14        -27.78  103.92
HEALTHCARE           2.01        -19.77   51.02
AC                   1.86        -15.35   46.62
DURABLES             1.75        -48.14   84.18
FOOTWEAR             1.69        -74.45  144.40
TRAVEL               1.68        -78.01  167.13
APPARELS             1.67         -7.61   44.31
BREWERIES            1.45         -8.28   30.77
CERAMICS             1.42        -45.49   89.69
CABLES               1.39         28.80   48.03
REALTY               1.39         -7.01   24.59
ENGINEERING          1.21        -33.84   95.06
REFINERIES           1.20        -12.56   41.04
CEMENT               1.09        -64.56  187.67
JEWELLERY            1.04       -107.25  179.26
ENTERTAINMENT        0.72        -81.09  189.09
TEXTILES             0.42        -46.18   87.87
HOTELS               0.33       -133.20  215.46

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3471723.0     21
X40       1924643.0     19
XR        1328139.0     13
X40N      1256625.0     13
AR        1188149.0      9
OX40N      728155.0     10
XY25       432362.0      5
SR         297218.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3383015.0     24
X-LC        1970071.0     21
X-MC        1644486.0     15
M-SC        1399078.0     14
X-SC        1354341.0      9
H-MC         311550.0      2
L-SC         212515.0      2
M-LC         159128.0      1
M-MC          88667.0      2
H-LC          53096.0      1
L-MC          51067.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1050727.0     10
H-SC       XY24      1028985.0      6
           AR         945587.0      5
M-SC       XY24       843502.0      6
H-SC       XR         786563.0      7
X-SC       XY24       785438.0      4
X-MC       X40        666888.0      7
           X40N       515370.0      4
X-LC       X40N       379380.0      6
X-SC       X40N       361875.0      3
X-LC       XY24       359588.0      2
H-SC       OX40N      324662.0      4
           SR         297218.0      2
M-SC       OX40N      295888.0      5
X-MC       XY25       243790.0      2
H-MC       XY24       235772.0      1
X-MC       XY24       218438.0      2
X-SC       X40        207028.0      2
M-SC       XR         182408.0      2
M-LC       XR         159128.0      1
X-LC       XY25       136313.0      2
L-SC       OX40N      107605.0      1
           XR         104910.0      1
M-SC       AR          77280.0      1
H-MC       AR          75778.0      1
H-LC       AR          53096.0      1
M-MC       XY25        52259.0      1
L-MC       XR          51067.0      1
X-LC       XR          44063.0      1
M-MC       AR          36408.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 26.0 seconds