<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-17 14:59:12
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -3.02 K (-0.02%)
Current PnL: -30.43 L (-16.69%)
CY Booked + Current PnL: -28.35 L (-15.55%)
-------------------
Total profit:  4.52 L
Total loss:  -34.95 L
-------------------
Total Booked + Current PnL: 14.52 L (10.41%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (66.86%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.1%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.71,16.33,0.09,16.43,232.0,36210.0,257984.0,342.00,-0.34,63.0,X-MC,17.90,61.0,156.08,1.69,46.27,X40N,NTT,REALTY
59,PIDILITIND,0.51,11.09,6.55,18.37,10268.0,15650.0,156760.0,1670.26,-22.17,51.0,X-LC,8.19,5.0,1.52,1.03,23.08,X40,ATH,CHEMICALS
83,TTKPRESTIG,-0.58,-12.41,14.28,0.09,12605.0,-12509.0,88268.0,770.00,104.91,72.0,M-SC,9.12,250.0,-0.99,0.58,57.17,OX40N,NTT,DURABLES
73,SONACOMS,2.97,21.74,13.92,38.69,17142.0,21989.0,123148.0,801.69,-3.59,79.0,M-MC,23.18,193.0,1.28,0.81,74.72,AR,ATH,AUTO
51,KOTAKBANK,3.47,4.09,16.15,20.90,23278.0,5662.0,144134.0,452.46,-10.71,52.0,X-LC,3.93,12.0,0.24,0.94,10.42,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,19.99,-43.02,167.30,52.31,138376.0,-62449.0,82711.0,1176.00,-39.31,68.0,X-SC,12.15,92.0,-0.45,0.54,84.93,X40N,NTT,FOOTWEAR
14,CAMPUS,7.23,-17.57,61.70,33.28,85325.0,-29485.0,138290.0,393.00,-33.59,60.0,M-SC,8.34,218.0,-0.35,0.91,11.05,XY24,NTT,FOOTWEAR
85,VAIBHAVGBL,4.40,-18.94,98.33,60.77,145689.0,-34612.0,148163.0,521.00,70.80,67.0,H-SC,6.44,160.0,-0.24,0.97,50.74,XR,NTT,JEWELLERY
51,KOTAKBANK,3.47,4.09,16.15,20.90,23278.0,5662.0,144134.0,452.46,-10.71,52.0,X-LC,3.93,12.0,0.24,0.94,10.42,X40,ATH,BANKS
48,JIOFIN,3.20,-19.30,59.14,28.43,142378.0,-57579.0,240748.0,387.00,-20.57,55.0,X-LC,10.72,34.0,-0.40,1.58,8.51,XY24,BTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
0,5PAISA,-4.66,-30.11,61.54,12.90,93980.0,-65782.0,152714.0,593.00,124.76,54.0,H-SC,11.77,170.0,-0.70,1.00,47.37,OX40N,NTT,FINANCE
68,SATIN,-4.00,41.58,7.24,51.83,28321.0,114886.0,391170.0,274.00,27.46,55.0,H-SC,44.00,159.0,4.06,2.56,90.56,XY24,NTT,FINANCE
29,GREENPANEL,-3.38,-47.96,175.07,43.14,166784.0,-87811.0,95267.0,537.00,113.18,51.0,M-SC,14.17,225.0,-0.53,0.62,14.44,XY24,NTT,MISC
21,DEN,-3.30,-48.32,174.93,42.07,76353.0,-40816.0,43648.0,75.00,55.44,40.0,M-SC,5.39,235.0,-0.53,0.29,18.71,AR,NTT,ENTERTAINMENT
25,FINCABLES,-2.81,29.01,61.16,107.91,116496.0,42834.0,190478.0,1641.55,16.18,40.0,M-SC,24.01,220.0,0.37,1.25,43.30,OX40N,ATH,CABLES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-1.47,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.0,2640.93,56.0,H-SC,25.15,168.0,-0.02,0.72,64.47,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.81,29.01,61.16,107.91,116496.0,42834.0,190478.0,1641.55,16.18,40.0,M-SC,24.01,220.0,0.37,1.25,43.30,OX40N,ATH,CABLES
72,SIS,-1.47,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,56.0,H-SC,25.15,168.0,-0.02,0.72,64.47,OX40N,NTT,MISC
83,TTKPRESTIG,-0.58,-12.41,14.28,0.09,12605.0,-12509.0,88268.0,770.00,104.91,72.0,M-SC,9.12,250.0,-0.99,0.58,57.17,OX40N,NTT,DURABLES
16,CERA,-1.72,-21.40,57.61,23.89,79654.0,-37639.0,138264.0,9475.00,-24.11,43.0,H-SC,15.55,153.0,-0.47,0.91,34.41,OX40N,NTT,CERAMICS
43,INDIGOPNTS,0.28,-24.15,31.86,0.02,42185.0,-42152.0,132407.0,1408.00,102.01,58.0,M-SC,3.55,222.0,-1.00,0.87,50.23,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.81,29.01,61.16,107.91,116496.0,42834.0,190478.0,1641.55,16.18,40.0,M-SC,24.01,220.0,0.37,1.25,43.30,OX40N,ATH,CABLES
73,SONACOMS,2.97,21.74,13.92,38.69,17142.0,21989.0,123148.0,801.69,-3.59,79.0,M-MC,23.18,193.0,1.28,0.81,74.72,AR,ATH,AUTO
68,SATIN,-4.00,41.58,7.24,51.83,28321.0,114886.0,391170.0,274.00,27.46,55.0,H-SC,44.00,159.0,4.06,2.56,90.56,XY24,NTT,FINANCE
91,ZYDUSLIFE,-1.20,20.22,12.82,35.63,32299.0,42366.0,251940.0,1286.17,4.50,58.0,H-MC,16.88,120.0,1.31,1.65,32.47,AR,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-0.35,2.79,87.20,92.42,249669.0,7759.0,286318.0,400.00,145.69,57.0,H-SC,20.12,174.0,0.03,1.87,57.72,XY24,NTT,BANKS
75,SURYODAY,-2.40,2.28,20.29,23.03,37163.0,4090.0,183161.0,216.00,99.56,54.0,H-SC,21.88,166.0,0.11,1.20,55.47,XR,NTT,BANKS
74,STARHEALTH,-2.74,13.47,29.77,47.26,94967.0,37879.0,319002.0,761.00,79.18,56.0,H-SC,19.34,173.0,0.40,2.09,38.43,XY24,NTT,INSURANCE
68,SATIN,-4.00,41.58,7.24,51.83,28321.0,114886.0,391170.0,274.00,27.46,55.0,H-SC,44.00,159.0,4.06,2.56,90.56,XY24,NTT,FINANCE
25,FINCABLES,-2.81,29.01,61.16,107.91,116496.0,42834.0,190478.0,1641.55,16.18,40.0,M-SC,24.01,220.0,0.37,1.25,43.30,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,-1.20,20.22,12.82,35.63,32299.0,42366.0,251940.0,1286.17,4.50,58.0,H-MC,16.88,120.0,1.31,1.65,32.47,AR,ATH,PHARMA
73,SONACOMS,2.97,21.74,13.92,38.69,17142.0,21989.0,123148.0,801.69,-3.59,79.0,M-MC,23.18,193.0,1.28,0.81,74.72,AR,ATH,AUTO
25,FINCABLES,-2.81,29.01,61.16,107.91,116496.0,42834.0,190478.0,1641.55,16.18,40.0,M-SC,24.01,220.0,0.37,1.25,43.30,OX40N,ATH,CABLES
75,SURYODAY,-2.40,2.28,20.29,23.03,37163.0,4090.0,183161.0,216.00,99.56,54.0,H-SC,21.88,166.0,0.11,1.20,55.47,XR,NTT,BANKS
72,SIS,-1.47,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,56.0,H-SC,25.15,168.0,-0.02,0.72,64.47,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-0.53,-14.44,38.96,18.89,66704.0,-28898.0,171211.0,2244.41,-27.92,30.0,X-MC,4.62,66.0,-0.43,1.12,0.00,X40,ATH,INSURANCE
87,VBL,-0.50,-6.23,44.37,35.37,131406.0,-19682.0,296160.0,670.16,-17.21,31.0,X-LC,8.00,13.0,-0.15,1.94,21.72,X40N,ATH,FMCG
58,PGHH,-0.57,-34.57,101.75,32.01,142157.0,-73808.0,139712.0,17616.87,-55.72,35.0,X-MC,20.31,57.0,-0.52,0.91,0.00,X40,ATH,FMCG
23,DMART,-0.09,-5.11,36.58,29.60,86638.0,-12756.0,236844.0,5391.45,-19.96,37.0,X-LC,2.26,14.0,-0.15,1.55,8.26,X40N,ATH,FMCG
81,TMPV,1.37,-23.44,78.39,36.58,213569.0,-83397.0,272444.0,600.00,-83.62,41.0,X-LC,8.09,4.0,-0.39,1.78,14.50,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,-1.09,-9.17,37.97,25.32,88889.0,-23645.0,234104.0,680.00,-14.15,42.0,X-MC,2.15,68.0,-0.27,1.53,21.84,XY24,NTT,PAINTS
23,DMART,-0.09,-5.11,36.58,29.60,86638.0,-12756.0,236844.0,5391.45,-19.96,37.0,X-LC,2.26,14.0,-0.15,1.55,8.26,X40N,ATH,FMCG
19,COLPAL,1.97,-22.52,80.52,39.86,164301.0,-59315.0,204050.0,3683.41,-6.30,51.0,X-MC,2.90,62.0,-0.36,1.34,15.42,XY25,ATH,FMCG
17,CIPLA,-0.71,14.92,16.12,33.43,28372.0,22845.0,176006.0,1648.14,-11.14,48.0,X-LC,3.09,18.0,0.81,1.15,20.15,X40N,ATH,PHARMA
8,BAJAJHLDNG,0.57,-6.33,36.26,27.63,64576.0,-12033.0,178092.0,14274.15,-13.24,49.0,X-LC,3.79,28.0,-0.19,1.17,21.27,X40,ATH,FINANCE

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
39,ICICIGI,-0.53,-14.44,38.96,18.89,66704.0,-28898.0,171211.0,2244.41,-27.92,30.0,X-MC,4.62,66.0,-0.43,1.12,0.00,X40,ATH,INSURANCE
58,PGHH,-0.57,-34.57,101.75,32.01,142157.0,-73808.0,139712.0,17616.87,-55.72,35.0,X-MC,20.31,57.0,-0.52,0.91,0.00,X40,ATH,FMCG
47,ITC,0.57,-26.00,60.88,19.06,153254.0,-88435.0,251731.0,452.00,-59.56,42.0,X-LC,12.65,1.0,-0.58,1.65,1.96,X40,NTT,FMCG
35,HDFCLIFE,-0.60,-7.72,43.82,32.71,60572.0,-11571.0,138229.0,811.41,-28.00,46.0,X-LC,15.06,31.0,-0.19,0.91,3.84,X40,ATH,INSURANCE
65,RELIANCE,1.91,-15.18,47.72,25.30,81344.0,-30502.0,170461.0,1952.00,-17.34,55.0,X-LC,7.34,21.0,-0.37,1.12,4.97,XY25,BTT,REFINERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.88,-55.36,202.89,35.20,116532.0,-71234.0,57436.0,2096.00,-24.77,50.0,X-SC,18.41,91.0,-0.61,0.38,13.91,X40,NTT,FOOTWEAR
64,RELAXO,19.99,-43.02,167.30,52.31,138376.0,-62449.0,82711.0,1176.00,-39.31,68.0,X-SC,12.15,92.0,-0.45,0.54,84.93,X40N,NTT,FOOTWEAR
60,QUESS,-0.48,19.80,45.16,73.90,57778.0,21147.0,127940.0,424.00,-35.54,68.0,X-SC,29.62,80.0,0.37,0.84,74.41,XY24,NTT,MISC
35,HDFCLIFE,-0.60,-7.72,43.82,32.71,60572.0,-11571.0,138229.0,811.41,-28.00,46.0,X-LC,15.06,31.0,-0.19,0.91,3.84,X40,ATH,INSURANCE
58,PGHH,-0.57,-34.57,101.75,32.01,142157.0,-73808.0,139712.0,17616.87,-55.72,35.0,X-MC,20.31,57.0,-0.52,0.91,0.00,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.57,-26.00,60.88,19.06,153254.0,-88435.0,251731.0,452.00,-59.56,42.0,X-LC,12.65,1.0,-0.58,1.65,1.96,X40,NTT,FMCG
79,TCS,3.00,-33.45,86.62,24.20,267060.0,-154961.0,308312.0,4230.71,-43.63,63.0,X-LC,20.88,2.0,-0.58,2.02,14.97,X40,ATH,IT
45,INFY,1.76,-25.02,79.04,34.24,185426.0,-78290.0,234598.0,1972.00,-40.86,54.0,X-LC,21.32,3.0,-0.42,1.54,11.78,X40,NTT,IT
81,TMPV,1.37,-23.44,78.39,36.58,213569.0,-83397.0,272444.0,600.00,-83.62,41.0,X-LC,8.09,4.0,-0.39,1.78,14.50,XY24,NTT,AUTO
59,PIDILITIND,0.51,11.09,6.55,18.37,10268.0,15650.0,156760.0,1670.26,-22.17,51.0,X-LC,8.19,5.0,1.52,1.03,23.08,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.50,-24.05,74.98,32.89,43965.0,-18570.0,58636.0,1800.00,-375.91,67.0,L-MC,11.15,258.0,-0.42,0.38,44.56,XR,NTT,BANKS
3,ALKYLAMINE,-2.72,-21.73,145.99,92.54,115369.0,-21938.0,79025.0,4520.85,-16.24,52.0,H-SC,11.59,142.0,-0.19,0.52,50.06,SR,ATH,CHEMICALS
64,RELAXO,19.99,-43.02,167.30,52.31,138376.0,-62449.0,82711.0,1176.00,-39.31,68.0,X-SC,12.15,92.0,-0.45,0.54,84.93,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,-0.58,-12.41,14.28,0.09,12605.0,-12509.0,88268.0,770.00,104.91,72.0,M-SC,9.12,250.0,-0.99,0.58,57.17,OX40N,NTT,DURABLES
72,SIS,-1.47,-0.37,21.72,21.26,24026.0,-413.0,110619.0,528.00,2640.93,56.0,H-SC,25.15,168.0,-0.02,0.72,64.47,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
83,TTKPRESTIG,-0.58,-12.41,14.28,0.09,12605.0,-12509.0,88268.0,770.00,104.91,72.0,M-SC,9.12,250.0,-0.99,0.58,57.17,OX40N,NTT,DURABLES
64,RELAXO,19.99,-43.02,167.30,52.31,138376.0,-62449.0,82711.0,1176.00,-39.31,68.0,X-SC,12.15,92.0,-0.45,0.54,84.93,X40N,NTT,FOOTWEAR
73,SONACOMS,2.97,21.74,13.92,38.69,17142.0,21989.0,123148.0,801.69,-3.59,79.0,M-MC,23.18,193.0,1.28,0.81,74.72,AR,ATH,AUTO
60,QUESS,-0.48,19.80,45.16,73.90,57778.0,21147.0,127940.0,424.00,-35.54,68.0,X-SC,29.62,80.0,0.37,0.84,74.41,XY24,NTT,MISC
49,JSWINFRA,0.71,16.33,0.09,16.43,232.0,36210.0,257984.0,342.00,-0.34,63.0,X-MC,17.90,61.0,156.08,1.69,46.27,X40N,NTT,REALTY

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.37
1     25       42.64
2     50       72.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.65
LC    30.26
MC    26.10
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.76
X40      24.66
X40N     17.43
XR        8.82
OX40N     7.00
AR        6.99
XY25      6.46
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.26
H-SC    22.99
X-MC    20.90
X-SC    10.10
M-SC    10.01
H-MC     2.73
M-MC     2.09
H-LC     1.20
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.13        -22.53   65.52
FINANCE             11.20         -7.78   54.49
IT                  10.25        -43.91  115.13
MISC                 7.16        -22.44   74.97
AUTO                 6.67         -7.48   47.57
BANKS                5.90         -0.62   47.11
PAINTS               5.39        -19.78   40.21
INSURANCE            5.19         -4.66   39.96
PHARMA               5.18          6.40   22.57
ELECTRICAL           4.11        -12.66   52.28
CHEMICALS            2.14        -24.45   98.27
HEALTHCARE           2.05        -14.19   43.99
APPARELS             1.83          3.89   28.40
FOOTWEAR             1.83        -58.60  122.19
AC                   1.80        -15.68   47.05
REALTY               1.69         14.04    0.09
DURABLES             1.64        -54.23   91.75
BREWERIES            1.55          1.04   19.51
TRAVEL               1.52        -93.66  190.63
CERAMICS             1.39        -44.88   88.89
ENGINEERING          1.29        -23.20   79.55
CABLES               1.25         22.49   61.16
REFINERIES           1.12        -17.89   47.72
JEWELLERY            1.12        -87.22  152.27
CEMENT               1.08        -62.15  183.45
ENTERTAINMENT        0.72        -76.48  181.73
TEXTILES             0.41        -48.21   90.48
HOTELS               0.40        -86.09  151.73

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3356955.0     21
X40       1905540.0     19
XR        1329475.0     13
AR        1107515.0      9
X40N      1056810.0     13
OX40N      724204.0     10
XY25       449487.0      5
SR         282399.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3259121.0     24
X-LC        1958573.0     21
X-MC        1523907.0     15
M-SC        1390216.0     14
X-SC        1260694.0      9
H-MC         281664.0      2
L-SC         207116.0      2
M-LC         169587.0      1
M-MC          67064.0      2
H-LC          50478.0      1
L-MC          43965.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1012514.0     10
H-SC       XY24       949509.0      6
           AR         931243.0      5
M-SC       XY24       815059.0      6
H-SC       XR         790966.0      7
X-SC       XY24       749385.0      4
X-MC       X40        681484.0      7
X-LC       X40N       392835.0      6
X-MC       X40N       364208.0      4
X-LC       XY24       355947.0      2
H-SC       OX40N      305004.0      4
M-SC       OX40N      304667.0      5
X-SC       X40N       299767.0      3
H-SC       SR         282399.0      2
H-MC       XY24       249365.0      1
X-MC       XY25       240525.0      2
           XY24       237690.0      2
X-SC       X40        211542.0      2
M-SC       XR         194137.0      2
M-LC       XR         169587.0      1
X-LC       XY25       159040.0      2
L-SC       OX40N      114533.0      1
           XR          92583.0      1
M-SC       AR          76353.0      1
H-LC       AR          50478.0      1
M-MC       XY25        49922.0      1
L-MC       XR          43965.0      1
X-LC       XR          38237.0      1
H-MC       AR          32299.0      1
M-MC       AR          17142.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 28.0 seconds