<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-06 15:47:44
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.51 C
-------------------
Today PnL: 1.76 L (1.18%)
Current PnL: -31.99 L (-17.54%)
CY Booked + Current PnL: -29.91 L (-16.4%)
-------------------
Total profit:  1.74 L
Total loss:  -33.73 L
-------------------
Total Booked + Current PnL: 12.96 L (9.29%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.38%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.04 C (68.96%)
===================
Deployed:  1.40 C
Current:  1.51 C
CAGR/XIRR %: 3.98%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.82,4.99,15.79,21.57,16243.0,4890.0,102870.0,397.04,-9.67,67.0,H-SC,3.21,167.0,0.30,0.68,32.93,XR,ATH,FINANCE
53,M&M,2.80,7.11,15.20,23.38,22577.0,9855.0,148536.0,3802.40,-9.22,60.0,X-LC,7.77,25.0,0.44,0.98,12.61,X40N,ATH,AUTO
59,PIDILITIND,4.20,0.74,17.50,18.37,24876.0,1040.0,142150.0,1670.26,-29.43,60.0,X-LC,5.89,5.0,0.04,0.94,11.61,X40,ATH,CHEMICALS
51,KOTAKBANK,1.41,0.63,20.35,21.11,28356.0,870.0,139342.0,453.24,-13.74,49.0,X-LC,7.75,12.0,0.03,0.92,6.56,X40,ATH,BANKS
83,TTKPRESTIG,-0.42,-30.84,44.72,0.09,31169.0,-31078.0,69699.0,770.00,61.79,61.0,M-SC,17.28,250.0,-1.00,0.46,24.11,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,13.99,-25.11,158.54,93.63,119882.0,-25347.0,75616.0,4546.37,-19.73,74.0,H-SC,18.57,142.0,-0.21,0.50,42.78,SR,ATH,CHEMICALS
86,VALIANTORG,8.83,-36.85,175.79,74.15,181607.0,-60296.0,103309.0,838.00,-285.90,67.0,H-SC,15.89,145.0,-0.33,0.68,53.74,XR,NTT,CHEMICALS
81,TMPV,5.29,-18.47,67.53,36.58,195906.0,-65739.0,290102.0,600.00,-82.53,58.0,X-LC,4.92,4.0,-0.34,1.92,20.91,XY24,NTT,AUTO
62,RAJOOENG,4.90,-42.60,143.20,39.61,84259.0,-43660.0,58840.0,143.10,-61.21,45.0,H-SC,23.56,136.0,-0.52,0.39,26.05,AR,ATH,MISC
77,TANLA,4.47,-36.48,242.02,117.25,416243.0,-98774.0,171987.0,1922.32,-35.93,66.0,H-SC,17.91,147.0,-0.24,1.14,50.58,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-2.64,-10.09,34.87,21.26,34811.0,-11200.0,99832.0,528.00,2373.58,74.0,H-SC,8.62,168.0,-0.32,0.66,48.44,OX40N,NTT,MISC
58,PGHH,-2.03,-25.40,76.95,32.01,122578.0,-54224.0,159296.0,17616.87,-49.54,44.0,X-MC,17.69,57.0,-0.44,1.05,8.95,X40,ATH,FMCG
84,UNITDSPR,-1.92,-5.22,27.41,20.77,60832.0,-12212.0,221932.0,1644.00,-15.87,44.0,X-MC,2.86,64.0,-0.20,1.47,5.87,X40N,NTT,BREWERIES
65,RELIANCE,-1.76,-7.70,35.75,25.30,66312.0,-15474.0,185489.0,1952.00,-10.03,60.0,X-LC,3.87,21.0,-0.23,1.23,10.22,XY25,BTT,REFINERIES
37,HONAUT,-1.65,-21.75,93.36,51.31,140880.0,-41938.0,150900.0,58357.33,-34.96,47.0,X-SC,12.49,90.0,-0.30,1.00,14.64,X40N,ATH,ELECTRICAL

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.82,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,56.0,M-MC,18.97,193.0,0.02,0.67,44.23,AR,ATH,AUTO
9,BANDHANBNK,1.18,0.48,91.50,92.42,256108.0,1340.0,279899.0,400.00,139.94,77.0,H-SC,12.50,174.0,0.01,1.85,54.19,XY24,NTT,BANKS
74,STARHEALTH,0.67,0.78,46.12,47.26,130665.0,2192.0,283315.0,761.00,59.02,65.0,H-SC,8.47,173.0,0.02,1.87,46.72,XY24,NTT,INSURANCE

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.90,32.41,57.02,107.91,111474.0,47855.0,195499.0,1641.55,19.23,73.0,M-SC,15.46,220.0,0.43,1.29,47.08,OX40N,ATH,CABLES
72,SIS,-2.64,-10.09,34.87,21.26,34811.0,-11200.0,99832.0,528.00,2373.58,74.0,H-SC,8.62,168.0,-0.32,0.66,48.44,OX40N,NTT,MISC
16,CERA,0.23,-29.67,76.15,23.89,94210.0,-52186.0,123717.0,9475.00,-32.22,62.0,H-SC,11.61,153.0,-0.55,0.82,18.89,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.42,-30.84,44.72,0.09,31169.0,-31078.0,69699.0,770.00,61.79,61.0,M-SC,17.28,250.0,-1.00,0.46,24.11,OX40N,NTT,DURABLES
50,KANSAINER,3.76,-32.77,68.79,13.47,124707.0,-88380.0,181287.0,340.00,-42.28,58.0,H-SC,16.25,162.0,-0.71,1.20,26.63,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.9,32.41,57.02,107.91,111474.0,47855.0,195499.0,1641.55,19.23,73.0,M-SC,15.46,220.0,0.43,1.29,47.08,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,1.18,0.48,91.50,92.42,256108.0,1340.0,279899.0,400.00,139.94,77.0,H-SC,12.50,174.0,0.01,1.85,54.19,XY24,NTT,BANKS
74,STARHEALTH,0.67,0.78,46.12,47.26,130665.0,2192.0,283315.0,761.00,59.02,65.0,H-SC,8.47,173.0,0.02,1.87,46.72,XY24,NTT,INSURANCE
25,FINCABLES,-0.90,32.41,57.02,107.91,111474.0,47855.0,195499.0,1641.55,19.23,73.0,M-SC,15.46,220.0,0.43,1.29,47.08,OX40N,ATH,CABLES
68,SATIN,2.92,7.38,41.40,51.83,122824.0,20393.0,296677.0,274.00,-4.07,74.0,H-SC,13.47,159.0,0.17,1.96,44.53,XY24,NTT,FINANCE
55,MASFIN,-0.82,4.99,15.79,21.57,16243.0,4890.0,102870.0,397.04,-9.67,67.0,H-SC,3.21,167.0,0.30,0.68,32.93,XR,ATH,FINANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-0.90,32.41,57.02,107.91,111474.0,47855.0,195499.0,1641.55,19.23,73.0,M-SC,15.46,220.0,0.43,1.29,47.08,OX40N,ATH,CABLES
55,MASFIN,-0.82,4.99,15.79,21.57,16243.0,4890.0,102870.0,397.04,-9.67,67.0,H-SC,3.21,167.0,0.30,0.68,32.93,XR,ATH,FINANCE
73,SONACOMS,0.82,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,56.0,M-MC,18.97,193.0,0.02,0.67,44.23,AR,ATH,AUTO
91,ZYDUSLIFE,2.91,-1.00,37.00,35.63,76766.0,-2099.0,207475.0,1286.17,-13.96,58.0,H-MC,3.78,120.0,-0.03,1.37,9.09,AR,ATH,PHARMA
42,INDIAMART,0.20,-11.61,133.88,106.72,145951.0,-14320.0,109016.0,4810.62,-60.16,41.0,H-SC,9.34,140.0,-0.10,0.72,4.74,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.92,-22.83,57.46,21.51,107271.0,-55235.0,186689.0,1872.35,-18.94,29.0,X-LC,10.84,8.0,-0.51,1.23,0.00,X40,ATH,IT
45,INFY,-0.93,-20.54,68.95,34.24,171419.0,-64274.0,248614.0,1972.00,-37.59,35.0,X-LC,14.91,3.0,-0.37,1.64,1.31,X40,NTT,IT
79,TCS,0.33,-28.51,77.04,26.57,255167.0,-132059.0,331214.0,4311.59,-39.36,43.0,X-LC,13.99,2.0,-0.52,2.19,3.37,X40,ATH,IT
58,PGHH,-2.03,-25.40,76.95,32.01,122578.0,-54224.0,159296.0,17616.87,-49.54,44.0,X-MC,17.69,57.0,-0.44,1.05,8.95,X40,ATH,FMCG
84,UNITDSPR,-1.92,-5.22,27.41,20.77,60832.0,-12212.0,221932.0,1644.00,-15.87,44.0,X-MC,2.86,64.0,-0.20,1.47,5.87,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,0.27,7.93,34.53,45.20,71456.0,15198.0,206940.0,1856.00,23.58,46.0,X-MC,1.85,79.0,0.21,1.37,13.43,XY25,NTT,AC
84,UNITDSPR,-1.92,-5.22,27.41,20.77,60832.0,-12212.0,221932.0,1644.00,-15.87,44.0,X-MC,2.86,64.0,-0.20,1.47,5.87,X40N,NTT,BREWERIES
65,RELIANCE,-1.76,-7.70,35.75,25.30,66312.0,-15474.0,185489.0,1952.00,-10.03,60.0,X-LC,3.87,21.0,-0.23,1.23,10.22,XY25,BTT,REFINERIES
81,TMPV,5.29,-18.47,67.53,36.58,195906.0,-65739.0,290102.0,600.00,-82.53,58.0,X-LC,4.92,4.0,-0.34,1.92,20.91,XY24,NTT,AUTO
19,COLPAL,-1.00,-18.09,72.77,41.51,156972.0,-47655.0,215710.0,3726.84,-0.92,61.0,X-MC,5.20,62.0,-0.30,1.43,20.60,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.92,-22.83,57.46,21.51,107271.0,-55235.0,186689.0,1872.35,-18.94,29.0,X-LC,10.84,8.0,-0.51,1.23,0.00,X40,ATH,IT
45,INFY,-0.93,-20.54,68.95,34.24,171419.0,-64274.0,248614.0,1972.00,-37.59,35.0,X-LC,14.91,3.0,-0.37,1.64,1.31,X40,NTT,IT
79,TCS,0.33,-28.51,77.04,26.57,255167.0,-132059.0,331214.0,4311.59,-39.36,43.0,X-LC,13.99,2.0,-0.52,2.19,3.37,X40,ATH,IT
1,ABBOTINDIA,3.93,-11.77,33.82,18.07,53368.0,-21055.0,157800.0,35195.00,-24.86,58.0,X-MC,11.84,58.0,-0.39,1.04,4.45,X40,ATH,PHARMA
84,UNITDSPR,-1.92,-5.22,27.41,20.77,60832.0,-12212.0,221932.0,1644.00,-15.87,44.0,X-MC,2.86,64.0,-0.20,1.47,5.87,X40N,NTT,BREWERIES

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.73,-60.91,289.60,52.31,164342.0,-88412.0,56748.0,1176.00,-58.38,52.0,X-SC,24.99,92.0,-0.54,0.38,26.88,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.89,-53.24,189.12,35.20,113795.0,-68499.0,60171.0,2096.00,-21.16,50.0,X-SC,26.13,91.0,-0.60,0.40,19.33,X40,NTT,FOOTWEAR
60,QUESS,-0.26,-8.61,90.29,73.90,88119.0,-9198.0,97595.0,424.00,-50.96,72.0,X-SC,14.39,80.0,-0.10,0.65,31.29,XY24,NTT,MISC
51,KOTAKBANK,1.41,0.63,20.35,21.11,28356.0,870.0,139342.0,453.24,-13.74,49.0,X-LC,7.75,12.0,0.03,0.92,6.56,X40,ATH,BANKS
59,PIDILITIND,4.20,0.74,17.50,18.37,24876.0,1040.0,142150.0,1670.26,-29.43,60.0,X-LC,5.89,5.0,0.04,0.94,11.61,X40,ATH,CHEMICALS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.24,-18.16,45.48,19.06,126610.0,-61779.0,278387.0,452.00,-55.12,55.0,X-LC,15.60,1.0,-0.49,1.84,7.99,X40,NTT,FMCG
79,TCS,0.33,-28.51,77.04,26.57,255167.0,-132059.0,331214.0,4311.59,-39.36,43.0,X-LC,13.99,2.0,-0.52,2.19,3.37,X40,ATH,IT
45,INFY,-0.93,-20.54,68.95,34.24,171419.0,-64274.0,248614.0,1972.00,-37.59,35.0,X-LC,14.91,3.0,-0.37,1.64,1.31,X40,NTT,IT
81,TMPV,5.29,-18.47,67.53,36.58,195906.0,-65739.0,290102.0,600.00,-82.53,58.0,X-LC,4.92,4.0,-0.34,1.92,20.91,XY24,NTT,AUTO
59,PIDILITIND,4.20,0.74,17.50,18.37,24876.0,1040.0,142150.0,1670.26,-29.43,60.0,X-LC,5.89,5.0,0.04,0.94,11.61,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,3.96,-30.10,90.12,32.89,48633.0,-23242.0,53965.0,1800.00,-354.20,68.0,L-MC,4.51,258.0,-0.48,0.36,32.83,XR,NTT,BANKS
12,BOSCH-HCIL,0.92,-36.75,58.09,-0.01,46958.0,-46969.0,80836.0,2282.00,16443.48,62.0,M-SC,3.31,231.0,-1.00,0.53,37.59,OX40N,BTT,AC
72,SIS,-2.64,-10.09,34.87,21.26,34811.0,-11200.0,99832.0,528.00,2373.58,74.0,H-SC,8.62,168.0,-0.32,0.66,48.44,OX40N,NTT,MISC
73,SONACOMS,0.82,0.79,38.01,39.09,38753.0,796.0,101955.0,804.02,-20.20,56.0,M-MC,18.97,193.0,0.02,0.67,44.23,AR,ATH,AUTO
55,MASFIN,-0.82,4.99,15.79,21.57,16243.0,4890.0,102870.0,397.04,-9.67,67.0,H-SC,3.21,167.0,0.30,0.68,32.93,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,1.18,0.48,91.50,92.42,256108.0,1340.0,279899.0,400.00,139.94,77.0,H-SC,12.50,174.0,0.01,1.85,54.19,XY24,NTT,BANKS
72,SIS,-2.64,-10.09,34.87,21.26,34811.0,-11200.0,99832.0,528.00,2373.58,74.0,H-SC,8.62,168.0,-0.32,0.66,48.44,OX40N,NTT,MISC
77,TANLA,4.47,-36.48,242.02,117.25,416243.0,-98774.0,171987.0,1922.32,-35.93,66.0,H-SC,17.91,147.0,-0.24,1.14,50.58,AR,ATH,IT
68,SATIN,2.92,7.38,41.40,51.83,122824.0,20393.0,296677.0,274.00,-4.07,74.0,H-SC,13.47,159.0,0.17,1.96,44.53,XY24,NTT,FINANCE
3,ALKYLAMINE,13.99,-25.11,158.54,93.63,119882.0,-25347.0,75616.0,4546.37,-19.73,74.0,H-SC,18.57,142.0,-0.21,0.50,42.78,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.07
1     25       42.45
2     50       72.54

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.66
LC    31.60
MC    25.72
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.27
X40      25.40
X40N     16.78
XR        9.16
OX40N     6.89
XY25      6.87
AR        6.74
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.41
H-SC    22.30
X-MC    20.77
M-SC    10.04
X-SC     9.77
H-MC     2.61
M-MC     1.98
H-LC     1.27
M-LC     0.92
L-SC     0.55
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.48        -13.13   53.04
FINANCE             10.78        -13.04   62.21
IT                  10.49        -41.99  113.48
MISC                 7.05        -26.01   80.75
AUTO                 6.68         -8.35   48.97
BANKS                5.69         -5.55   54.36
INSURANCE            5.31         -3.11   38.20
PAINTS               5.14        -26.86   48.90
PHARMA               4.81         -1.72   34.42
ELECTRICAL           4.02        -16.46   57.91
CHEMICALS            2.12        -26.35  101.65
HEALTHCARE           1.94        -21.81   53.59
AC                   1.90        -11.04   41.15
DURABLES             1.76        -45.29   80.64
TRAVEL               1.76        -68.75  153.25
APPARELS             1.74         -2.13   36.97
FOOTWEAR             1.71        -71.03  139.61
BREWERIES            1.47         -5.50   27.41
REALTY               1.36         -7.52   25.18
CERAMICS             1.30        -56.73  104.35
CABLES               1.29         24.48   57.02
ENGINEERING          1.28        -25.49   82.89
REFINERIES           1.23         -8.34   35.75
CEMENT               1.12        -58.02  176.24
JEWELLERY            1.05       -100.87  170.67
ENTERTAINMENT        0.73        -73.68  177.26
TEXTILES             0.43        -41.10   81.34
HOTELS               0.34       -121.33  199.40

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3475610.0     21
X40       1860661.0     19
XR        1297693.0     13
X40N      1188255.0     13
AR        1164016.0      9
OX40N      749280.0     10
XY25       403035.0      5
SR         286991.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3414538.0     24
X-LC        1849263.0     21
X-MC        1593729.0     15
M-SC        1397624.0     14
X-SC        1328893.0      9
H-MC         303738.0      2
L-SC         207569.0      2
M-LC         153514.0      1
M-MC          86549.0      2
L-MC          48633.0      1
H-LC          41491.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1087620.0      6
X-LC       X40       1003634.0     10
H-SC       AR         931518.0      5
M-SC       XY24       832563.0      6
H-SC       XR         781174.0      7
X-SC       XY24       773256.0      4
X-MC       X40        650873.0      7
           X40N       488340.0      4
X-LC       X40N       350432.0      6
X-SC       X40N       349483.0      3
X-LC       XY24       329111.0      2
H-SC       OX40N      327235.0      4
M-SC       OX40N      316772.0      5
H-SC       SR         286991.0      2
X-MC       XY25       228428.0      2
H-MC       XY24       226972.0      1
X-MC       XY24       226088.0      2
X-SC       X40        206154.0      2
M-SC       XR         172801.0      2
M-LC       XR         153514.0      1
X-LC       XY25       126811.0      2
L-SC       OX40N      105273.0      1
           XR         102296.0      1
H-MC       AR          76766.0      1
M-SC       AR          75488.0      1
L-MC       XR          48633.0      1
M-MC       XY25        47796.0      1
H-LC       AR          41491.0      1
X-LC       XR          39275.0      1
M-MC       AR          38753.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds