<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-11 15:54:59
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -8.13 K (-0.05%)
Current PnL: -30.74 L (-16.27%)
CY Booked + Current PnL: -26.52 L (-14.04%)
-------------------
Total profit:  4.23 L
Total loss:  -34.97 L
-------------------
Total Booked + Current PnL: 16.35 L (11.19%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.62%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.05 C (65.28%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.57%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-2.43,23.22,3.17,27.12,6895.0,40983.0,217500.0,1486.00,19.37,61.0,X-SC,16.04,87.0,5.94,1.37,49.87,XY24,NTT,HEALTHCARE
80,UNITDSPR,1.75,13.77,6.15,20.77,16382.0,32232.0,266376.0,1644.00,0.92,75.0,X-MC,8.13,64.0,1.97,1.67,28.05,X40N,NTT,BREWERIES
87,ZYDUSLIFE,6.43,25.59,7.89,35.51,20767.0,53637.0,263211.0,1285.01,9.46,69.0,H-MC,15.75,120.0,2.58,1.65,38.52,AR,ATH,PHARMA
52,M&M,-1.62,9.26,8.75,18.82,23010.0,22287.0,262968.0,3762.88,-4.70,64.0,X-LC,5.04,25.0,0.97,1.65,19.29,X40N,ATH,AUTO
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,56.0,H-SC,22.60,168.0,0.02,0.70,65.90,OX40N,NTT,MISC

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,6.43,25.59,7.89,35.51,20767.0,53637.0,263211.0,1285.01,9.46,69.0,H-MC,15.75,120.0,2.58,1.65,38.52,AR,ATH,PHARMA
82,VALIANTORG,4.06,-35.61,170.45,74.15,179567.0,-58256.0,105349.0,838.00,-289.64,70.0,H-SC,4.08,145.0,-0.32,0.66,56.77,XR,NTT,CHEMICALS
68,SIEMENS,2.47,7.77,15.90,24.90,31887.0,14455.0,200550.0,4648.66,68.37,71.0,H-LC,11.54,51.0,0.45,1.26,41.50,AR,ATH,ELECTRICAL
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,56.0,H-SC,22.60,168.0,0.02,0.70,65.90,OX40N,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-3.40,-51.06,192.50,43.14,172465.0,-93486.0,89592.0,537.00,100.90,38.0,M-SC,10.34,225.0,-0.54,0.56,7.90,XY24,NTT,MISC
5,ATULAUTO,-2.96,-14.78,70.82,45.57,118973.0,-29138.0,167994.0,844.00,3640.54,45.0,M-SC,9.76,248.0,-0.24,1.06,29.28,XY24,NTT,AUTO
79,TTKPRESTIG,-2.58,-23.31,30.52,0.09,23587.0,-23494.0,77283.0,770.00,79.30,39.0,M-SC,12.77,250.0,-1.00,0.49,39.10,OX40N,NTT,DURABLES
73,TANLA,-2.44,-30.31,211.74,117.25,399543.0,-82066.0,188695.0,1922.32,-29.77,59.0,H-SC,14.68,147.0,-0.21,1.19,65.21,AR,ATH,IT
55,MEDANTA,-2.43,23.22,3.17,27.12,6895.0,40983.0,217500.0,1486.00,19.37,61.0,X-SC,16.04,87.0,5.94,1.37,49.87,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.0,2664.77,56.0,H-SC,22.6,168.0,0.02,0.7,65.9,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,56.0,H-SC,22.60,168.0,0.02,0.70,65.90,OX40N,NTT,MISC
43,INDIGOPNTS,-1.38,-20.05,25.10,0.02,35030.0,-34997.0,139562.0,1408.00,112.61,62.0,M-SC,5.43,222.0,-1.00,0.88,58.34,OX40N,NTT,PAINTS
16,CERA,-0.81,-21.75,58.33,23.89,80288.0,-38259.0,137644.0,9475.00,-24.58,42.0,H-SC,12.55,153.0,-0.48,0.87,33.80,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-2.58,-23.31,30.52,0.09,23587.0,-23494.0,77283.0,770.00,79.30,39.0,M-SC,12.77,250.0,-1.00,0.49,39.10,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,6.43,25.59,7.89,35.51,20767.0,53637.0,263211.0,1285.01,9.46,69.0,H-MC,15.75,120.0,2.58,1.65,38.52,AR,ATH,PHARMA
55,MEDANTA,-2.43,23.22,3.17,27.12,6895.0,40983.0,217500.0,1486.00,19.37,61.0,X-SC,16.04,87.0,5.94,1.37,49.87,XY24,NTT,HEALTHCARE
58,QUESS,0.14,32.97,30.78,73.90,43708.0,35207.0,142000.0,424.00,-28.37,65.0,X-SC,40.30,80.0,0.81,0.89,95.44,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,56.0,H-SC,22.60,168.0,0.02,0.70,65.90,OX40N,NTT,MISC
70,STARHEALTH,1.70,13.15,30.15,47.26,95900.0,36954.0,318077.0,761.00,78.49,51.0,H-SC,17.00,173.0,0.39,2.00,37.53,XY24,NTT,INSURANCE
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,6.43,25.59,7.89,35.51,20767.0,53637.0,263211.0,1285.01,9.46,69.0,H-MC,15.75,120.0,2.58,1.65,38.52,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,6.43,25.59,7.89,35.51,20767.0,53637.0,263211.0,1285.01,9.46,69.0,H-MC,15.75,120.0,2.58,1.65,38.52,AR,ATH,PHARMA
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
69,SIS,2.39,0.49,20.67,21.26,23063.0,543.0,111575.0,528.00,2664.77,56.0,H-SC,22.60,168.0,0.02,0.70,65.90,OX40N,NTT,MISC
3,ALKYLAMINE,1.62,-17.06,132.15,92.54,110660.0,-17225.0,83738.0,4520.85,-11.24,62.0,H-SC,13.70,142.0,-0.16,0.53,59.01,SR,ATH,CHEMICALS
42,INDIAMART,0.09,-23.32,162.04,100.92,153238.0,-28768.0,94568.0,4675.60,-65.43,41.0,H-SC,12.47,140.0,-0.19,0.59,2.37,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.27,-10.96,47.19,31.05,123157.0,-32138.0,260982.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.30,X40,BTT,BANKS
57,PGHH,-0.32,-36.64,108.36,32.01,146589.0,-78240.0,135280.0,17616.87,-57.19,34.0,X-MC,19.24,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
83,VBL,-1.91,-11.44,53.19,35.66,165730.0,-40263.0,311581.0,669.42,-22.02,37.0,X-LC,7.58,13.0,-0.24,1.96,14.72,X40N,ATH,FMCG
35,HDFCLIFE,-0.74,-8.08,51.38,39.15,118421.0,-20257.0,230480.0,811.41,-31.58,38.0,X-LC,16.11,31.0,-0.17,1.45,0.01,X40,ATH,INSURANCE
56,PAGEIND,-0.57,0.26,33.24,33.59,89442.0,701.0,269080.0,51217.29,-28.15,38.0,X-MC,8.80,55.0,0.01,1.69,27.79,X40,ATH,APPARELS

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.57,-23.76,83.44,39.86,167548.0,-62565.0,200800.0,3683.41,-7.64,43.0,X-MC,1.57,62.0,-0.37,1.26,13.58,XY25,ATH,FMCG
11,BERGEPAINT,-1.32,-1.42,27.11,25.32,68887.0,-3648.0,254101.0,680.00,-6.74,60.0,X-MC,2.25,68.0,-0.05,1.60,33.25,XY24,NTT,PAINTS
8,BAJAJHLDNG,0.69,3.77,23.59,28.24,62667.0,9645.0,265650.0,14274.15,-4.76,67.0,X-LC,2.83,28.0,0.15,1.67,33.70,X40,ATH,FINANCE
23,DMART,0.02,-1.16,32.96,31.42,101573.0,-3618.0,308172.0,5391.45,-17.82,53.0,X-LC,3.06,14.0,-0.04,1.94,11.21,X40N,ATH,FMCG
26,GILLETTE,-0.13,-9.71,43.67,29.72,100111.0,-24651.0,229245.0,10978.86,-30.67,43.0,X-SC,3.30,83.0,-0.25,1.44,5.35,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-0.32,-36.64,108.36,32.01,146589.0,-78240.0,135280.0,17616.87,-57.19,34.0,X-MC,19.24,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.74,-8.08,51.38,39.15,118421.0,-20257.0,230480.0,811.41,-31.58,38.0,X-LC,16.11,31.0,-0.17,1.45,0.01,X40,ATH,INSURANCE
47,ITC,-1.29,-23.03,62.01,24.70,189617.0,-91494.0,305784.0,452.00,-59.56,40.0,X-LC,10.92,1.0,-0.48,1.92,1.25,X40,NTT,FMCG
34,HDFCBANK,-0.27,-10.96,47.19,31.05,123157.0,-32138.0,260982.0,1073.00,-25.96,34.0,X-LC,11.35,26.0,-0.26,1.64,1.30,X40,BTT,BANKS
20,DABUR,-0.37,-19.32,78.12,43.70,156345.0,-47933.0,200135.0,735.00,-26.86,41.0,X-MC,9.24,70.0,-0.31,1.26,1.84,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.82,-54.86,199.49,35.20,115880.0,-70582.0,58088.0,2096.00,-23.90,51.0,X-SC,13.64,91.0,-0.61,0.37,16.70,X40,NTT,FOOTWEAR
62,RELAXO,-0.66,-45.39,178.90,52.31,141814.0,-65890.0,79270.0,1176.00,-41.83,59.0,X-SC,12.08,92.0,-0.46,0.50,77.24,X40N,NTT,FOOTWEAR
57,PGHH,-0.32,-36.64,108.36,32.01,146589.0,-78240.0,135280.0,17616.87,-57.19,34.0,X-MC,19.24,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,0.14,32.97,30.78,73.90,43708.0,35207.0,142000.0,424.00,-28.37,65.0,X-SC,40.30,80.0,0.81,0.89,95.44,XY24,NTT,MISC
2,ACC,-1.31,-40.04,191.54,74.81,307950.0,-107352.0,160776.0,3906.00,-57.46,44.0,X-SC,12.11,85.0,-0.35,1.01,7.41,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-1.29,-23.03,62.01,24.70,189617.0,-91494.0,305784.0,452.00,-59.56,40.0,X-LC,10.92,1.0,-0.48,1.92,1.25,X40,NTT,FMCG
75,TCS,0.82,-28.20,72.99,24.20,242776.0,-130658.0,332615.0,4230.71,-39.36,62.0,X-LC,15.42,2.0,-0.54,2.09,24.03,X40,ATH,IT
45,INFY,0.65,-15.24,65.62,40.38,209399.0,-57362.0,319108.0,1972.00,-36.14,65.0,X-LC,16.24,3.0,-0.27,2.01,20.85,X40,NTT,IT
77,TMPV,0.14,-17.30,72.61,42.75,249868.0,-71983.0,344124.0,600.00,-83.62,56.0,X-LC,5.11,4.0,-0.29,2.16,18.33,XY24,NTT,AUTO
33,HCLTECH,0.60,-8.67,35.74,23.97,101015.0,-26848.0,282638.0,1853.42,-6.95,70.0,X-LC,13.06,8.0,-0.27,1.78,33.37,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.79,-25.52,78.41,32.89,45091.0,-19700.0,57507.0,1800.00,-371.01,51.0,L-MC,13.89,258.0,-0.44,0.36,41.78,XR,NTT,BANKS
62,RELAXO,-0.66,-45.39,178.90,52.31,141814.0,-65890.0,79270.0,1176.00,-41.83,59.0,X-SC,12.08,92.0,-0.46,0.50,77.24,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,1.62,-17.06,132.15,92.54,110660.0,-17225.0,83738.0,4520.85,-11.24,62.0,H-SC,13.70,142.0,-0.16,0.53,59.01,SR,ATH,CHEMICALS
12,BOSCH-HCIL,-0.72,-25.65,34.49,-0.01,32773.0,-32784.0,95021.0,2282.00,19334.78,83.0,M-SC,3.11,231.0,-1.00,0.60,61.74,OX40N,BTT,AC
82,VALIANTORG,4.06,-35.61,170.45,74.15,179567.0,-58256.0,105349.0,838.00,-289.64,70.0,H-SC,4.08,145.0,-0.32,0.66,56.77,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-0.72,-25.65,34.49,-0.01,32773.0,-32784.0,95021.0,2282.00,19334.78,83.0,M-SC,3.11,231.0,-1.00,0.60,61.74,OX40N,BTT,AC
68,SIEMENS,2.47,7.77,15.90,24.90,31887.0,14455.0,200550.0,4648.66,68.37,71.0,H-LC,11.54,51.0,0.45,1.26,41.50,AR,ATH,ELECTRICAL
25,FINCABLES,14.16,52.98,35.91,107.91,81109.0,78224.0,225868.0,1641.55,37.49,73.0,M-SC,17.50,220.0,0.96,1.42,69.93,OX40N,ATH,CABLES
33,HCLTECH,0.60,-8.67,35.74,23.97,101015.0,-26848.0,282638.0,1853.42,-6.95,70.0,X-LC,13.06,8.0,-0.27,1.78,33.37,X40,ATH,IT
80,UNITDSPR,1.75,13.77,6.15,20.77,16382.0,32232.0,266376.0,1644.00,0.92,75.0,X-MC,8.13,64.0,1.97,1.67,28.05,X40N,NTT,BREWERIES

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.75
1     25       44.80
2     50       76.89

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.34
LC    37.75
MC    22.95
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.39
XY24     24.83
X40N     18.47
XR        9.08
XY25      7.18
OX40N     7.07
AR        6.15
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.68
H-SC    19.30
X-MC    18.69
X-SC     9.89
M-SC     9.64
H-MC     2.71
H-LC     1.26
M-MC     1.19
M-LC     0.81
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.40        -21.75   65.60
IT                  11.25        -33.32   99.49
FINANCE              9.24        -16.27   65.13
AUTO                 8.25         -3.01   39.91
MISC                 6.86        -22.42   74.94
BANKS                6.08        -10.51   58.17
PHARMA               5.71          8.78   17.09
INSURANCE            5.57         -4.82   41.88
PAINTS               5.43        -14.09   33.55
ELECTRICAL           4.13         -7.46   45.09
HEALTHCARE           2.07         -8.53   36.86
AC                   1.81        -11.33   41.52
REFINERIES           1.70        -10.37   47.44
APPARELS             1.69          0.26   33.24
BREWERIES            1.67         12.10    6.15
FOOTWEAR             1.65        -68.64  136.25
DURABLES             1.48        -64.97  105.10
TRAVEL               1.46        -92.72  189.21
CABLES               1.42         34.63   35.91
CERAMICS             1.34        -44.39   88.26
ENGINEERING          1.21        -25.73   83.24
CHEMICALS            1.19        -39.92  153.49
CEMENT               1.01        -66.77  191.54
JEWELLERY            0.98       -105.00  176.23
ENTERTAINMENT        0.68        -78.72  185.30
TEXTILES             0.39        -50.42   93.31
HOTELS               0.37        -94.16  162.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3451700.0     20
X40       2028256.0     18
XR        1352278.0     13
X40N      1142049.0     12
AR        1052698.0      8
OX40N      669849.0     10
XY25       557791.0      5
SR         279257.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3282359.0     23
X-LC        2383919.0     20
X-MC        1480532.0     14
M-SC        1384302.0     14
X-SC        1229569.0      9
H-MC         266548.0      2
L-SC         210348.0      2
M-LC         163604.0      1
M-MC          55719.0      1
L-MC          45091.0      1
H-LC          31887.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1155476.0      9
H-SC       XY24       985292.0      5
           AR         923582.0      5
M-SC       XY24       855316.0      6
H-SC       XR         799208.0      7
X-SC       XY24       717014.0      4
X-MC       X40        656789.0      7
X-LC       X40N       500922.0      6
           XY24       423065.0      2
X-MC       X40N       344563.0      3
X-SC       X40N       296564.0      3
H-SC       OX40N      295020.0      4
           SR         279257.0      2
M-SC       OX40N      259598.0      5
X-MC       XY25       253948.0      2
X-LC       XY25       248124.0      2
H-MC       XY24       245781.0      1
X-MC       XY24       225232.0      2
X-SC       X40        215991.0      2
M-SC       XR         192926.0      2
M-LC       XR         163604.0      1
L-SC       OX40N      115231.0      1
           XR          95117.0      1
M-SC       AR          76462.0      1
X-LC       XR          56332.0      1
M-MC       XY25        55719.0      1
L-MC       XR          45091.0      1
H-LC       AR          31887.0      1
H-MC       AR          20767.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 36.0 seconds