<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-30 10:28:32
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.54 C
-------------------
Today PnL: 27.78 K (0.18%)
Current PnL: -30.99 L (-16.99%)
CY Booked + Current PnL: -27.35 L (-15.0%)
-------------------
Total profit:  3.94 L
Total loss:  -34.93 L
-------------------
Total Booked + Current PnL: 15.52 L (11.12%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (65.58%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.32%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,0.78,15.67,1.60,17.52,2612.0,22110.0,163220.0,1658.32,-19.03,65.0,X-LC,8.31,5.0,8.46,1.11,29.08,X40,ATH,CHEMICALS
71,SONACOMS,2.81,28.15,8.23,38.69,10669.0,28472.0,129631.0,801.69,1.54,76.0,M-MC,28.25,193.0,2.67,0.88,83.91,AR,ATH,AUTO
55,MEDANTA,0.43,20.39,5.59,27.12,11879.0,35985.0,212502.0,1486.00,16.68,69.0,X-SC,12.74,87.0,3.03,1.44,46.43,XY24,NTT,HEALTHCARE
81,TTKPRESTIG,-1.96,-13.70,15.98,0.09,13898.0,-13806.0,86971.0,770.00,101.92,60.0,M-SC,12.99,250.0,-0.99,0.59,56.54,OX40N,NTT,DURABLES
82,UNITDSPR,1.29,12.26,7.58,20.77,19924.0,28706.0,262850.0,1644.00,-0.46,78.0,X-MC,5.49,64.0,1.44,1.79,26.35,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,7.21,-12.00,65.43,45.57,113500.0,-23664.0,173468.0,844.0,3764.86,64.0,M-SC,5.06,248.0,-0.21,1.18,33.49,XY24,NTT,AUTO
63,RELAXO,4.98,-46.71,185.82,52.31,143737.0,-67807.0,77353.0,1176.0,-43.28,57.0,X-SC,9.42,92.0,-0.47,0.53,72.95,X40N,NTT,FOOTWEAR
72,STARHEALTH,3.78,17.29,25.56,47.26,84276.0,48595.0,329718.0,761.0,85.21,63.0,H-SC,18.70,173.0,0.58,2.24,42.56,XY24,NTT,INSURANCE
59,QUESS,3.69,28.97,34.84,73.90,47985.0,30936.0,137729.0,424.0,-30.58,75.0,X-SC,36.70,80.0,0.64,0.94,87.75,XY24,NTT,MISC
11,BERGEPAINT,3.47,-4.78,31.60,25.32,77557.0,-12316.0,245433.0,680.0,-9.89,57.0,X-MC,1.64,68.0,-0.16,1.67,27.74,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-4.68,-35.91,105.97,32.01,145018.0,-76672.0,136848.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
73,SURYODAY,-3.91,-9.32,35.68,23.03,57939.0,-16687.0,162384.0,216.00,77.63,37.0,H-SC,22.64,166.0,-0.29,1.10,37.84,XR,NTT,BANKS
39,ICICIGI,-3.56,-13.99,38.22,18.89,65785.0,-27986.0,172123.0,2244.41,-27.68,39.0,X-MC,7.65,66.0,-0.43,1.17,2.54,X40,ATH,INSURANCE
16,CERA,-2.47,-20.13,55.11,23.89,77427.0,-35407.0,140496.0,9475.00,-22.91,48.0,H-SC,13.93,153.0,-0.46,0.95,36.57,OX40N,NTT,CERAMICS
83,VAIBHAVGBL,-2.47,-18.38,96.97,60.77,144664.0,-33591.0,149184.0,521.00,71.90,61.0,H-SC,9.93,160.0,-0.23,1.01,51.78,XR,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.00,23.25,68.69,107.91,124995.0,34326.0,181970.0,1641.55,11.11,36.0,M-SC,19.73,220.0,0.27,1.24,36.90,OX40N,ATH,CABLES
70,SIS,-0.58,-1.70,23.36,21.26,25495.0,-1892.0,109140.0,528.00,2604.66,47.0,H-SC,23.93,168.0,-0.07,0.74,62.27,OX40N,NTT,MISC
81,TTKPRESTIG,-1.96,-13.70,15.98,0.09,13898.0,-13806.0,86971.0,770.00,101.92,60.0,M-SC,12.99,250.0,-0.99,0.59,56.54,OX40N,NTT,DURABLES
16,CERA,-2.47,-20.13,55.11,23.89,77427.0,-35407.0,140496.0,9475.00,-22.91,48.0,H-SC,13.93,153.0,-0.46,0.95,36.57,OX40N,NTT,CERAMICS
67,SFL,0.48,-21.96,62.26,26.63,127405.0,-57585.0,204633.0,1287.00,54.95,65.0,M-SC,25.60,242.0,-0.45,1.39,70.78,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.00,23.25,68.69,107.91,124995.0,34326.0,181970.0,1641.55,11.11,36.0,M-SC,19.73,220.0,0.27,1.24,36.90,OX40N,ATH,CABLES
71,SONACOMS,2.81,28.15,8.23,38.69,10669.0,28472.0,129631.0,801.69,1.54,76.0,M-MC,28.25,193.0,2.67,0.88,83.91,AR,ATH,AUTO
55,MEDANTA,0.43,20.39,5.59,27.12,11879.0,35985.0,212502.0,1486.00,16.68,69.0,X-SC,12.74,87.0,3.03,1.44,46.43,XY24,NTT,HEALTHCARE
59,QUESS,3.69,28.97,34.84,73.90,47985.0,30936.0,137729.0,424.00,-30.58,75.0,X-SC,36.70,80.0,0.64,0.94,87.75,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,3.78,17.29,25.56,47.26,84276.0,48595.0,329718.0,761.00,85.21,63.0,H-SC,18.70,173.0,0.58,2.24,42.56,XY24,NTT,INSURANCE
62,RECLTD,0.11,1.42,19.04,20.74,39233.0,2888.0,206058.0,446.00,11.33,66.0,M-MC,2.14,191.0,0.07,1.40,22.80,XY25,NTT,FINANCE
25,FINCABLES,0.00,23.25,68.69,107.91,124995.0,34326.0,181970.0,1641.55,11.11,36.0,M-SC,19.73,220.0,0.27,1.24,36.90,OX40N,ATH,CABLES
89,ZYDUSLIFE,0.00,18.39,14.46,35.51,35878.0,38543.0,248117.0,1285.01,3.15,52.0,H-MC,16.99,120.0,1.07,1.69,30.57,AR,ATH,PHARMA
71,SONACOMS,2.81,28.15,8.23,38.69,10669.0,28472.0,129631.0,801.69,1.54,76.0,M-MC,28.25,193.0,2.67,0.88,83.91,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,2.81,28.15,8.23,38.69,10669.0,28472.0,129631.0,801.69,1.54,76.0,M-MC,28.25,193.0,2.67,0.88,83.91,AR,ATH,AUTO
89,ZYDUSLIFE,0.00,18.39,14.46,35.51,35878.0,38543.0,248117.0,1285.01,3.15,52.0,H-MC,16.99,120.0,1.07,1.69,30.57,AR,ATH,PHARMA
25,FINCABLES,0.00,23.25,68.69,107.91,124995.0,34326.0,181970.0,1641.55,11.11,36.0,M-SC,19.73,220.0,0.27,1.24,36.90,OX40N,ATH,CABLES
70,SIS,-0.58,-1.70,23.36,21.26,25495.0,-1892.0,109140.0,528.00,2604.66,47.0,H-SC,23.93,168.0,-0.07,0.74,62.27,OX40N,NTT,MISC
54,MASFIN,1.92,-1.78,23.77,21.57,22876.0,-1740.0,96240.0,397.04,-15.54,54.0,H-SC,1.94,167.0,-0.08,0.65,14.71,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-4.68,-35.91,105.97,32.01,145018.0,-76672.0,136848.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.26,-10.72,43.79,28.37,91826.0,-25189.0,209696.0,1073.00,-23.99,38.0,X-LC,10.26,26.0,-0.27,1.42,3.70,X40,BTT,BANKS
85,VBL,0.97,-8.79,48.41,35.37,139464.0,-27753.0,288089.0,670.16,-19.46,39.0,X-LC,7.12,13.0,-0.20,1.96,18.41,X40N,ATH,FMCG
39,ICICIGI,-3.56,-13.99,38.22,18.89,65785.0,-27986.0,172123.0,2244.41,-27.68,39.0,X-MC,7.65,66.0,-0.43,1.17,2.54,X40,ATH,INSURANCE
35,HDFCLIFE,-0.88,-9.75,47.05,32.71,63607.0,-14609.0,135191.0,811.41,-29.56,41.0,X-LC,15.82,31.0,-0.23,0.92,1.56,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,3.47,-4.78,31.60,25.32,77557.0,-12316.0,245433.0,680.00,-9.89,57.0,X-MC,1.64,68.0,-0.16,1.67,27.74,XY24,NTT,PAINTS
19,COLPAL,-1.66,-20.16,75.18,39.86,158081.0,-53095.0,210270.0,3683.41,-3.38,56.0,X-MC,1.67,62.0,-0.34,1.43,18.94,XY25,ATH,FMCG
8,BAJAJHLDNG,0.91,-2.27,30.60,27.63,56858.0,-4315.0,185810.0,14274.15,-9.98,62.0,X-LC,2.65,28.0,-0.08,1.26,26.52,X40,ATH,FINANCE
1,ABBOTINDIA,-0.41,-6.77,23.75,15.37,39601.0,-12115.0,166740.0,34390.26,-20.76,66.0,X-MC,2.80,58.0,-0.31,1.13,12.95,X40,ATH,PHARMA
23,DMART,2.59,-5.10,36.57,29.60,86620.0,-12738.0,236862.0,5391.45,-19.96,43.0,X-LC,2.89,14.0,-0.15,1.61,8.27,X40N,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-4.68,-35.91,105.97,32.01,145018.0,-76672.0,136848.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.88,-9.75,47.05,32.71,63607.0,-14609.0,135191.0,811.41,-29.56,41.0,X-LC,15.82,31.0,-0.23,0.92,1.56,X40,ATH,INSURANCE
64,RELIANCE,0.44,-17.74,52.32,25.30,86492.0,-35649.0,165314.0,1952.00,-20.03,45.0,X-LC,7.91,21.0,-0.41,1.12,1.80,XY25,BTT,REFINERIES
39,ICICIGI,-3.56,-13.99,38.22,18.89,65785.0,-27986.0,172123.0,2244.41,-27.68,39.0,X-MC,7.65,66.0,-0.43,1.17,2.54,X40,ATH,INSURANCE
34,HDFCBANK,-0.26,-10.72,43.79,28.37,91826.0,-25189.0,209696.0,1073.00,-23.99,38.0,X-LC,10.26,26.0,-0.27,1.42,3.70,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.58,-54.91,199.86,35.20,115953.0,-70653.0,58017.0,2096.00,-23.90,53.0,X-SC,16.55,91.0,-0.61,0.39,15.06,X40,NTT,FOOTWEAR
63,RELAXO,4.98,-46.71,185.82,52.31,143737.0,-67807.0,77353.0,1176.00,-43.28,57.0,X-SC,9.42,92.0,-0.47,0.53,72.95,X40N,NTT,FOOTWEAR
35,HDFCLIFE,-0.88,-9.75,47.05,32.71,63607.0,-14609.0,135191.0,811.41,-29.56,41.0,X-LC,15.82,31.0,-0.23,0.92,1.56,X40,ATH,INSURANCE
57,PGHH,-4.68,-35.91,105.97,32.01,145018.0,-76672.0,136848.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
59,QUESS,3.69,28.97,34.84,73.90,47985.0,30936.0,137729.0,424.00,-30.58,75.0,X-SC,36.70,80.0,0.64,0.94,87.75,XY24,NTT,MISC

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.09,-24.67,58.04,19.06,148731.0,-83910.0,256256.0,452.00,-58.75,54.0,X-LC,12.18,1.0,-0.56,1.74,3.79,X40,NTT,FMCG
77,TCS,1.50,-27.10,70.36,24.20,237635.0,-125531.0,337742.0,4230.71,-38.38,76.0,X-LC,16.78,2.0,-0.53,2.29,25.95,X40,ATH,IT
45,INFY,2.20,-19.60,66.98,34.24,168490.0,-61335.0,251553.0,1972.00,-36.87,67.0,X-LC,18.53,3.0,-0.36,1.71,19.86,X40,NTT,IT
79,TMPV,0.12,-24.84,81.71,36.58,218543.0,-88379.0,267462.0,600.00,-84.72,42.0,X-LC,6.86,4.0,-0.40,1.82,12.40,XY24,NTT,AUTO
58,PIDILITIND,0.78,15.67,1.60,17.52,2612.0,22110.0,163220.0,1658.32,-19.03,65.0,X-LC,8.31,5.0,8.46,1.11,29.08,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.66,-25.76,79.00,32.89,45282.0,-19888.0,57319.0,1800.00,-369.61,53.0,L-MC,14.43,258.0,-0.44,0.39,41.32,XR,NTT,BANKS
3,ALKYLAMINE,-0.89,-23.56,151.87,92.54,117215.0,-23782.0,77181.0,4520.85,-18.07,47.0,H-SC,12.91,142.0,-0.20,0.52,46.56,SR,ATH,CHEMICALS
63,RELAXO,4.98,-46.71,185.82,52.31,143737.0,-67807.0,77353.0,1176.00,-43.28,57.0,X-SC,9.42,92.0,-0.47,0.53,72.95,X40N,NTT,FOOTWEAR
81,TTKPRESTIG,-1.96,-13.70,15.98,0.09,13898.0,-13806.0,86971.0,770.00,101.92,60.0,M-SC,12.99,250.0,-0.99,0.59,56.54,OX40N,NTT,DURABLES
70,SIS,-0.58,-1.70,23.36,21.26,25495.0,-1892.0,109140.0,528.00,2604.66,47.0,H-SC,23.93,168.0,-0.07,0.74,62.27,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.58,-11.38,35.72,20.28,76583.0,-27525.0,214399.0,1853.42,-6.95,78.0,X-LC,15.49,8.0,-0.36,1.46,33.39,X40,ATH,IT
77,TCS,1.50,-27.10,70.36,24.20,237635.0,-125531.0,337742.0,4230.71,-38.38,76.0,X-LC,16.78,2.0,-0.53,2.29,25.95,X40,ATH,IT
22,DIXON,0.71,4.73,31.69,37.92,86559.0,12346.0,273144.0,18931.72,-55.49,67.0,X-MC,11.40,54.0,0.14,1.86,48.62,X40N,ATH,IT
71,SONACOMS,2.81,28.15,8.23,38.69,10669.0,28472.0,129631.0,801.69,1.54,76.0,M-MC,28.25,193.0,2.67,0.88,83.91,AR,ATH,AUTO
45,INFY,2.20,-19.60,66.98,34.24,168490.0,-61335.0,251553.0,1972.00,-36.87,67.0,X-LC,18.53,3.0,-0.36,1.71,19.86,X40,NTT,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.34
1     25       42.97
2     50       73.87

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.29
LC    31.87
MC    25.87
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.27
XY24     25.88
X40N     16.63
XR        9.21
AR        7.24
OX40N     7.17
XY25      6.73
SR        0.90
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.75
H-SC    20.70
X-MC    20.42
X-SC    10.69
M-SC    10.34
H-MC     2.78
M-MC     2.28
H-LC     1.22
M-LC     0.90
L-SC     0.56
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.62        -23.11   66.29
IT                  11.30        -35.48  102.42
FINANCE              9.01        -18.16   67.59
MISC                 7.67        -18.75   69.70
AUTO                 7.03         -5.94   45.44
PAINTS               5.70        -17.59   37.64
PHARMA               5.49          8.34   19.40
BANKS                5.46        -12.95   65.14
INSURANCE            5.46         -3.06   37.82
ELECTRICAL           4.32        -11.24   50.20
CHEMICALS            2.25        -22.12   94.20
HEALTHCARE           2.20        -10.28   39.06
APPARELS             1.96          7.12   24.07
AC                   1.85        -17.49   49.34
BREWERIES            1.79         10.92    7.58
FOOTWEAR             1.78        -68.47  136.02
DURABLES             1.69        -55.39   93.19
TRAVEL               1.54        -97.93  197.04
CERAMICS             1.44        -44.23   88.05
ENGINEERING          1.28        -28.99   87.99
CABLES               1.24         18.86   68.69
JEWELLERY            1.17        -85.86  150.44
REFINERIES           1.12        -21.56   52.32
CEMENT               1.10        -65.28  188.93
ENTERTAINMENT        0.74        -78.69  185.26
TEXTILES             0.42        -50.97   94.02
HOTELS               0.40        -93.90  162.30

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3370514.0     20
X40       1795767.0     19
XR        1321793.0     13
AR        1107702.0      9
X40N      1017439.0     12
OX40N      737628.0     10
XY25       445837.0      5
SR         283329.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3300492.0     23
X-LC        1893876.0     21
X-MC        1450880.0     14
M-SC        1398115.0     14
X-SC        1229961.0      9
H-MC         289141.0      2
L-SC         209350.0      2
M-LC         159883.0      1
H-LC          53127.0      1
M-MC          49902.0      2
L-MC          45282.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      985540.0      5
X-LC       X40       942079.0     10
H-SC       AR        931821.0      5
M-SC       XY24      813890.0      6
H-SC       XR        790436.0      7
X-SC       XY24      731506.0      4
X-MC       X40       643160.0      7
X-LC       X40N      390097.0      6
           XY24      356184.0      2
X-MC       X40N      339415.0      3
M-SC       OX40N     313955.0      5
H-SC       OX40N     309366.0      4
X-SC       X40N      287927.0      3
H-SC       SR        283329.0      2
H-MC       XY24      253263.0      1
X-MC       XY25      238174.0      2
           XY24      230131.0      2
X-SC       X40       210528.0      2
M-SC       XR        194063.0      2
X-LC       XY25      168430.0      2
M-LC       XR        159883.0      1
L-SC       OX40N     114307.0      1
           XR         95043.0      1
M-SC       AR         76207.0      1
H-LC       AR         53127.0      1
L-MC       XR         45282.0      1
M-MC       XY25       39233.0      1
X-LC       XR         37086.0      1
H-MC       AR         35878.0      1
M-MC       AR         10669.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 53.0 seconds