<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-20 11:09:43
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.53 C
-------------------
Today PnL: -2.37 K (-0.02%)
Current PnL: -30.58 L (-16.77%)
CY Booked + Current PnL: -28.50 L (-15.63%)
-------------------
Total profit:  4.50 L
Total loss:  -35.08 L
-------------------
Total Booked + Current PnL: 14.37 L (10.3%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.02 C (67.02%)
===================
Deployed:  1.40 C
Current:  1.53 C
CAGR/XIRR %: 4.04%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
49,JSWINFRA,0.22,16.74,-0.26,16.43,-673.0,37115.0,258889.0,342.00,0.11,64.0,X-MC,18.55,61.0,-55.15,1.70,46.78,X40N,NTT,REALTY
59,PIDILITIND,0.17,11.17,6.47,18.37,10149.0,15760.0,156870.0,1670.26,-22.17,51.0,X-LC,8.10,5.0,1.55,1.03,23.17,X40,ATH,CHEMICALS
83,TTKPRESTIG,0.49,-12.15,13.94,0.09,12341.0,-12247.0,88530.0,770.00,105.55,72.0,M-SC,9.54,250.0,-0.99,0.58,57.64,OX40N,NTT,DURABLES
73,SONACOMS,0.18,22.15,13.54,38.69,16731.0,22409.0,123568.0,801.69,-3.19,80.0,M-MC,23.54,193.0,1.34,0.81,75.31,AR,ATH,AUTO
56,MEDANTA,1.08,13.87,11.64,27.12,23396.0,24479.0,200996.0,1486.00,10.34,57.0,X-SC,10.97,87.0,1.05,1.32,38.50,XY24,NTT,HEALTHCARE

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,3.19,-19.97,74.77,39.86,157585.0,-52605.0,210760.0,3683.41,-3.16,60.0,X-MC,2.60,62.0,-0.33,1.38,19.22,XY25,ATH,FMCG
61,RAJESHEXPO,1.78,-83.10,492.00,0.07,114085.0,-113989.0,23188.0,518.00,749.75,41.0,L-SC,35.18,268.0,-1.00,0.15,14.51,OX40N,NTT,JEWELLERY
15,CAMS,1.72,0.11,24.34,24.48,61370.0,280.0,252136.0,950.00,-3.99,47.0,X-SC,5.20,89.0,0.00,1.65,23.39,X40N,NTT,MISC
17,CIPLA,1.66,16.77,14.27,33.43,25521.0,25684.0,178845.0,1648.14,-9.73,56.0,X-LC,3.19,18.0,1.01,1.17,22.09,X40N,ATH,PHARMA
16,CERA,1.55,-19.71,54.30,23.89,76689.0,-34671.0,141232.0,9475.00,-22.43,50.0,H-SC,15.15,153.0,-0.45,0.93,37.29,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
14,CAMPUS,-4.81,-23.82,74.97,33.28,95814.0,-39972.0,127803.0,393.00,-38.69,41.0,M-SC,8.72,218.0,-0.42,0.84,2.63,XY24,NTT,FOOTWEAR
34,HDFCBANK,-4.80,-6.65,37.51,28.37,82246.0,-15621.0,219264.0,1073.00,-20.53,44.0,X-LC,11.05,26.0,-0.19,1.44,8.43,X40,BTT,BANKS
85,VAIBHAVGBL,-2.50,-21.15,103.89,60.77,149725.0,-38656.0,144119.0,521.00,66.39,60.0,H-SC,6.77,160.0,-0.26,0.94,46.63,XR,NTT,JEWELLERY
64,RELAXO,-2.19,-44.27,173.30,52.31,140193.0,-64264.0,80896.0,1176.00,-40.66,64.0,X-SC,12.50,92.0,-0.46,0.53,80.87,X40N,NTT,FOOTWEAR
51,KOTAKBANK,-2.10,2.00,18.52,20.90,26159.0,2776.0,141248.0,452.46,-12.44,47.0,X-LC,3.92,12.0,0.11,0.93,8.21,X40,ATH,BANKS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.2,-0.22,21.53,21.26,23852.0,-247.0,110785.0,528.0,2645.08,56.0,H-SC,24.81,168.0,-0.01,0.73,64.72,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.17,29.06,61.09,107.91,116409.0,42909.0,190553.0,1641.55,16.18,41.0,M-SC,22.90,220.0,0.37,1.25,43.36,OX40N,ATH,CABLES
72,SIS,0.20,-0.22,21.53,21.26,23852.0,-247.0,110785.0,528.00,2645.08,56.0,H-SC,24.81,168.0,-0.01,0.73,64.72,OX40N,NTT,MISC
83,TTKPRESTIG,0.49,-12.15,13.94,0.09,12341.0,-12247.0,88530.0,770.00,105.55,72.0,M-SC,9.54,250.0,-0.99,0.58,57.64,OX40N,NTT,DURABLES
16,CERA,1.55,-19.71,54.30,23.89,76689.0,-34671.0,141232.0,9475.00,-22.43,50.0,H-SC,15.15,153.0,-0.45,0.93,37.29,OX40N,NTT,CERAMICS
43,INDIGOPNTS,-0.11,-24.42,32.34,0.02,42664.0,-42635.0,131924.0,1408.00,101.45,57.0,M-SC,3.59,222.0,-1.00,0.86,49.68,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.17,29.06,61.09,107.91,116409.0,42909.0,190553.0,1641.55,16.18,41.0,M-SC,22.90,220.0,0.37,1.25,43.36,OX40N,ATH,CABLES
73,SONACOMS,0.18,22.15,13.54,38.69,16731.0,22409.0,123568.0,801.69,-3.19,80.0,M-MC,23.54,193.0,1.34,0.81,75.31,AR,ATH,AUTO
68,SATIN,-0.42,40.75,7.87,51.83,30604.0,112590.0,388874.0,274.00,26.15,54.0,H-SC,44.50,159.0,3.68,2.55,89.44,XY24,NTT,FINANCE
91,ZYDUSLIFE,1.13,21.97,11.20,35.63,28628.0,46035.0,255609.0,1286.17,6.31,62.0,H-MC,17.15,120.0,1.61,1.68,34.39,AR,ATH,PHARMA
60,QUESS,1.10,20.64,44.14,73.90,56869.0,22045.0,128838.0,424.00,-34.99,69.0,X-SC,30.72,80.0,0.39,0.84,75.63,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-1.46,1.08,90.36,92.42,254430.0,3015.0,281574.0,400.00,141.38,53.0,H-SC,20.16,174.0,0.01,1.85,55.11,XY24,NTT,BANKS
75,SURYODAY,1.01,3.44,18.94,23.03,35083.0,6161.0,185232.0,216.00,101.75,56.0,H-SC,22.16,166.0,0.18,1.21,57.23,XR,NTT,BANKS
74,STARHEALTH,-0.53,12.21,31.24,47.26,98543.0,34315.0,315438.0,761.00,77.10,52.0,H-SC,19.29,173.0,0.35,2.07,36.89,XY24,NTT,INSURANCE
68,SATIN,-0.42,40.75,7.87,51.83,30604.0,112590.0,388874.0,274.00,26.15,54.0,H-SC,44.50,159.0,3.68,2.55,89.44,XY24,NTT,FINANCE
25,FINCABLES,0.17,29.06,61.09,107.91,116409.0,42909.0,190553.0,1641.55,16.18,41.0,M-SC,22.90,220.0,0.37,1.25,43.36,OX40N,ATH,CABLES

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
91,ZYDUSLIFE,1.13,21.97,11.20,35.63,28628.0,46035.0,255609.0,1286.17,6.31,62.0,H-MC,17.15,120.0,1.61,1.68,34.39,AR,ATH,PHARMA
73,SONACOMS,0.18,22.15,13.54,38.69,16731.0,22409.0,123568.0,801.69,-3.19,80.0,M-MC,23.54,193.0,1.34,0.81,75.31,AR,ATH,AUTO
25,FINCABLES,0.17,29.06,61.09,107.91,116409.0,42909.0,190553.0,1641.55,16.18,41.0,M-SC,22.90,220.0,0.37,1.25,43.36,OX40N,ATH,CABLES
75,SURYODAY,1.01,3.44,18.94,23.03,35083.0,6161.0,185232.0,216.00,101.75,56.0,H-SC,22.16,166.0,0.18,1.21,57.23,XR,NTT,BANKS
72,SIS,0.20,-0.22,21.53,21.26,23852.0,-247.0,110785.0,528.00,2645.08,56.0,H-SC,24.81,168.0,-0.01,0.73,64.72,OX40N,NTT,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,VBL,-0.13,-6.52,44.82,35.37,132324.0,-20608.0,295234.0,670.16,-17.53,30.0,X-LC,7.83,13.0,-0.16,1.93,21.34,X40N,ATH,FMCG
39,ICICIGI,0.61,-14.08,38.37,18.89,65970.0,-28177.0,171932.0,2244.41,-27.68,32.0,X-MC,5.22,66.0,-0.43,1.13,0.61,X40,ATH,INSURANCE
58,PGHH,-0.24,-34.81,102.49,32.01,142666.0,-74320.0,139200.0,17616.87,-55.85,34.0,X-MC,20.35,57.0,-0.52,0.91,0.00,X40,ATH,FMCG
23,DMART,0.61,-4.43,35.60,29.60,84925.0,-11046.0,238554.0,5391.45,-19.43,40.0,X-LC,2.14,14.0,-0.13,1.56,9.04,X40N,ATH,FMCG
81,TMPV,-0.28,-23.82,79.29,36.58,214928.0,-84775.0,271066.0,600.00,-84.72,40.0,X-LC,8.21,4.0,-0.39,1.78,13.92,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,0.79,-8.30,36.66,25.32,86650.0,-21389.0,236360.0,680.00,-13.36,45.0,X-MC,1.76,68.0,-0.25,1.55,23.02,XY24,NTT,PAINTS
23,DMART,0.61,-4.43,35.60,29.60,84925.0,-11046.0,238554.0,5391.45,-19.43,40.0,X-LC,2.14,14.0,-0.13,1.56,9.04,X40N,ATH,FMCG
19,COLPAL,3.19,-19.97,74.77,39.86,157585.0,-52605.0,210760.0,3683.41,-3.16,60.0,X-MC,2.60,62.0,-0.33,1.38,19.22,XY25,ATH,FMCG
17,CIPLA,1.66,16.77,14.27,33.43,25521.0,25684.0,178845.0,1648.14,-9.73,56.0,X-LC,3.19,18.0,1.01,1.17,22.09,X40N,ATH,PHARMA
1,ABBOTINDIA,-0.18,-6.05,25.67,18.07,43133.0,-10825.0,168030.0,35195.00,-20.15,70.0,X-MC,3.64,58.0,-0.25,1.10,11.22,X40,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PGHH,-0.24,-34.81,102.49,32.01,142666.0,-74320.0,139200.0,17616.87,-55.85,34.0,X-MC,20.35,57.0,-0.52,0.91,0.00,X40,ATH,FMCG
39,ICICIGI,0.61,-14.08,38.37,18.89,65970.0,-28177.0,171932.0,2244.41,-27.68,32.0,X-MC,5.22,66.0,-0.43,1.13,0.61,X40,ATH,INSURANCE
47,ITC,0.91,-25.39,59.58,19.06,151209.0,-86374.0,253792.0,452.00,-59.16,47.0,X-LC,12.50,1.0,-0.57,1.66,2.79,X40,NTT,FMCG
35,HDFCLIFE,-0.07,-7.88,44.06,32.71,60801.0,-11804.0,137996.0,811.41,-28.11,45.0,X-LC,15.19,31.0,-0.19,0.90,3.67,X40,ATH,INSURANCE
36,HINDUNILVR,-0.11,-16.69,36.45,13.67,78058.0,-42913.0,214150.0,2922.00,-38.12,48.0,X-LC,5.30,9.0,-0.55,1.40,5.41,XY25,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.20,-54.73,198.68,35.20,115721.0,-70425.0,58245.0,2096.00,-23.61,54.0,X-SC,18.23,91.0,-0.61,0.38,15.51,X40,NTT,FOOTWEAR
64,RELAXO,-2.19,-44.27,173.30,52.31,140193.0,-64264.0,80896.0,1176.00,-40.66,64.0,X-SC,12.50,92.0,-0.46,0.53,80.87,X40N,NTT,FOOTWEAR
60,QUESS,1.10,20.64,44.14,73.90,56869.0,22045.0,128838.0,424.00,-34.99,69.0,X-SC,30.72,80.0,0.39,0.84,75.63,XY24,NTT,MISC
35,HDFCLIFE,-0.07,-7.88,44.06,32.71,60801.0,-11804.0,137996.0,811.41,-28.11,45.0,X-LC,15.19,31.0,-0.19,0.90,3.67,X40,ATH,INSURANCE
58,PGHH,-0.24,-34.81,102.49,32.01,142666.0,-74320.0,139200.0,17616.87,-55.85,34.0,X-MC,20.35,57.0,-0.52,0.91,0.00,X40,ATH,FMCG

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.91,-25.39,59.58,19.06,151209.0,-86374.0,253792.0,452.00,-59.16,47.0,X-LC,12.50,1.0,-0.57,1.66,2.79,X40,NTT,FMCG
79,TCS,-0.40,-33.65,87.20,24.20,268018.0,-155913.0,307360.0,4230.71,-43.95,62.0,X-LC,20.54,2.0,-0.58,2.01,14.62,X40,ATH,IT
45,INFY,-0.18,-25.49,80.17,34.24,186899.0,-79760.0,233128.0,1972.00,-41.22,53.0,X-LC,21.17,3.0,-0.43,1.53,11.08,X40,NTT,IT
81,TMPV,-0.28,-23.82,79.29,36.58,214928.0,-84775.0,271066.0,600.00,-84.72,40.0,X-LC,8.21,4.0,-0.39,1.78,13.92,XY24,NTT,AUTO
59,PIDILITIND,0.17,11.17,6.47,18.37,10149.0,15760.0,156870.0,1670.26,-22.17,51.0,X-LC,8.10,5.0,1.55,1.03,23.17,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.70,-24.70,76.47,32.89,44460.0,-19066.0,58140.0,1800.00,-373.81,64.0,L-MC,11.46,258.0,-0.43,0.38,43.34,XR,NTT,BANKS
3,ALKYLAMINE,0.37,-21.90,146.54,92.54,115545.0,-22114.0,78849.0,4520.85,-16.40,51.0,H-SC,11.59,142.0,-0.19,0.52,49.73,SR,ATH,CHEMICALS
64,RELAXO,-2.19,-44.27,173.30,52.31,140193.0,-64264.0,80896.0,1176.00,-40.66,64.0,X-SC,12.50,92.0,-0.46,0.53,80.87,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,0.49,-12.15,13.94,0.09,12341.0,-12247.0,88530.0,770.00,105.55,72.0,M-SC,9.54,250.0,-0.99,0.58,57.64,OX40N,NTT,DURABLES
72,SIS,0.20,-0.22,21.53,21.26,23852.0,-247.0,110785.0,528.00,2645.08,56.0,H-SC,24.81,168.0,-0.01,0.73,64.72,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-2.19,-44.27,173.30,52.31,140193.0,-64264.0,80896.0,1176.00,-40.66,64.0,X-SC,12.50,92.0,-0.46,0.53,80.87,X40N,NTT,FOOTWEAR
83,TTKPRESTIG,0.49,-12.15,13.94,0.09,12341.0,-12247.0,88530.0,770.00,105.55,72.0,M-SC,9.54,250.0,-0.99,0.58,57.64,OX40N,NTT,DURABLES
60,QUESS,1.10,20.64,44.14,73.90,56869.0,22045.0,128838.0,424.00,-34.99,69.0,X-SC,30.72,80.0,0.39,0.84,75.63,XY24,NTT,MISC
22,DIXON,0.86,5.29,31.00,37.92,85122.0,13790.0,274588.0,18931.72,-55.25,73.0,X-MC,6.63,54.0,0.16,1.80,49.41,X40N,ATH,IT
73,SONACOMS,0.18,22.15,13.54,38.69,16731.0,22409.0,123568.0,801.69,-3.19,80.0,M-MC,23.54,193.0,1.34,0.81,75.31,AR,ATH,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.34
1     25       42.62
2     50       72.74

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.56
LC    30.16
MC    26.29
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.61
X40      24.64
X40N     17.48
XR        8.83
OX40N     7.03
AR        7.00
XY25      6.53
SR        0.89
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    28.16
H-SC    22.94
X-MC    21.04
X-SC    10.12
M-SC     9.95
H-MC     2.76
M-MC     2.11
H-LC     1.20
M-LC     0.80
L-SC     0.55
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.19        -22.06   64.88
FINANCE             11.17         -8.20   55.08
IT                  10.25        -44.05  115.34
MISC                 7.23        -21.41   73.50
AUTO                 6.65         -8.13   48.46
BANKS                5.81         -2.57   49.96
PAINTS               5.40        -19.65   40.06
PHARMA               5.24          7.26   21.45
INSURANCE            5.17         -4.93   40.32
ELECTRICAL           4.11        -12.82   52.50
CHEMICALS            2.16        -23.65   97.01
HEALTHCARE           2.07        -13.62   43.28
APPARELS             1.84          4.41   27.69
AC                   1.81        -15.75   47.13
FOOTWEAR             1.75        -65.43  131.76
REALTY               1.70         14.34   -0.26
DURABLES             1.65        -53.33   90.63
BREWERIES            1.56          1.60   18.84
TRAVEL               1.51        -94.04  191.21
CERAMICS             1.40        -43.74   87.40
ENGINEERING          1.27        -24.84   81.94
CABLES               1.25         22.52   61.09
REFINERIES           1.13        -16.94   46.52
JEWELLERY            1.09        -91.24  157.68
CEMENT               1.08        -62.64  184.32
ENTERTAINMENT        0.71        -76.27  181.39
TEXTILES             0.41        -47.45   89.50
HOTELS               0.40        -86.27  151.97

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3385624.0     21
X40       1911681.0     19
XR        1329212.0     13
AR        1105849.0      9
X40N      1053244.0     13
OX40N      719368.0     10
XY25       439656.0      5
SR         282288.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3271961.0     24
X-LC        1977161.0     21
X-MC        1506700.0     15
M-SC        1399195.0     14
X-SC        1258282.0      9
H-MC         278156.0      2
L-SC         206726.0      2
M-LC         169333.0      1
M-MC          64066.0      2
H-LC          50882.0      1
L-MC          44460.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1026855.0     10
H-SC       XY24       966191.0      6
           AR         932905.0      5
M-SC       XY24       825460.0      6
H-SC       XR         788884.0      7
X-SC       XY24       748546.0      4
X-MC       X40        675610.0      7
X-LC       X40N       390819.0      6
X-MC       X40N       361905.0      4
X-LC       XY24       361031.0      2
M-SC       OX40N      303590.0      5
H-SC       OX40N      301693.0      4
X-SC       X40N       300520.0      3
H-SC       SR         282288.0      2
H-MC       XY24       249528.0      1
X-MC       XY24       234868.0      2
           XY25       234317.0      2
X-SC       X40        209216.0      2
M-SC       XR         193442.0      2
M-LC       XR         169333.0      1
X-LC       XY25       158004.0      2
L-SC       OX40N      114085.0      1
           XR          92641.0      1
M-SC       AR          76703.0      1
H-LC       AR          50882.0      1
M-MC       XY25        47335.0      1
L-MC       XR          44460.0      1
X-LC       XR          40452.0      1
H-MC       AR          28628.0      1
M-MC       AR          16731.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 66.0 seconds