<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-07 09:55:12
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.62 C
-------------------
Today PnL: 25.05 K (0.15%)
Current PnL: -29.88 L (-15.81%)
CY Booked + Current PnL: -25.66 L (-13.58%)
-------------------
Total profit:  3.68 L
Total loss:  -33.55 L
-------------------
Total Booked + Current PnL: 17.21 L (11.79%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.6%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.04 C (64.4%)
===================
Deployed:  1.46 C
Current:  1.62 C
CAGR/XIRR %: 4.85%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,0.88,24.64,1.99,27.12,4378.0,43490.0,220007.0,1486.00,20.80,67.0,X-SC,15.38,87.0,9.93,1.38,51.60,XY24,NTT,HEALTHCARE
79,TTKPRESTIG,0.76,-17.72,21.64,0.09,17945.0,-17854.0,82923.0,770.00,92.53,50.0,M-SC,13.87,250.0,-0.99,0.52,49.25,OX40N,NTT,DURABLES
80,UNITDSPR,0.28,11.97,7.86,20.77,20606.0,28018.0,262162.0,1644.00,-0.77,71.0,X-MC,7.15,64.0,1.36,1.64,26.02,X40N,NTT,BREWERIES
69,SIS,1.44,0.31,20.89,21.26,23265.0,339.0,111371.0,528.00,2659.59,57.0,H-SC,22.86,168.0,0.01,0.70,65.59,OX40N,NTT,MISC
52,M&M,1.44,9.10,8.91,18.82,23396.0,21899.0,262580.0,3762.88,-5.04,67.0,X-LC,5.74,25.0,0.94,1.64,19.11,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
62,RELAXO,3.71,-44.10,172.47,52.31,139944.0,-64019.0,81141.0,1176.00,-40.47,63.0,X-SC,11.17,92.0,-0.46,0.51,81.42,X40N,NTT,FOOTWEAR
75,TCS,3.07,-28.20,72.98,24.20,242753.0,-130644.0,332629.0,4230.71,-39.36,63.0,X-LC,15.71,2.0,-0.54,2.08,24.04,X40,ATH,IT
43,INDIGOPNTS,2.79,-20.35,25.58,0.02,35564.0,-35530.0,139029.0,1408.00,112.05,62.0,M-SC,4.65,222.0,-1.00,0.87,57.74,OX40N,NTT,PAINTS
25,FINCABLES,2.67,30.47,59.35,107.91,114331.0,44994.0,192638.0,1641.55,17.20,52.0,M-SC,17.62,220.0,0.39,1.20,44.93,OX40N,ATH,CABLES
74,TATAELXSI,2.13,-45.32,141.45,32.03,101968.0,-59747.0,72088.0,9161.00,-31.62,57.0,H-SC,20.40,158.0,-0.59,0.45,12.00,OX40N,NTT,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
18,COFFEEDAY,-5.04,-45.21,146.91,35.27,91390.0,-51341.0,62208.0,80.00,-57.75,53.0,L-SC,5.65,266.0,-0.56,0.39,53.41,XR,NTT,HOTELS
51,LAOPALA,-2.36,-42.60,142.32,39.09,107099.0,-55853.0,75252.0,464.00,64.71,59.0,H-SC,6.25,154.0,-0.52,0.47,16.76,AR,NTT,CERAMICS
39,ICICIGI,-2.20,-12.76,36.27,18.89,63321.0,-25527.0,174582.0,2244.41,-26.70,44.0,X-MC,9.39,66.0,-0.40,1.09,4.01,X40,ATH,INSURANCE
40,ICICIPRULI,-2.07,-16.29,55.63,30.28,91738.0,-32098.0,164907.0,787.27,-38.80,50.0,X-MC,13.70,78.0,-0.35,1.03,9.87,X40,ATH,INSURANCE
3,ALKYLAMINE,-1.90,-18.95,137.56,92.54,112564.0,-19134.0,81829.0,4520.85,-13.24,58.0,H-SC,13.37,142.0,-0.17,0.51,55.39,SR,ATH,CHEMICALS

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,-0.46,-0.26,45.95,45.57,90348.0,-510.0,196622.0,844.0,4278.38,77.0,M-SC,8.39,248.0,-0.01,1.23,51.31,XY24,NTT,AUTO
61,RECLTD,1.41,-0.76,21.66,20.74,43673.0,-1540.0,201630.0,446.0,9.37,57.0,M-MC,3.42,191.0,-0.04,1.26,21.54,XY25,NTT,FINANCE
69,SIS,1.44,0.31,20.89,21.26,23265.0,339.0,111371.0,528.0,2659.59,57.0,H-SC,22.86,168.0,0.01,0.70,65.59,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.67,30.47,59.35,107.91,114331.0,44994.0,192638.0,1641.55,17.20,52.0,M-SC,17.62,220.0,0.39,1.20,44.93,OX40N,ATH,CABLES
69,SIS,1.44,0.31,20.89,21.26,23265.0,339.0,111371.0,528.00,2659.59,57.0,H-SC,22.86,168.0,0.01,0.70,65.59,OX40N,NTT,MISC
79,TTKPRESTIG,0.76,-17.72,21.64,0.09,17945.0,-17854.0,82923.0,770.00,92.53,50.0,M-SC,13.87,250.0,-0.99,0.52,49.25,OX40N,NTT,DURABLES
16,CERA,-0.70,-17.89,50.88,23.89,73491.0,-31463.0,144440.0,9475.00,-20.76,55.0,H-SC,12.94,153.0,-0.43,0.90,40.41,OX40N,NTT,CERAMICS
43,INDIGOPNTS,2.79,-20.35,25.58,0.02,35564.0,-35530.0,139029.0,1408.00,112.05,62.0,M-SC,4.65,222.0,-1.00,0.87,57.74,OX40N,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.67,30.47,59.35,107.91,114331.0,44994.0,192638.0,1641.55,17.20,52.0,M-SC,17.62,220.0,0.39,1.20,44.93,OX40N,ATH,CABLES
55,MEDANTA,0.88,24.64,1.99,27.12,4378.0,43490.0,220007.0,1486.00,20.80,67.0,X-SC,15.38,87.0,9.93,1.38,51.60,XY24,NTT,HEALTHCARE
58,QUESS,-1.23,26.49,37.48,73.90,50628.0,28286.0,135079.0,424.00,-32.23,57.0,X-SC,39.43,80.0,0.56,0.84,85.92,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,1.44,0.31,20.89,21.26,23265.0,339.0,111371.0,528.00,2659.59,57.0,H-SC,22.86,168.0,0.01,0.70,65.59,OX40N,NTT,MISC
70,STARHEALTH,0.10,11.12,32.52,47.26,101590.0,31269.0,312392.0,761.00,75.48,45.0,H-SC,17.65,173.0,0.31,1.95,35.07,XY24,NTT,INSURANCE
25,FINCABLES,2.67,30.47,59.35,107.91,114331.0,44994.0,192638.0,1641.55,17.20,52.0,M-SC,17.62,220.0,0.39,1.20,44.93,OX40N,ATH,CABLES
87,ZYDUSLIFE,-0.26,16.53,16.28,35.51,39760.0,34653.0,244227.0,1285.01,1.35,45.0,H-MC,15.55,120.0,0.87,1.53,28.53,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,-0.26,16.53,16.28,35.51,39760.0,34653.0,244227.0,1285.01,1.35,45.0,H-MC,15.55,120.0,0.87,1.53,28.53,AR,ATH,PHARMA
25,FINCABLES,2.67,30.47,59.35,107.91,114331.0,44994.0,192638.0,1641.55,17.20,52.0,M-SC,17.62,220.0,0.39,1.20,44.93,OX40N,ATH,CABLES
69,SIS,1.44,0.31,20.89,21.26,23265.0,339.0,111371.0,528.00,2659.59,57.0,H-SC,22.86,168.0,0.01,0.70,65.59,OX40N,NTT,MISC
3,ALKYLAMINE,-1.90,-18.95,137.56,92.54,112564.0,-19134.0,81829.0,4520.85,-13.24,58.0,H-SC,13.37,142.0,-0.17,0.51,55.39,SR,ATH,CHEMICALS
73,TANLA,1.58,-30.10,210.80,117.25,398962.0,-81500.0,189261.0,1922.32,-29.36,62.0,H-SC,13.83,147.0,-0.20,1.18,65.70,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,0.06,-10.26,46.04,31.05,121104.0,-30080.0,263040.0,1073.00,-25.47,36.0,X-LC,10.55,26.0,-0.25,1.64,2.10,X40,BTT,BANKS
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
83,VBL,0.42,-9.65,50.14,35.66,159391.0,-33953.0,317891.0,669.42,-20.58,40.0,X-LC,7.72,13.0,-0.21,1.99,17.04,X40N,ATH,FMCG
35,HDFCLIFE,-0.28,-7.22,49.98,39.15,116268.0,-18107.0,232630.0,811.41,-30.91,40.0,X-LC,15.96,31.0,-0.16,1.45,0.94,X40,ATH,INSURANCE
20,DABUR,0.39,-19.27,78.01,43.70,156220.0,-47812.0,200256.0,735.00,-26.67,41.0,X-MC,9.11,70.0,-0.31,1.25,1.90,XY24,BTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,0.22,-22.81,81.20,39.86,165063.0,-60085.0,203280.0,3683.41,-6.52,46.0,X-MC,1.62,62.0,-0.36,1.27,14.99,XY25,ATH,FMCG
11,BERGEPAINT,-1.14,-0.67,26.16,25.32,66976.0,-1724.0,256025.0,680.00,-6.11,65.0,X-MC,1.91,68.0,-0.03,1.60,34.26,XY24,NTT,PAINTS
8,BAJAJHLDNG,-0.97,2.29,25.38,28.24,66459.0,5850.0,261855.0,14274.15,-6.07,65.0,X-LC,2.59,28.0,0.09,1.64,31.79,X40,ATH,FINANCE
23,DMART,0.16,-4.02,36.93,31.42,110510.0,-12548.0,299242.0,5391.45,-20.23,44.0,X-LC,3.21,14.0,-0.11,1.87,7.98,X40N,ATH,FMCG
26,GILLETTE,0.25,-8.86,42.34,29.72,97971.0,-22506.0,231390.0,10978.86,-29.98,47.0,X-SC,3.42,83.0,-0.23,1.45,6.33,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
35,HDFCLIFE,-0.28,-7.22,49.98,39.15,116268.0,-18107.0,232630.0,811.41,-30.91,40.0,X-LC,15.96,31.0,-0.16,1.45,0.94,X40,ATH,INSURANCE
20,DABUR,0.39,-19.27,78.01,43.70,156220.0,-47812.0,200256.0,735.00,-26.67,41.0,X-MC,9.11,70.0,-0.31,1.25,1.90,XY24,BTT,FMCG
34,HDFCBANK,0.06,-10.26,46.04,31.05,121104.0,-30080.0,263040.0,1073.00,-25.47,36.0,X-LC,10.55,26.0,-0.25,1.64,2.10,X40,BTT,BANKS
47,ITC,-0.19,-21.28,58.40,24.70,182642.0,-84534.0,312744.0,452.00,-58.75,51.0,X-LC,11.31,1.0,-0.46,1.95,3.56,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-0.69,-53.23,189.08,35.20,113786.0,-68491.0,60179.0,2096.00,-21.16,64.0,X-SC,14.79,91.0,-0.60,0.38,20.90,X40,NTT,FOOTWEAR
62,RELAXO,3.71,-44.10,172.47,52.31,139944.0,-64019.0,81141.0,1176.00,-40.47,63.0,X-SC,11.17,92.0,-0.46,0.51,81.42,X40N,NTT,FOOTWEAR
58,QUESS,-1.23,26.49,37.48,73.90,50628.0,28286.0,135079.0,424.00,-32.23,57.0,X-SC,39.43,80.0,0.56,0.84,85.92,XY24,NTT,MISC
57,PGHH,0.18,-36.31,107.27,32.01,145879.0,-77528.0,135992.0,17616.87,-56.92,36.0,X-MC,19.18,57.0,-0.53,0.85,0.27,X40,ATH,FMCG
40,ICICIPRULI,-2.07,-16.29,55.63,30.28,91738.0,-32098.0,164907.0,787.27,-38.80,50.0,X-MC,13.70,78.0,-0.35,1.03,9.87,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.19,-21.28,58.40,24.70,182642.0,-84534.0,312744.0,452.00,-58.75,51.0,X-LC,11.31,1.0,-0.46,1.95,3.56,X40,NTT,FMCG
75,TCS,3.07,-28.20,72.98,24.20,242753.0,-130644.0,332629.0,4230.71,-39.36,63.0,X-LC,15.71,2.0,-0.54,2.08,24.04,X40,ATH,IT
45,INFY,1.34,-15.96,67.03,40.38,212084.0,-60069.0,316401.0,1972.00,-36.87,63.0,X-LC,16.35,3.0,-0.28,1.98,19.82,X40,NTT,IT
77,TMPV,0.22,-17.66,73.36,42.75,251360.0,-73468.0,342639.0,600.00,-83.62,54.0,X-LC,5.40,4.0,-0.29,2.14,17.82,XY24,NTT,AUTO
33,HCLTECH,2.10,-8.83,35.97,23.97,101494.0,-27324.0,282162.0,1853.42,-6.95,69.0,X-LC,13.57,8.0,-0.27,1.76,33.15,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.41,-25.29,77.87,32.89,44919.0,-19522.0,57684.0,1800.00,-371.71,53.0,L-MC,13.90,258.0,-0.43,0.36,42.21,XR,NTT,BANKS
3,ALKYLAMINE,-1.90,-18.95,137.56,92.54,112564.0,-19134.0,81829.0,4520.85,-13.24,58.0,H-SC,13.37,142.0,-0.17,0.51,55.39,SR,ATH,CHEMICALS
62,RELAXO,3.71,-44.10,172.47,52.31,139944.0,-64019.0,81141.0,1176.00,-40.47,63.0,X-SC,11.17,92.0,-0.46,0.51,81.42,X40N,NTT,FOOTWEAR
79,TTKPRESTIG,0.76,-17.72,21.64,0.09,17945.0,-17854.0,82923.0,770.00,92.53,50.0,M-SC,13.87,250.0,-0.99,0.52,49.25,OX40N,NTT,DURABLES
12,BOSCH-HCIL,2.06,-26.43,35.91,-0.01,33766.0,-33775.0,94030.0,2282.00,19139.13,85.0,M-SC,3.85,231.0,-1.00,0.59,60.05,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,2.06,-26.43,35.91,-0.01,33766.0,-33775.0,94030.0,2282.00,19139.13,85.0,M-SC,3.85,231.0,-1.00,0.59,60.05,OX40N,BTT,AC
30,HAPPSTMNDS,0.37,-49.11,259.75,83.08,169419.0,-62941.0,65224.0,1466.54,-39.56,68.0,H-SC,10.38,152.0,-0.37,0.41,22.17,AR,ATH,IT
33,HCLTECH,2.10,-8.83,35.97,23.97,101494.0,-27324.0,282162.0,1853.42,-6.95,69.0,X-LC,13.57,8.0,-0.27,1.76,33.15,X40,ATH,IT
75,TCS,3.07,-28.20,72.98,24.20,242753.0,-130644.0,332629.0,4230.71,-39.36,63.0,X-LC,15.71,2.0,-0.54,2.08,24.04,X40,ATH,IT
5,ATULAUTO,-0.46,-0.26,45.95,45.57,90348.0,-510.0,196622.0,844.00,4278.38,77.0,M-SC,8.39,248.0,-0.01,1.23,51.31,XY24,NTT,AUTO

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.69
1     25       44.60
2     50       76.85

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.36
LC    37.71
MC    22.94
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.40
XY24     25.10
X40N     18.48
XR        9.06
XY25      7.25
OX40N     6.87
AR        6.00
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.65
H-SC    19.21
X-MC    18.73
X-SC     9.94
M-SC     9.68
H-MC     2.59
M-MC     1.26
H-LC     1.24
M-LC     0.82
L-SC     0.53
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.55        -19.92   63.11
IT                  11.22        -32.88   98.84
FINANCE              9.36        -14.11   62.07
AUTO                 8.37         -0.87   37.00
MISC                 6.86        -22.11   74.49
BANKS                6.04        -10.33   57.91
PHARMA               5.58          6.99   19.39
INSURANCE            5.52         -5.03   42.16
PAINTS               5.41        -13.87   33.29
ELECTRICAL           4.11         -7.52   45.17
HEALTHCARE           2.08         -7.83   35.97
AC                   1.79        -11.74   42.03
APPARELS             1.76          4.51   27.56
REFINERIES           1.68        -10.87   48.11
FOOTWEAR             1.67        -65.49  131.85
BREWERIES            1.64         10.69    7.86
DURABLES             1.53        -58.02   96.47
TRAVEL               1.46        -91.55  187.46
CERAMICS             1.37        -39.74   82.20
ENGINEERING          1.22        -24.01   80.74
CABLES               1.20         23.36   59.35
CHEMICALS            1.10        -50.00  171.75
CEMENT               1.03        -63.15  185.21
JEWELLERY            1.00        -99.68  169.06
ENTERTAINMENT        0.68        -77.71  183.70
TEXTILES             0.39        -47.63   89.72
HOTELS               0.39        -82.53  146.91

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3386470.0     20
X40       2002152.0     18
XR        1345645.0     13
X40N      1125478.0     12
AR        1072286.0      8
OX40N      694265.0     10
XY25       539891.0      5
SR         280909.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3277297.0     23
X-LC        2354435.0     20
X-MC        1457452.0     14
M-SC        1368213.0     14
X-SC        1213908.0      9
H-MC         284621.0      2
L-SC         206635.0      2
M-LC         161190.0      1
L-MC          44919.0      1
M-MC          43673.0      1
H-LC          34753.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1150255.0      9
H-SC       XY24       979850.0      5
           AR         921503.0      5
M-SC       XY24       816144.0      6
H-SC       XR         802713.0      7
X-SC       XY24       708084.0      4
X-MC       X40        640140.0      7
X-LC       X40N       488795.0      6
           XY24       414335.0      2
X-MC       X40N       342616.0      3
X-SC       X40N       294067.0      3
H-SC       OX40N      292322.0      4
M-SC       OX40N      286698.0      5
H-SC       SR         280909.0      2
X-MC       XY25       251500.0      2
H-MC       XY24       244861.0      1
X-LC       XY25       244718.0      2
X-MC       XY24       223196.0      2
X-SC       X40        211757.0      2
M-SC       XR         189101.0      2
M-LC       XR         161190.0      1
L-SC       OX40N      115245.0      1
           XR          91390.0      1
M-SC       AR          76270.0      1
X-LC       XR          56332.0      1
L-MC       XR          44919.0      1
M-MC       XY25        43673.0      1
H-MC       AR          39760.0      1
H-LC       AR          34753.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds