<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-08 12:21:58
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 25.84 K (0.17%)
Current PnL: -30.77 L (-16.87%)
CY Booked + Current PnL: -28.69 L (-15.73%)
-------------------
Total profit:  2.20 L
Total loss:  -32.96 L
-------------------
Total Booked + Current PnL: 14.18 L (10.17%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.36%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.6%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.38%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.10,6.22,14.45,21.57,15038.0,6090.0,104070.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.48,XR,ATH,FINANCE
59,PIDILITIND,2.01,4.85,12.89,18.37,19071.0,6840.0,147950.0,1670.26,-26.53,68.0,X-LC,5.36,5.0,0.36,0.97,16.17,X40,ATH,CHEMICALS
53,M&M,-0.45,8.88,13.32,23.38,20112.0,12312.0,150993.0,3802.40,-7.83,62.0,X-LC,7.57,25.0,0.61,0.99,14.48,X40N,ATH,AUTO
51,KOTAKBANK,-0.15,1.23,19.64,21.11,27530.0,1702.0,140174.0,453.24,-13.31,51.0,X-LC,7.45,12.0,0.06,0.92,7.20,X40,ATH,BANKS
83,TTKPRESTIG,-1.44,-31.63,46.39,0.09,31965.0,-31871.0,68906.0,770.00,59.87,58.0,M-SC,17.26,250.0,-1.00,0.45,22.70,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,8.21,-0.55,23.71,23.03,42226.0,-979.0,178092.0,216.00,92.98,83.0,H-SC,9.60,166.0,-0.02,1.17,51.88,XR,NTT,BANKS
11,BERGEPAINT,5.38,-5.18,32.17,25.32,78620.0,-13361.0,244388.0,680.00,-10.37,75.0,X-MC,12.93,68.0,-0.17,1.60,27.19,XY24,NTT,PAINTS
25,FINCABLES,4.80,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.70,1.40,60.40,OX40N,ATH,CABLES
62,RAJOOENG,4.49,-39.33,130.10,39.61,80909.0,-40310.0,62190.0,143.10,-58.91,51.0,H-SC,22.76,136.0,-0.50,0.41,33.23,AR,ATH,MISC
20,DABUR,4.05,-4.39,50.29,43.70,119282.0,-10879.0,237189.0,735.00,-13.19,69.0,X-MC,9.44,70.0,-0.09,1.56,19.15,XY24,BTT,FMCG

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-3.04,-57.49,295.55,68.16,167193.0,-76496.0,56570.0,2215.45,-65.51,64.0,H-SC,27.12,141.0,-0.46,0.37,34.77,SR,ATH,IT
88,VOLTAS,-2.53,4.00,39.61,45.20,78986.0,7668.0,199410.0,1856.00,19.11,40.0,X-MC,2.44,79.0,0.10,1.31,9.30,XY25,NTT,AC
89,WHIRLPOOL,-2.24,-23.33,137.26,81.92,120818.0,-26777.0,88021.0,2270.00,-55.05,58.0,M-SC,17.32,210.0,-0.22,0.58,23.64,XR,NTT,DURABLES
6,AWL,-2.22,-28.63,134.03,67.02,340816.0,-102026.0,254283.0,485.00,-61.53,62.0,X-SC,20.06,81.0,-0.30,1.67,20.28,XY24,NTT,FMCG
66,REPCOHOME,-2.19,-12.64,117.28,89.82,293540.0,-36215.0,250290.0,880.00,-56.04,53.0,H-SC,5.86,161.0,-0.12,1.64,20.32,XY24,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.06,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,55.0,M-MC,19.76,193.0,0.00,0.66,43.34,AR,ATH,AUTO
74,STARHEALTH,0.49,0.63,46.35,47.26,131115.0,1757.0,282880.0,761.00,58.79,63.0,H-SC,9.58,173.0,0.01,1.86,46.50,XY24,NTT,INSURANCE
75,SURYODAY,8.21,-0.55,23.71,23.03,42226.0,-979.0,178092.0,216.00,92.98,83.0,H-SC,9.60,166.0,-0.02,1.17,51.88,XR,NTT,BANKS

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.80,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.70,1.40,60.40,OX40N,ATH,CABLES
72,SIS,0.39,-8.20,32.10,21.26,32718.0,-9108.0,101924.0,528.00,2425.39,76.0,H-SC,10.74,168.0,-0.28,0.67,51.55,OX40N,NTT,MISC
16,CERA,2.08,-27.17,70.11,23.89,89818.0,-47793.0,128110.0,9475.00,-29.83,69.0,H-SC,11.16,153.0,-0.53,0.84,23.11,OX40N,NTT,CERAMICS
50,KANSAINER,1.58,-28.28,58.22,13.47,112598.0,-76266.0,193401.0,340.00,-38.33,68.0,H-SC,16.04,162.0,-0.68,1.27,35.09,XY24,NTT,PAINTS
83,TTKPRESTIG,-1.44,-31.63,46.39,0.09,31965.0,-31871.0,68906.0,770.00,59.87,58.0,M-SC,17.26,250.0,-1.00,0.45,22.70,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.8,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.7,1.4,60.4,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.49,0.63,46.35,47.26,131115.0,1757.0,282880.0,761.00,58.79,63.0,H-SC,9.58,173.0,0.01,1.86,46.50,XY24,NTT,INSURANCE
25,FINCABLES,4.80,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.70,1.40,60.40,OX40N,ATH,CABLES
68,SATIN,1.73,14.88,32.17,51.83,102105.0,41108.0,317392.0,274.00,2.50,80.0,H-SC,16.75,159.0,0.40,2.08,54.62,XY24,NTT,FINANCE
55,MASFIN,-0.10,6.22,14.45,21.57,15038.0,6090.0,104070.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.48,XR,ATH,FINANCE
73,SONACOMS,0.06,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,55.0,M-MC,19.76,193.0,0.00,0.66,43.34,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,4.80,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.70,1.40,60.40,OX40N,ATH,CABLES
55,MASFIN,-0.10,6.22,14.45,21.57,15038.0,6090.0,104070.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.48,XR,ATH,FINANCE
73,SONACOMS,0.06,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,55.0,M-MC,19.76,193.0,0.00,0.66,43.34,AR,ATH,AUTO
75,SURYODAY,8.21,-0.55,23.71,23.03,42226.0,-979.0,178092.0,216.00,92.98,83.0,H-SC,9.60,166.0,-0.02,1.17,51.88,XR,NTT,BANKS
91,ZYDUSLIFE,-0.31,-1.15,37.21,35.63,77082.0,-2420.0,207154.0,1286.17,-13.96,58.0,H-MC,3.56,120.0,-0.03,1.36,8.92,AR,ATH,PHARMA

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.81,-22.58,56.94,21.51,106649.0,-54623.0,187301.0,1872.35,-18.53,31.0,X-LC,12.35,8.0,-0.51,1.23,0.81,X40,ATH,IT
45,INFY,0.58,-20.39,68.63,34.24,170945.0,-63806.0,249082.0,1972.00,-37.23,36.0,X-LC,15.86,3.0,-0.37,1.63,1.50,X40,NTT,IT
79,TCS,-1.02,-30.22,81.39,26.57,263111.0,-140001.0,323272.0,4311.58,-41.00,37.0,X-LC,14.26,2.0,-0.53,2.12,0.89,X40,ATH,IT
88,VOLTAS,-2.53,4.00,39.61,45.20,78986.0,7668.0,199410.0,1856.00,19.11,40.0,X-MC,2.44,79.0,0.10,1.31,9.30,XY25,NTT,AC
28,GODREJCP,0.58,-6.69,41.60,32.12,57685.0,-9948.0,138666.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.87,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-2.53,4.00,39.61,45.20,78986.0,7668.0,199410.0,1856.00,19.11,40.0,X-MC,2.44,79.0,0.10,1.31,9.30,XY25,NTT,AC
84,UNITDSPR,0.19,-5.81,28.22,20.77,62236.0,-13606.0,220538.0,1644.00,-16.49,43.0,X-MC,2.51,64.0,-0.22,1.45,5.20,X40N,NTT,BREWERIES
65,RELIANCE,-0.68,-8.44,36.85,25.30,67806.0,-16957.0,184006.0,1952.00,-10.80,57.0,X-LC,3.40,21.0,-0.25,1.21,9.34,XY25,BTT,REFINERIES
39,ICICIGI,-0.88,-2.85,22.84,19.34,44402.0,-5705.0,194404.0,2252.93,-18.36,57.0,X-MC,4.59,66.0,-0.13,1.28,8.58,X40,ATH,INSURANCE
19,COLPAL,0.83,-17.04,70.56,41.51,154174.0,-44865.0,218500.0,3726.84,0.43,64.0,X-MC,5.12,62.0,-0.29,1.43,22.16,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,0.81,-22.58,56.94,21.51,106649.0,-54623.0,187301.0,1872.35,-18.53,31.0,X-LC,12.35,8.0,-0.51,1.23,0.81,X40,ATH,IT
79,TCS,-1.02,-30.22,81.39,26.57,263111.0,-140001.0,323272.0,4311.58,-41.00,37.0,X-LC,14.26,2.0,-0.53,2.12,0.89,X40,ATH,IT
45,INFY,0.58,-20.39,68.63,34.24,170945.0,-63806.0,249082.0,1972.00,-37.23,36.0,X-LC,15.86,3.0,-0.37,1.63,1.50,X40,NTT,IT
84,UNITDSPR,0.19,-5.81,28.22,20.77,62236.0,-13606.0,220538.0,1644.00,-16.49,43.0,X-MC,2.51,64.0,-0.22,1.45,5.20,X40N,NTT,BREWERIES
28,GODREJCP,0.58,-6.69,41.60,32.12,57685.0,-9948.0,138666.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.87,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.79,-60.16,282.25,52.31,163248.0,-87322.0,57838.0,1176.00,-57.60,56.0,X-SC,24.40,92.0,-0.53,0.38,29.32,X40N,NTT,FOOTWEAR
10,BATAINDIA,-0.91,-53.46,190.49,35.20,114083.0,-68781.0,59889.0,2096.00,-21.44,49.0,X-SC,26.14,91.0,-0.60,0.39,18.77,X40,NTT,FOOTWEAR
60,QUESS,0.25,-7.95,88.92,73.90,87408.0,-8493.0,98300.0,424.00,-50.41,74.0,X-SC,13.56,80.0,-0.10,0.65,34.00,XY24,NTT,MISC
28,GODREJCP,0.58,-6.69,41.60,32.12,57685.0,-9948.0,138666.0,1476.34,-1.81,42.0,X-LC,6.34,32.0,-0.17,0.91,5.87,X40N,ATH,FMCG
51,KOTAKBANK,-0.15,1.23,19.64,21.11,27530.0,1702.0,140174.0,453.24,-13.31,51.0,X-LC,7.45,12.0,0.06,0.92,7.20,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.10,-19.11,47.18,19.06,129821.0,-65004.0,275162.0,452.00,-55.52,50.0,X-LC,15.58,1.0,-0.50,1.81,6.74,X40,NTT,FMCG
79,TCS,-1.02,-30.22,81.39,26.57,263111.0,-140001.0,323272.0,4311.58,-41.00,37.0,X-LC,14.26,2.0,-0.53,2.12,0.89,X40,ATH,IT
45,INFY,0.58,-20.39,68.63,34.24,170945.0,-63806.0,249082.0,1972.00,-37.23,36.0,X-LC,15.86,3.0,-0.37,1.63,1.50,X40,NTT,IT
81,TMPV,-1.02,-19.05,68.73,36.58,197967.0,-67805.0,288036.0,600.00,-83.62,56.0,X-LC,5.17,4.0,-0.34,1.89,20.05,XY24,NTT,AUTO
59,PIDILITIND,2.01,4.85,12.89,18.37,19071.0,6840.0,147950.0,1670.26,-26.53,68.0,X-LC,5.36,5.0,0.36,0.97,16.17,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.02,-30.08,90.05,32.89,48613.0,-23222.0,53985.0,1800.00,-354.20,68.0,L-MC,5.84,258.0,-0.48,0.35,32.88,XR,NTT,BANKS
12,BOSCH-HCIL,-0.81,-37.14,59.07,-0.01,47456.0,-47467.0,80338.0,2282.00,16334.78,60.0,M-SC,4.78,231.0,-1.00,0.53,36.75,OX40N,BTT,AC
73,SONACOMS,0.06,0.16,38.86,39.09,39375.0,166.0,101325.0,804.02,-20.60,55.0,M-MC,19.76,193.0,0.00,0.66,43.34,AR,ATH,AUTO
72,SIS,0.39,-8.20,32.10,21.26,32718.0,-9108.0,101924.0,528.00,2425.39,76.0,H-SC,10.74,168.0,-0.28,0.67,51.55,OX40N,NTT,MISC
55,MASFIN,-0.10,6.22,14.45,21.57,15038.0,6090.0,104070.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.40,0.68,34.48,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.39,-8.20,32.10,21.26,32718.0,-9108.0,101924.0,528.00,2425.39,76.0,H-SC,10.74,168.0,-0.28,0.67,51.55,OX40N,NTT,MISC
25,FINCABLES,4.80,44.41,43.98,107.91,93769.0,65564.0,213208.0,1641.55,29.88,82.0,M-SC,18.57,220.0,0.70,1.40,60.40,OX40N,ATH,CABLES
68,SATIN,1.73,14.88,32.17,51.83,102105.0,41108.0,317392.0,274.00,2.50,80.0,H-SC,16.75,159.0,0.40,2.08,54.62,XY24,NTT,FINANCE
75,SURYODAY,8.21,-0.55,23.71,23.03,42226.0,-979.0,178092.0,216.00,92.98,83.0,H-SC,9.60,166.0,-0.02,1.17,51.88,XR,NTT,BANKS
77,TANLA,-1.90,-36.36,241.38,117.25,415919.0,-98452.0,172309.0,1922.32,-35.93,65.0,H-SC,16.91,147.0,-0.24,1.13,50.86,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.00
1     25       42.35
2     50       72.62

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.98
LC    31.25
MC    25.76
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.45
X40      25.37
X40N     16.68
XR        9.18
OX40N     7.00
XY25      6.75
AR        6.70
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.10
H-SC    22.48
X-MC    20.88
M-SC    10.18
X-SC     9.78
H-MC     2.57
M-MC     1.96
H-LC     1.25
M-LC     0.90
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.38        -12.96   52.81
FINANCE             10.82        -11.73   60.33
IT                  10.33        -43.02  115.03
MISC                 7.18        -22.64   75.91
AUTO                 6.64         -8.12   48.65
BANKS                5.69         -4.78   53.23
PAINTS               5.38        -20.17   41.04
INSURANCE            5.36         -1.56   36.12
PHARMA               4.81         -0.96   33.41
ELECTRICAL           3.99        -16.33   57.74
CHEMICALS            2.11        -26.15  101.33
HEALTHCARE           1.95        -20.25   51.63
AC                   1.84        -14.23   45.20
TRAVEL               1.72        -70.50  155.88
DURABLES             1.71        -48.00   84.00
FOOTWEAR             1.70        -70.54  138.92
APPARELS             1.69         -4.07   39.57
BREWERIES            1.45         -6.17   28.22
REALTY               1.40         -3.61   20.63
CABLES               1.40         30.75   43.98
CERAMICS             1.31        -53.29   99.87
ENGINEERING          1.26        -26.41   84.22
REFINERIES           1.21         -9.22   36.85
CEMENT               1.10        -59.55  178.92
JEWELLERY            1.07        -95.65  163.62
ENTERTAINMENT        0.73        -74.33  178.30
TEXTILES             0.43        -40.15   80.11
HOTELS               0.33       -125.47  204.99

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3415050.0     21
X40       1838882.0     19
XR        1281734.0     13
X40N      1183567.0     13
AR        1161216.0      9
OX40N      723449.0     10
XY25       410452.0      5
SR         288497.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3360531.0     24
X-LC        1863132.0     21
X-MC        1552795.0     15
M-SC        1365429.0     14
X-SC        1314671.0      9
H-MC         306284.0      2
L-SC         207964.0      2
M-LC         154622.0      1
M-MC          85874.0      2
L-MC          48613.0      1
H-LC          42932.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1061456.0      6
X-LC       X40        999520.0     10
H-SC       AR         926163.0      5
M-SC       XY24       819517.0      6
X-SC       XY24       772862.0      4
H-SC       XR         762390.0      7
X-MC       X40        637616.0      7
           X40N       484117.0      4
X-LC       X40N       359387.0      6
X-SC       X40N       340063.0      3
X-LC       XY24       334111.0      2
H-SC       OX40N      322025.0      4
M-SC       OX40N      296697.0      5
H-SC       SR         288497.0      2
X-MC       XY25       233160.0      2
H-MC       XY24       229202.0      1
X-SC       X40        201746.0      2
X-MC       XY24       197902.0      2
M-SC       XR         173551.0      2
M-LC       XR         154622.0      1
X-LC       XY25       130793.0      2
L-SC       OX40N      104727.0      1
           XR         103237.0      1
H-MC       AR          77082.0      1
M-SC       AR          75664.0      1
L-MC       XR          48613.0      1
M-MC       XY25        46499.0      1
H-LC       AR          42932.0      1
M-MC       AR          39375.0      1
X-LC       XR          39321.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds