<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-26 15:48:25
-------------------
qualified stocks: 86
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  5.73 L
Current:  1.57 C
-------------------
Today PnL: -20.31 K (-0.13%)
Current PnL: -35.71 L (-18.9%)
CY Booked + Current PnL: -30.47 L (-16.13%)
-------------------
Total profit:  3.75 L
Total loss:  -39.45 L
-------------------
Total Booked + Current PnL: 12.40 L (8.49%)
Total Booked PnL: 48.10 L (32.94%)
Curr Year Booked PnL: 5.24 L (3.33%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.10 C (69.64%)
===================
Deployed:  1.46 C
Current:  1.57 C
CAGR/XIRR %: 3.37%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,UNITDSPR,-0.74,13.02,6.86,20.77,18153.0,30478.0,264622.0,1644.00,-3.65,60.0,X-MC,12.35,64.0,1.68,1.74,27.20,X40N,NTT,BREWERIES
76,TTKPRESTIG,2.45,-20.69,26.20,0.09,20942.0,-20847.0,79930.0,770.00,-3.55,51.0,M-SC,8.42,250.0,-1.00,0.53,43.86,OX40N,NTT,DURABLES
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
66,SIS,1.94,-3.29,25.39,21.26,27264.0,-3652.0,107380.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.13,0.71,59.66,OX40N,NTT,MISC
43,INDIGOPNTS,4.42,-15.74,18.71,0.02,27518.0,-27483.0,147076.0,1408.00,-19.63,66.0,M-SC,9.10,222.0,-1.00,0.97,66.87,OX40N,NTT,PAINTS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
68,SURYODAY,4.91,-9.76,36.34,23.03,58725.0,-17472.0,161599.0,216.00,-25.86,46.0,H-SC,14.48,166.0,-0.30,1.07,37.17,XR,NTT,BANKS
43,INDIGOPNTS,4.42,-15.74,18.71,0.02,27518.0,-27483.0,147076.0,1408.00,-19.63,66.0,M-SC,9.10,222.0,-1.00,0.97,66.87,OX40N,NTT,PAINTS
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
63,ROUTE,3.12,-60.27,318.52,66.28,168395.0,-80198.0,52868.0,2190.73,NaN,51.0,NaN,6.92,141.0,-0.48,0.35,27.37,SR,ATH,IT
12,BOSCH-HCIL,2.45,-25.27,33.79,-0.01,32274.0,-32291.0,95514.0,2282.00,745.07,64.0,M-SC,14.50,231.0,-1.00,0.63,62.58,OX40N,BTT,AC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
70,TANLA,-5.40,-40.55,265.43,117.25,427265.0,-109790.0,160971.0,1922.32,NaN,32.0,NaN,13.77,147.0,-0.26,1.06,40.93,AR,ATH,IT
81,VBL,-3.82,-14.64,58.91,35.66,176937.0,-51493.0,300351.0,669.42,-30.15,36.0,X-LC,7.01,13.0,-0.29,1.98,10.58,X40N,ATH,FMCG
23,DMART,-2.12,-6.72,40.88,31.42,118897.0,-20946.0,290844.0,5391.45,-21.79,36.0,X-LC,2.10,14.0,-0.18,1.92,4.95,X40N,ATH,FMCG
45,INFY,-2.10,-20.27,76.07,40.38,228332.0,-76310.0,300160.0,1972.00,-41.25,47.0,X-LC,15.35,3.0,-0.33,1.98,13.67,X40,NTT,IT
82,VOLTAS,-2.09,-4.79,52.51,45.20,95857.0,-9192.0,182550.0,1856.00,31.07,36.0,X-MC,5.89,79.0,-0.10,1.20,0.05,XY25,NTT,AC

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.10,62.92,27.61,107.91,66415.0,92903.0,240547.0,1641.55,18.78,65.0,M-SC,26.13,220.0,1.40,1.59,80.97,OX40N,ATH,CABLES
66,SIS,1.94,-3.29,25.39,21.26,27264.0,-3652.0,107380.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.13,0.71,59.66,OX40N,NTT,MISC
43,INDIGOPNTS,4.42,-15.74,18.71,0.02,27518.0,-27483.0,147076.0,1408.00,-19.63,66.0,M-SC,9.10,222.0,-1.00,0.97,66.87,OX40N,NTT,PAINTS
76,TTKPRESTIG,2.45,-20.69,26.20,0.09,20942.0,-20847.0,79930.0,770.00,-3.55,51.0,M-SC,8.42,250.0,-1.00,0.53,43.86,OX40N,NTT,DURABLES
16,CERA,-1.75,-25.25,65.73,23.89,86429.0,-44412.0,131491.0,9475.00,NaN,37.0,NaN,12.70,153.0,-0.51,0.87,27.82,OX40N,NTT,CERAMICS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.10,62.92,27.61,107.91,66415.0,92903.0,240547.0,1641.55,18.78,65.0,M-SC,26.13,220.0,1.40,1.59,80.97,OX40N,ATH,CABLES
85,ZYDUSLIFE,2.27,21.27,11.74,35.51,29837.0,44576.0,254150.0,1285.01,20.13,56.0,H-LC,14.89,120.0,1.49,1.68,33.75,AR,ATH,PHARMA
27,GLAXO,2.40,21.81,11.39,35.69,27649.0,43468.0,242752.0,3380.16,-8.73,75.0,X-MC,13.53,56.0,1.57,1.60,44.28,X40,ATH,PHARMA

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.10,62.92,27.61,107.91,66415.0,92903.0,240547.0,1641.55,18.78,65.0,M-SC,26.13,220.0,1.40,1.59,80.97,OX40N,ATH,CABLES
67,STARHEALTH,0.15,12.96,30.36,47.26,96411.0,36437.0,317560.0,761.00,-0.37,51.0,H-SC,15.47,173.0,0.38,2.09,37.30,XY24,NTT,INSURANCE

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.10,62.92,27.61,107.91,66415.0,92903.0,240547.0,1641.55,18.78,65.0,M-SC,26.13,220.0,1.40,1.59,80.97,OX40N,ATH,CABLES
3,ALKYLAMINE,1.36,-11.00,116.35,92.54,104544.0,-11110.0,89853.0,4520.85,NaN,67.0,NaN,17.69,142.0,-0.11,0.59,70.62,SR,ATH,CHEMICALS
66,SIS,1.94,-3.29,25.39,21.26,27264.0,-3652.0,107380.0,528.00,106.30,47.0,H-SC,19.64,168.0,-0.13,0.71,59.66,OX40N,NTT,MISC
42,INDIAMART,0.09,-24.72,166.89,100.92,154959.0,-30485.0,92851.0,4675.60,NaN,40.0,NaN,13.18,140.0,-0.20,0.61,1.01,AR,ATH,MISC
70,TANLA,-5.40,-40.55,265.43,117.25,427265.0,-109790.0,160971.0,1922.32,NaN,32.0,NaN,13.77,147.0,-0.26,1.06,40.93,AR,ATH,IT

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.72,-23.32,87.40,43.70,166250.0,-57851.0,190217.0,735.00,-33.80,28.0,X-MC,11.22,70.0,-0.35,1.25,0.00,XY24,BTT,FMCG
56,PGHH,0.59,-39.03,116.52,32.01,151690.0,-83336.0,130184.0,17616.87,-55.19,28.0,X-SC,20.09,57.0,-0.55,0.86,0.59,X40,ATH,FMCG
55,PAGEIND,-0.97,-8.31,44.89,32.85,110468.0,-22294.0,246085.0,50936.07,-31.87,29.0,X-MC,8.22,55.0,-0.20,1.62,17.51,X40,ATH,APPARELS
19,COLPAL,-0.90,-29.38,98.03,39.86,182336.0,-77365.0,186000.0,3683.41,-14.54,29.0,X-MC,4.13,62.0,-0.42,1.23,5.21,XY25,ATH,FMCG
74,TMPV,-0.37,-25.51,91.63,42.75,284025.0,-106138.0,309969.0,600.00,-84.91,30.0,X-LC,4.43,4.0,-0.37,2.04,6.58,XY24,NTT,AUTO

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABBOTINDIA,0.53,-10.92,29.51,15.37,47018.0,-19525.0,159330.0,34390.26,-27.58,42.0,X-MC,2.06,58.0,-0.42,1.05,7.93,X40,ATH,PHARMA
50,KOTAKBANK,3.76,9.52,8.58,18.92,22524.0,22819.0,262521.0,452.46,-7.40,71.0,X-LC,2.08,12.0,1.01,1.73,18.12,X40,ATH,BANKS
23,DMART,-2.12,-6.72,40.88,31.42,118897.0,-20946.0,290844.0,5391.45,-21.79,36.0,X-LC,2.10,14.0,-0.18,1.92,4.95,X40N,ATH,FMCG
53,MARUTI,-1.16,-1.57,26.63,24.64,64807.0,-3878.0,243360.0,17120.06,-7.22,42.0,X-LC,3.67,33.0,-0.06,1.60,10.97,XR,ATH,AUTO
19,COLPAL,-0.90,-29.38,98.03,39.86,182336.0,-77365.0,186000.0,3683.41,-14.54,29.0,X-MC,4.13,62.0,-0.42,1.23,5.21,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
20,DABUR,-0.72,-23.32,87.40,43.70,166250.0,-57851.0,190217.0,735.00,-33.80,28.0,X-MC,11.22,70.0,-0.35,1.25,0.00,XY24,BTT,FMCG
82,VOLTAS,-2.09,-4.79,52.51,45.20,95857.0,-9192.0,182550.0,1856.00,31.07,36.0,X-MC,5.89,79.0,-0.10,1.20,0.05,XY25,NTT,AC
36,HINDUNILVR,-0.16,-15.92,44.58,21.56,126135.0,-53577.0,282940.0,2922.00,-42.16,39.0,X-LC,7.11,9.0,-0.42,1.87,0.30,XY25,NTT,FMCG
56,PGHH,0.59,-39.03,116.52,32.01,151690.0,-83336.0,130184.0,17616.87,-55.19,28.0,X-SC,20.09,57.0,-0.55,0.86,0.59,X40,ATH,FMCG
39,ICICIGI,-1.18,-15.41,40.55,18.89,68639.0,-30838.0,169271.0,2244.41,-15.62,37.0,X-MC,10.25,66.0,-0.45,1.12,0.85,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
56,PGHH,0.59,-39.03,116.52,32.01,151690.0,-83336.0,130184.0,17616.87,-55.19,28.0,X-SC,20.09,57.0,-0.55,0.86,0.59,X40,ATH,FMCG
1,ABBOTINDIA,0.53,-10.92,29.51,15.37,47018.0,-19525.0,159330.0,34390.26,-27.58,42.0,X-MC,2.06,58.0,-0.42,1.05,7.93,X40,ATH,PHARMA
2,ACC,1.98,-40.40,193.31,74.81,308917.0,-108324.0,159804.0,3906.00,-40.88,49.0,X-SC,11.32,85.0,-0.35,1.05,6.76,XY24,BTT,CEMENT
40,ICICIPRULI,0.99,-14.77,52.85,30.28,88738.0,-29099.0,167906.0,787.27,-45.40,57.0,X-MC,11.54,78.0,-0.33,1.11,11.87,X40,ATH,INSURANCE
39,ICICIGI,-1.18,-15.41,40.55,18.89,68639.0,-30838.0,169271.0,2244.41,-15.62,37.0,X-MC,10.25,66.0,-0.45,1.12,0.85,X40,ATH,INSURANCE

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.42,-25.44,67.25,24.70,199190.0,-101084.0,296194.0,452.00,-30.35,38.0,X-LC,10.93,1.0,-0.51,1.95,1.20,X40,NTT,FMCG
72,TCS,-1.14,-33.36,86.37,24.20,266641.0,-154553.0,308720.0,4230.71,-44.65,45.0,X-LC,13.12,2.0,-0.58,2.04,15.12,X40,ATH,IT
45,INFY,-2.10,-20.27,76.07,40.38,228332.0,-76310.0,300160.0,1972.00,-41.25,47.0,X-LC,15.35,3.0,-0.33,1.98,13.67,X40,NTT,IT
74,TMPV,-0.37,-25.51,91.63,42.75,284025.0,-106138.0,309969.0,600.00,-84.91,30.0,X-LC,4.43,4.0,-0.37,2.04,6.58,XY24,NTT,AUTO
33,HCLTECH,-1.31,-13.15,42.74,23.97,114881.0,-40696.0,268790.0,1853.42,-15.52,49.0,X-LC,9.42,8.0,-0.35,1.77,26.84,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.08,-25.88,79.28,32.89,45370.0,-19978.0,57228.0,1800.00,321.65,48.0,L-MC,11.82,258.0,-0.44,0.38,41.09,XR,NTT,BANKS
30,HAPPSTMNDS,0.43,-44.09,227.46,83.08,162989.0,-56509.0,71656.0,1466.54,NaN,69.0,NaN,7.29,152.0,-0.35,0.47,34.22,AR,ATH,IT
76,TTKPRESTIG,2.45,-20.69,26.20,0.09,20942.0,-20847.0,79930.0,770.00,-3.55,51.0,M-SC,8.42,250.0,-1.00,0.53,43.86,OX40N,NTT,DURABLES
3,ALKYLAMINE,1.36,-11.00,116.35,92.54,104544.0,-11110.0,89853.0,4520.85,NaN,67.0,NaN,17.69,142.0,-0.11,0.59,70.62,SR,ATH,CHEMICALS
12,BOSCH-HCIL,2.45,-25.27,33.79,-0.01,32274.0,-32291.0,95514.0,2282.00,745.07,64.0,M-SC,14.50,231.0,-1.00,0.63,62.58,OX40N,BTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,2.10,62.92,27.61,107.91,66415.0,92903.0,240547.0,1641.55,18.78,65.0,M-SC,26.13,220.0,1.40,1.59,80.97,OX40N,ATH,CABLES
12,BOSCH-HCIL,2.45,-25.27,33.79,-0.01,32274.0,-32291.0,95514.0,2282.00,745.07,64.0,M-SC,14.50,231.0,-1.00,0.63,62.58,OX40N,BTT,AC
27,GLAXO,2.40,21.81,11.39,35.69,27649.0,43468.0,242752.0,3380.16,-8.73,75.0,X-MC,13.53,56.0,1.57,1.60,44.28,X40,ATH,PHARMA
30,HAPPSTMNDS,0.43,-44.09,227.46,83.08,162989.0,-56509.0,71656.0,1466.54,NaN,69.0,NaN,7.29,152.0,-0.35,0.47,34.22,AR,ATH,IT
3,ALKYLAMINE,1.36,-11.00,116.35,92.54,104544.0,-11110.0,89853.0,4520.85,NaN,67.0,NaN,17.69,142.0,-0.11,0.59,70.62,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.85
1     25       45.62
2     50       78.33

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
LC    37.31
MC    22.43
SC    22.06
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      27.22
XY24     24.29
X40N     18.83
XR        9.20
OX40N     7.44
XY25      7.22
AR        4.88
SR        0.94
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    34.82
X-MC    19.82
H-SC     8.67
X-SC     7.82
M-SC     5.57
H-LC     1.68
M-MC     1.17
H-MC     1.06
M-LC     0.81
L-MC     0.38
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.53        -26.57   71.97
IT                  11.28        -39.36  108.48
FINANCE             10.87        -17.10   67.53
AUTO                 8.36         -6.51   44.65
BANKS                6.43         -9.60   56.86
PHARMA               6.03          9.34   16.37
MISC                 5.97        -36.25   91.06
INSURANCE            5.89         -4.08   40.88
PAINTS               5.51        -17.95   38.07
ELECTRICAL           2.94        -16.63   61.68
AC                   1.83        -14.92   46.08
REFINERIES           1.75        -12.57   50.39
BREWERIES            1.74         11.52    6.86
FOOTWEAR             1.68        -73.80  143.48
APPARELS             1.62         -9.06   44.89
CABLES               1.59         38.62   27.61
DURABLES             1.52        -68.24  109.18
TRAVEL               1.45       -103.12  204.83
CERAMICS             1.31        -54.77  101.78
CHEMICALS            1.26        -38.64  151.17
ENGINEERING          1.24        -28.69   87.55
CEMENT               1.05        -67.79  193.31
JEWELLERY            0.96       -118.51  194.43
HEALTHCARE           0.72        -66.57  108.39
ENTERTAINMENT        0.71        -79.36  186.33
TEXTILES             0.40        -52.82   96.40
HOTELS               0.38        -98.59  168.64

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3639779.0     19
X40       2093976.0     18
XR        1402070.0     13
X40N      1223741.0     12
AR        1059945.0      7
OX40N      664778.0     10
XY25       605841.0      5
SR         272939.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
X-LC        2446071.0     19
X-MC        1495088.0     14
X-SC        1088673.0      6
H-SC         835182.0      8
M-SC         321581.0      6
H-MC         253386.0      1
M-LC         168642.0      1
M-MC          68084.0      1
L-MC          45370.0      1
H-LC          29837.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1211361.0      9
X-SC       XY24       656285.0      2
H-SC       XY24       524735.0      3
X-MC       X40        509223.0      6
X-LC       XY24       472362.0      2
X-MC       X40N       457682.0      4
X-LC       X40N       437977.0      5
X-MC       XY25       278193.0      2
X-LC       XY25       259564.0      2
X-SC       X40        256324.0      2
H-MC       XY24       253386.0      1
X-MC       XY24       249990.0      2
H-SC       OX40N      222089.0      3
X-SC       X40N       176064.0      2
M-LC       XR         168642.0      1
M-SC       OX40N      147149.0      4
           XY24       116238.0      1
H-SC       XR          88358.0      2
M-MC       XY25        68084.0      1
X-LC       XR          64807.0      1
M-SC       XR          58194.0      1
L-MC       XR          45370.0      1
H-LC       AR          29837.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 29.0 seconds