<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-06 13:30:53
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20

-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.50 C
-------------------
Today PnL: 60.89 K (0.41%)
Current PnL: -33.15 L (-18.18%)
CY Booked + Current PnL: -31.07 L (-17.03%)
-------------------
Total profit:  1.54 L
Total loss:  -34.69 L
-------------------
Total Booked + Current PnL: 11.80 L (8.46%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.39%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.05 C (70.26%)
===================
Deployed:  1.40 C
Current:  1.50 C
CAGR/XIRR %: 3.6%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-1.48,4.30,16.55,21.57,16913.0,4215.0,102195.0,397.04,-10.12,65.0,H-SC,3.18,167.0,0.25,0.68,32.06,XR,ATH,FINANCE
53,M&M,1.81,6.07,16.32,23.38,24007.0,8419.0,147100.0,3802.40,-10.26,58.0,X-LC,7.82,25.0,0.35,0.98,11.52,X40N,ATH,AUTO
59,PIDILITIND,3.50,0.06,18.29,18.37,25825.0,90.0,141200.0,1670.26,-29.88,58.0,X-LC,5.92,5.0,0.00,0.94,10.87,X40,ATH,CHEMICALS
83,TTKPRESTIG,-0.63,-30.98,45.02,0.09,31313.0,-31223.0,69554.0,770.00,61.37,61.0,M-SC,17.14,250.0,-1.00,0.46,23.85,OX40N,NTT,DURABLES
51,KOTAKBANK,-1.00,-1.76,23.28,21.11,31668.0,-2442.0,136030.0,453.24,-15.91,42.0,X-LC,7.86,12.0,-0.08,0.91,4.03,X40,ATH,BANKS

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
3,ALKYLAMINE,4.97,-31.03,180.74,93.63,125856.0,-31329.0,69634.0,4546.37,-26.06,66.0,H-SC,18.68,142.0,-0.25,0.46,31.49,SR,ATH,CHEMICALS
62,RAJOOENG,3.74,-43.23,145.92,39.61,84911.0,-44310.0,58190.0,143.10,-61.60,43.0,H-SC,23.58,136.0,-0.52,0.39,24.66,AR,ATH,MISC
59,PIDILITIND,3.50,0.06,18.29,18.37,25825.0,90.0,141200.0,1670.26,-29.88,58.0,X-LC,5.92,5.0,0.00,0.94,10.87,X40,ATH,CHEMICALS
77,TANLA,3.48,-37.08,245.31,117.25,417886.0,-100411.0,170350.0,1922.32,-36.34,65.0,H-SC,17.93,147.0,-0.24,1.14,49.15,AR,ATH,IT
30,HAPPSTMNDS,3.40,-51.43,280.55,84.85,174659.0,-65909.0,62256.0,1480.71,-42.16,56.0,H-SC,21.16,152.0,-0.38,0.42,15.29,AR,ATH,IT

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
60,QUESS,-2.94,-11.07,95.54,73.90,90736.0,-11821.0,94972.0,424.00,-52.07,66.0,X-SC,14.44,80.0,-0.13,0.63,27.76,XY24,NTT,MISC
72,SIS,-2.81,-10.25,35.11,21.26,34989.0,-11378.0,99654.0,528.00,2369.43,73.0,H-SC,8.61,168.0,-0.33,0.66,48.17,OX40N,NTT,MISC
84,UNITDSPR,-2.44,-5.72,28.09,20.77,62012.0,-13382.0,220762.0,1644.00,-16.33,43.0,X-MC,2.89,64.0,-0.22,1.47,5.31,X40N,NTT,BREWERIES
25,FINCABLES,-2.08,30.84,58.90,107.91,113783.0,45536.0,193180.0,1641.55,17.71,70.0,M-SC,15.39,220.0,0.40,1.29,45.34,OX40N,ATH,CABLES
65,RELIANCE,-2.06,-7.99,36.18,25.30,66900.0,-16054.0,184909.0,1952.00,-10.42,59.0,X-LC,3.88,21.0,-0.24,1.23,9.87,XY25,BTT,REFINERIES

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-0.02,-0.72,93.81,92.42,259444.0,-1996.0,276563.0,400.00,137.07,76.0,H-SC,12.42,174.0,-0.01,1.84,52.35,XY24,NTT,BANKS
74,STARHEALTH,-0.31,-0.20,47.55,47.26,133410.0,-555.0,280568.0,761.00,57.63,62.0,H-SC,8.41,173.0,-0.00,1.87,45.30,XY24,NTT,INSURANCE
91,ZYDUSLIFE,2.93,-0.98,36.97,35.63,76720.0,-2055.0,207519.0,1286.17,-13.96,58.0,H-MC,3.78,120.0,-0.03,1.38,9.11,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,30.84,58.90,107.91,113783.0,45536.0,193180.0,1641.55,17.71,70.0,M-SC,15.39,220.0,0.40,1.29,45.34,OX40N,ATH,CABLES
72,SIS,-2.81,-10.25,35.11,21.26,34989.0,-11378.0,99654.0,528.00,2369.43,73.0,H-SC,8.61,168.0,-0.33,0.66,48.17,OX40N,NTT,MISC
16,CERA,-0.34,-30.07,77.15,23.89,94907.0,-52887.0,123016.0,9475.00,-32.46,60.0,H-SC,11.62,153.0,-0.56,0.82,18.22,OX40N,NTT,CERAMICS
83,TTKPRESTIG,-0.63,-30.98,45.02,0.09,31313.0,-31223.0,69554.0,770.00,61.37,61.0,M-SC,17.14,250.0,-1.00,0.46,23.85,OX40N,NTT,DURABLES
50,KANSAINER,0.49,-34.89,74.29,13.47,130432.0,-94095.0,175572.0,340.00,-44.14,52.0,H-SC,16.31,162.0,-0.72,1.17,22.64,XY24,NTT,PAINTS

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,30.84,58.9,107.91,113783.0,45536.0,193180.0,1641.55,17.71,70.0,M-SC,15.39,220.0,0.4,1.29,45.34,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,30.84,58.90,107.91,113783.0,45536.0,193180.0,1641.55,17.71,70.0,M-SC,15.39,220.0,0.40,1.29,45.34,OX40N,ATH,CABLES
68,SATIN,2.38,6.82,42.15,51.83,124391.0,18832.0,295116.0,274.00,-4.07,74.0,H-SC,13.44,159.0,0.15,1.97,43.76,XY24,NTT,FINANCE
55,MASFIN,-1.48,4.30,16.55,21.57,16913.0,4215.0,102195.0,397.04,-10.12,65.0,H-SC,3.18,167.0,0.25,0.68,32.06,XR,ATH,FINANCE
73,SONACOMS,1.47,1.44,37.12,39.09,38089.0,1452.0,102611.0,804.02,-19.66,57.0,M-MC,19.01,193.0,0.04,0.68,45.16,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,-2.08,30.84,58.90,107.91,113783.0,45536.0,193180.0,1641.55,17.71,70.0,M-SC,15.39,220.0,0.40,1.29,45.34,OX40N,ATH,CABLES
55,MASFIN,-1.48,4.30,16.55,21.57,16913.0,4215.0,102195.0,397.04,-10.12,65.0,H-SC,3.18,167.0,0.25,0.68,32.06,XR,ATH,FINANCE
73,SONACOMS,1.47,1.44,37.12,39.09,38089.0,1452.0,102611.0,804.02,-19.66,57.0,M-MC,19.01,193.0,0.04,0.68,45.16,AR,ATH,AUTO
91,ZYDUSLIFE,2.93,-0.98,36.97,35.63,76720.0,-2055.0,207519.0,1286.17,-13.96,58.0,H-MC,3.78,120.0,-0.03,1.38,9.11,AR,ATH,PHARMA
42,INDIAMART,0.22,-11.58,133.81,106.72,145917.0,-14288.0,109048.0,4810.62,-60.16,41.0,H-SC,9.34,140.0,-0.10,0.73,4.77,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.78,-22.72,57.22,21.51,106985.0,-54953.0,186971.0,1872.35,-18.94,29.0,X-LC,10.84,8.0,-0.51,1.25,0.00,X40,ATH,IT
45,INFY,-0.77,-20.42,68.69,34.24,171036.0,-63891.0,248997.0,1972.00,-37.23,35.0,X-LC,14.90,3.0,-0.37,1.66,1.47,X40,NTT,IT
79,TCS,-0.30,-28.96,78.16,26.57,257240.0,-134153.0,329120.0,4311.59,-39.69,41.0,X-LC,14.00,2.0,-0.52,2.19,2.72,X40,ATH,IT
51,KOTAKBANK,-1.00,-1.76,23.28,21.11,31668.0,-2442.0,136030.0,453.24,-15.91,42.0,X-LC,7.86,12.0,-0.08,0.91,4.03,X40,ATH,BANKS
84,UNITDSPR,-2.44,-5.72,28.09,20.77,62012.0,-13382.0,220762.0,1644.00,-16.33,43.0,X-MC,2.89,64.0,-0.22,1.47,5.31,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-0.29,7.32,35.29,45.20,72622.0,14043.0,205785.0,1856.00,22.90,45.0,X-MC,1.82,79.0,0.19,1.37,12.79,XY25,NTT,AC
84,UNITDSPR,-2.44,-5.72,28.09,20.77,62012.0,-13382.0,220762.0,1644.00,-16.33,43.0,X-MC,2.89,64.0,-0.22,1.47,5.31,X40N,NTT,BREWERIES
65,RELIANCE,-2.06,-7.99,36.18,25.30,66900.0,-16054.0,184909.0,1952.00,-10.42,59.0,X-LC,3.88,21.0,-0.24,1.23,9.87,XY25,BTT,REFINERIES
81,TMPV,2.54,-20.60,72.02,36.58,203477.0,-73313.0,282528.0,600.00,-83.62,54.0,X-LC,4.97,4.0,-0.36,1.88,17.76,XY24,NTT,AUTO
19,COLPAL,-0.75,-17.89,72.33,41.51,156421.0,-47105.0,216260.0,3726.84,-0.69,62.0,X-MC,5.19,62.0,-0.30,1.44,20.90,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,-0.78,-22.72,57.22,21.51,106985.0,-54953.0,186971.0,1872.35,-18.94,29.0,X-LC,10.84,8.0,-0.51,1.25,0.00,X40,ATH,IT
45,INFY,-0.77,-20.42,68.69,34.24,171036.0,-63891.0,248997.0,1972.00,-37.23,35.0,X-LC,14.90,3.0,-0.37,1.66,1.47,X40,NTT,IT
1,ABBOTINDIA,1.46,-13.87,37.08,18.07,57122.0,-24805.0,154050.0,35195.00,-26.70,48.0,X-MC,11.94,58.0,-0.43,1.03,1.97,X40,ATH,PHARMA
79,TCS,-0.30,-28.96,78.16,26.57,257240.0,-134153.0,329120.0,4311.59,-39.69,41.0,X-LC,14.00,2.0,-0.52,2.19,2.72,X40,ATH,IT
51,KOTAKBANK,-1.00,-1.76,23.28,21.11,31668.0,-2442.0,136030.0,453.24,-15.91,42.0,X-LC,7.86,12.0,-0.08,0.91,4.03,X40,ATH,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,-0.50,-61.39,294.43,52.31,165034.0,-89108.0,56052.0,1176.00,-58.86,49.0,X-SC,25.03,92.0,-0.54,0.37,25.33,X40N,NTT,FOOTWEAR
10,BATAINDIA,0.46,-53.44,190.37,35.20,114058.0,-68756.0,59914.0,2096.00,-21.44,49.0,X-SC,26.14,91.0,-0.60,0.40,18.82,X40,NTT,FOOTWEAR
60,QUESS,-2.94,-11.07,95.54,73.90,90736.0,-11821.0,94972.0,424.00,-52.07,66.0,X-SC,14.44,80.0,-0.13,0.63,27.76,XY24,NTT,MISC
51,KOTAKBANK,-1.00,-1.76,23.28,21.11,31668.0,-2442.0,136030.0,453.24,-15.91,42.0,X-LC,7.86,12.0,-0.08,0.91,4.03,X40,ATH,BANKS
59,PIDILITIND,3.50,0.06,18.29,18.37,25825.0,90.0,141200.0,1670.26,-29.88,58.0,X-LC,5.92,5.0,0.00,0.94,10.87,X40,ATH,CHEMICALS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.40,-18.29,45.71,19.06,127046.0,-62227.0,277939.0,452.00,-55.12,54.0,X-LC,15.60,1.0,-0.49,1.85,7.82,X40,NTT,FMCG
79,TCS,-0.30,-28.96,78.16,26.57,257240.0,-134153.0,329120.0,4311.59,-39.69,41.0,X-LC,14.00,2.0,-0.52,2.19,2.72,X40,ATH,IT
45,INFY,-0.77,-20.42,68.69,34.24,171036.0,-63891.0,248997.0,1972.00,-37.23,35.0,X-LC,14.90,3.0,-0.37,1.66,1.47,X40,NTT,IT
81,TMPV,2.54,-20.60,72.02,36.58,203477.0,-73313.0,282528.0,600.00,-83.62,54.0,X-LC,4.97,4.0,-0.36,1.88,17.76,XY24,NTT,AUTO
59,PIDILITIND,3.50,0.06,18.29,18.37,25825.0,90.0,141200.0,1670.26,-29.88,58.0,X-LC,5.92,5.0,0.00,0.94,10.87,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.48,-31.77,94.76,32.89,49919.0,-24528.0,52679.0,1800.00,-347.90,64.0,L-MC,4.37,258.0,-0.49,0.35,29.67,XR,NTT,BANKS
12,BOSCH-HCIL,0.32,-37.12,59.02,-0.01,47428.0,-47445.0,80360.0,2282.00,16334.78,61.0,M-SC,3.29,231.0,-1.00,0.54,36.78,OX40N,BTT,AC
72,SIS,-2.81,-10.25,35.11,21.26,34989.0,-11378.0,99654.0,528.00,2369.43,73.0,H-SC,8.61,168.0,-0.33,0.66,48.17,OX40N,NTT,MISC
55,MASFIN,-1.48,4.30,16.55,21.57,16913.0,4215.0,102195.0,397.04,-10.12,65.0,H-SC,3.18,167.0,0.25,0.68,32.06,XR,ATH,FINANCE
73,SONACOMS,1.47,1.44,37.12,39.09,38089.0,1452.0,102611.0,804.02,-19.66,57.0,M-MC,19.01,193.0,0.04,0.68,45.16,AR,ATH,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
9,BANDHANBNK,-0.02,-0.72,93.81,92.42,259444.0,-1996.0,276563.0,400.00,137.07,76.0,H-SC,12.42,174.0,-0.01,1.84,52.35,XY24,NTT,BANKS
72,SIS,-2.81,-10.25,35.11,21.26,34989.0,-11378.0,99654.0,528.00,2369.43,73.0,H-SC,8.61,168.0,-0.33,0.66,48.17,OX40N,NTT,MISC
77,TANLA,3.48,-37.08,245.31,117.25,417886.0,-100411.0,170350.0,1922.32,-36.34,65.0,H-SC,17.93,147.0,-0.24,1.14,49.15,AR,ATH,IT
68,SATIN,2.38,6.82,42.15,51.83,124391.0,18832.0,295116.0,274.00,-4.07,74.0,H-SC,13.44,159.0,0.15,1.97,43.76,XY24,NTT,FINANCE
80,TITAGARH,0.76,-20.30,82.85,45.74,159921.0,-49152.0,193025.0,1548.00,6.29,74.0,H-SC,14.18,175.0,-0.31,1.29,47.27,XY24,NTT,ENGINEERING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.05
1     25       42.51
2     50       72.63

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.58
LC    31.62
MC    25.76
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.22
X40      25.46
X40N     16.82
XR        9.08
OX40N     6.90
XY25      6.87
AR        6.78
SR        0.83
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.43
H-SC    22.26
X-MC    20.83
M-SC    10.02
X-SC     9.76
H-MC     2.61
M-MC     1.97
H-LC     1.27
M-LC     0.92
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.56        -13.41   53.41
FINANCE             10.85        -13.35   62.65
IT                  10.55        -42.36  114.03
MISC                 7.03        -27.35   82.67
AUTO                 6.62        -10.02   51.27
BANKS                5.63         -7.52   57.23
INSURANCE            5.33         -3.44   38.64
PAINTS               5.07        -29.36   51.83
PHARMA               4.83         -2.20   35.04
ELECTRICAL           4.03        -17.09   58.77
CHEMICALS            2.05        -31.44  109.76
HEALTHCARE           1.96        -22.06   53.91
AC                   1.91        -11.67   41.95
DURABLES             1.76        -46.04   81.57
APPARELS             1.75         -2.10   36.93
TRAVEL               1.74        -70.51  155.90
FOOTWEAR             1.70        -72.60  141.81
BREWERIES            1.47         -6.06   28.09
REALTY               1.36         -8.39   26.20
CERAMICS             1.30        -57.33  105.13
CABLES               1.29         23.57   58.90
ENGINEERING          1.29        -25.46   82.85
REFINERIES           1.23         -8.68   36.18
CEMENT               1.12        -59.60  179.00
JEWELLERY            1.04       -104.10  175.01
ENTERTAINMENT        0.73        -76.29  181.44
TEXTILES             0.43        -42.07   82.58
HOTELS               0.33       -126.33  206.16

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3512405.0     21
X40       1883108.0     19
XR        1316809.0     13
X40N      1202651.0     13
AR        1167150.0      9
OX40N      756715.0     10
XY25       408859.0      5
SR         293388.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3446134.0     24
X-LC        1883647.0     21
X-MC        1607582.0     15
M-SC        1414211.0     14
X-SC        1340134.0      9
H-MC         305170.0      2
L-SC         208793.0      2
M-LC         153644.0      1
M-MC          89121.0      2
L-MC          49919.0      1
H-LC          42730.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1096059.0      6
X-LC       X40       1019529.0     10
H-SC       AR         933610.0      5
M-SC       XY24       842029.0      6
H-SC       XR         794316.0      7
X-SC       XY24       779085.0      4
X-MC       X40        657043.0      7
           X40N       492823.0      4
X-LC       X40N       355315.0      6
X-SC       X40N       354513.0      3
X-LC       XY24       338109.0      2
H-SC       OX40N      328761.0      4
M-SC       OX40N      322591.0      5
H-SC       SR         293388.0      2
X-MC       XY25       229043.0      2
           XY24       228673.0      2
H-MC       XY24       228450.0      1
X-SC       X40        206536.0      2
M-SC       XR         173590.0      2
M-LC       XR         153644.0      1
X-LC       XY25       128784.0      2
L-SC       OX40N      105363.0      1
           XR         103430.0      1
H-MC       AR          76720.0      1
M-SC       AR          76001.0      1
M-MC       XY25        51032.0      1
L-MC       XR          49919.0      1
H-LC       AR          42730.0      1
X-LC       XR          41910.0      1
M-MC       AR          38089.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 38.0 seconds