<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-07-30 13:06:05
-------------------
qualified stocks: 90
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  6.53 L
Current:  1.54 C
-------------------
Today PnL: 42.11 K (0.27%)
Current PnL: -30.85 L (-16.92%)
CY Booked + Current PnL: -27.21 L (-14.92%)
-------------------
Total profit:  3.98 L
Total loss:  -34.83 L
-------------------
Total Booked + Current PnL: 15.66 L (11.23%)
Total Booked PnL: 46.51 L (33.34%)
Curr Year Booked PnL: 3.64 L (2.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.01 C (65.42%)
===================
Deployed:  1.40 C
Current:  1.54 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,PIDILITIND,0.46,15.31,1.92,17.52,3124.0,21600.0,162710.0,1658.32,-19.26,64.0,X-LC,8.29,5.0,6.91,1.10,28.68,X40,ATH,CHEMICALS
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
55,MEDANTA,0.98,21.04,5.02,27.12,10726.0,37148.0,213665.0,1486.00,17.31,70.0,X-SC,12.77,87.0,3.46,1.45,47.23,XY24,NTT,HEALTHCARE
81,TTKPRESTIG,-1.56,-13.35,15.51,0.09,13544.0,-13452.0,87325.0,770.00,102.77,61.0,M-SC,13.01,250.0,-0.99,0.59,57.17,OX40N,NTT,DURABLES
52,M&M,2.73,7.40,13.69,22.10,20391.0,10265.0,148946.0,3762.88,-8.87,62.0,X-LC,7.07,25.0,0.50,1.01,14.11,X40N,ATH,AUTO

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
5,ATULAUTO,8.80,-10.69,63.00,45.57,110913.0,-21080.0,176052.0,844.00,3818.92,66.0,M-SC,5.15,248.0,-0.19,1.19,35.48,XY24,NTT,AUTO
11,BERGEPAINT,5.14,-3.25,29.52,25.32,73616.0,-8374.0,249375.0,680.00,-8.48,60.0,X-MC,1.61,68.0,-0.11,1.69,29.79,XY24,NTT,PAINTS
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
72,STARHEALTH,4.08,17.62,25.21,47.26,83355.0,49520.0,330643.0,761.00,85.67,63.0,H-SC,18.72,173.0,0.59,2.24,42.96,XY24,NTT,INSURANCE
63,RELAXO,3.84,-47.29,188.94,52.31,144569.0,-68644.0,76516.0,1176.00,-43.86,55.0,X-SC,9.36,92.0,-0.47,0.52,71.08,X40N,NTT,FOOTWEAR

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-4.72,-35.93,106.06,32.01,145082.0,-76728.0,136792.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
73,SURYODAY,-2.81,-8.28,34.14,23.03,56072.0,-14831.0,164240.0,216.00,79.82,38.0,H-SC,22.70,166.0,-0.26,1.11,39.41,XR,NTT,BANKS
39,ICICIGI,-2.24,-12.81,36.36,18.89,63439.0,-25633.0,174476.0,2244.41,-26.70,41.0,X-MC,7.59,66.0,-0.40,1.18,3.95,X40,ATH,INSURANCE
24,EASEMYTRIP,-1.93,-63.58,300.00,45.70,193209.0,-112412.0,64403.0,26.40,-33.14,37.0,M-SC,6.21,204.0,-0.58,0.44,12.82,XY24,NTT,TRAVEL
19,COLPAL,-1.88,-20.35,75.58,39.86,158552.0,-53585.0,209780.0,3683.41,-3.61,55.0,X-MC,1.67,62.0,-0.34,1.42,18.66,XY25,ATH,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.27,23.58,68.24,107.91,124508.0,34812.0,182456.0,1641.55,11.11,37.0,M-SC,19.73,220.0,0.28,1.24,37.27,OX40N,ATH,CABLES
70,SIS,-0.69,-1.81,23.49,21.26,25610.0,-2007.0,109025.0,528.00,2601.55,47.0,H-SC,23.92,168.0,-0.08,0.74,62.10,OX40N,NTT,MISC
81,TTKPRESTIG,-1.56,-13.35,15.51,0.09,13544.0,-13452.0,87325.0,770.00,102.77,61.0,M-SC,13.01,250.0,-0.99,0.59,57.17,OX40N,NTT,DURABLES
16,CERA,-1.70,-19.49,53.89,23.89,76314.0,-34292.0,141611.0,9475.00,-22.43,50.0,H-SC,13.98,153.0,-0.45,0.96,37.66,OX40N,NTT,CERAMICS
67,SFL,-0.61,-22.81,64.04,26.63,129626.0,-59804.0,202414.0,1287.00,53.39,62.0,M-SC,25.53,242.0,-0.46,1.37,68.93,XY24,NTT,MISC

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,0.27,23.58,68.24,107.91,124508.0,34812.0,182456.0,1641.55,11.11,37.0,M-SC,19.73,220.0,0.28,1.24,37.27,OX40N,ATH,CABLES
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
55,MEDANTA,0.98,21.04,5.02,27.12,10726.0,37148.0,213665.0,1486.00,17.31,70.0,X-SC,12.77,87.0,3.46,1.45,47.23,XY24,NTT,HEALTHCARE
59,QUESS,3.45,28.66,35.16,73.90,48310.0,30608.0,137401.0,424.00,-30.58,75.0,X-SC,36.68,80.0,0.63,0.93,87.31,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,STARHEALTH,4.08,17.62,25.21,47.26,83355.0,49520.0,330643.0,761.00,85.67,63.0,H-SC,18.72,173.0,0.59,2.24,42.96,XY24,NTT,INSURANCE
62,RECLTD,-0.04,1.27,19.22,20.74,39546.0,2585.0,205755.0,446.00,11.33,66.0,M-MC,2.13,191.0,0.07,1.40,22.62,XY25,NTT,FINANCE
25,FINCABLES,0.27,23.58,68.24,107.91,124508.0,34812.0,182456.0,1641.55,11.11,37.0,M-SC,19.73,220.0,0.28,1.24,37.27,OX40N,ATH,CABLES
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
89,ZYDUSLIFE,-0.04,18.34,14.51,35.51,35986.0,38432.0,248006.0,1285.01,3.15,52.0,H-MC,16.99,120.0,1.07,1.68,30.51,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
89,ZYDUSLIFE,-0.04,18.34,14.51,35.51,35986.0,38432.0,248006.0,1285.01,3.15,52.0,H-MC,16.99,120.0,1.07,1.68,30.51,AR,ATH,PHARMA
25,FINCABLES,0.27,23.58,68.24,107.91,124508.0,34812.0,182456.0,1641.55,11.11,37.0,M-SC,19.73,220.0,0.28,1.24,37.27,OX40N,ATH,CABLES
70,SIS,-0.69,-1.81,23.49,21.26,25610.0,-2007.0,109025.0,528.00,2601.55,47.0,H-SC,23.92,168.0,-0.08,0.74,62.10,OX40N,NTT,MISC
54,MASFIN,1.05,-2.62,24.84,21.57,23701.0,-2565.0,95415.0,397.04,-15.99,51.0,H-SC,1.91,167.0,-0.11,0.65,13.73,XR,ATH,FINANCE

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
23,DMART,0.05,-7.45,40.03,29.60,92472.0,-18594.0,231006.0,5391.45,-21.92,33.0,X-LC,2.96,14.0,-0.20,1.57,5.59,X40N,ATH,FMCG
57,PGHH,-4.72,-35.93,106.06,32.01,145082.0,-76728.0,136792.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
85,VBL,0.09,-9.58,49.72,35.37,141985.0,-30273.0,285569.0,670.16,-20.26,37.0,X-LC,7.15,13.0,-0.21,1.94,17.37,X40N,ATH,FMCG
34,HDFCBANK,0.27,-10.25,43.02,28.37,90695.0,-24065.0,210820.0,1073.00,-23.49,40.0,X-LC,10.25,26.0,-0.27,1.43,4.25,X40,BTT,BANKS
35,HDFCLIFE,-1.43,-10.25,47.87,32.71,64358.0,-15356.0,134444.0,811.41,-29.90,40.0,X-LC,15.84,31.0,-0.24,0.91,1.00,X40,ATH,INSURANCE

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
11,BERGEPAINT,5.14,-3.25,29.52,25.32,73616.0,-8374.0,249375.0,680.00,-8.48,60.0,X-MC,1.61,68.0,-0.11,1.69,29.79,XY24,NTT,PAINTS
19,COLPAL,-1.88,-20.35,75.58,39.86,158552.0,-53585.0,209780.0,3683.41,-3.61,55.0,X-MC,1.67,62.0,-0.34,1.42,18.66,XY25,ATH,FMCG
8,BAJAJHLDNG,1.05,-2.14,30.42,27.63,56601.0,-4060.0,186065.0,14274.15,-9.33,62.0,X-LC,2.65,28.0,-0.07,1.26,26.70,X40,ATH,FINANCE
1,ABBOTINDIA,-0.95,-7.28,24.42,15.37,40498.0,-13015.0,165840.0,34390.26,-21.17,63.0,X-MC,2.78,58.0,-0.32,1.13,12.34,X40,ATH,PHARMA
17,CIPLA,-0.11,19.23,11.91,33.43,21749.0,29454.0,182615.0,1648.14,-7.62,62.0,X-LC,2.94,18.0,1.35,1.24,24.67,X40N,ATH,PHARMA

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
57,PGHH,-4.72,-35.93,106.06,32.01,145082.0,-76728.0,136792.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
35,HDFCLIFE,-1.43,-10.25,47.87,32.71,64358.0,-15356.0,134444.0,811.41,-29.90,40.0,X-LC,15.84,31.0,-0.24,0.91,1.00,X40,ATH,INSURANCE
64,RELIANCE,1.26,-17.07,51.08,25.30,85134.0,-34295.0,166668.0,1952.00,-19.26,49.0,X-LC,7.87,21.0,-0.40,1.13,2.64,XY25,BTT,REFINERIES
47,ITC,-0.02,-24.61,57.93,19.06,148553.0,-83731.0,256435.0,452.00,-58.75,54.0,X-LC,12.18,1.0,-0.56,1.74,3.86,X40,NTT,FMCG
39,ICICIGI,-2.24,-12.81,36.36,18.89,63439.0,-25633.0,174476.0,2244.41,-26.70,41.0,X-MC,7.59,66.0,-0.40,1.18,3.95,X40,ATH,INSURANCE

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,0.72,-54.85,199.45,35.20,115872.0,-70574.0,58096.0,2096.00,-23.90,53.0,X-SC,16.54,91.0,-0.61,0.39,15.22,X40,NTT,FOOTWEAR
63,RELAXO,3.84,-47.29,188.94,52.31,144569.0,-68644.0,76516.0,1176.00,-43.86,55.0,X-SC,9.36,92.0,-0.47,0.52,71.08,X40N,NTT,FOOTWEAR
35,HDFCLIFE,-1.43,-10.25,47.87,32.71,64358.0,-15356.0,134444.0,811.41,-29.90,40.0,X-LC,15.84,31.0,-0.24,0.91,1.00,X40,ATH,INSURANCE
57,PGHH,-4.72,-35.93,106.06,32.01,145082.0,-76728.0,136792.0,17616.87,-56.66,33.0,X-MC,19.37,57.0,-0.53,0.93,0.00,X40,ATH,FMCG
59,QUESS,3.45,28.66,35.16,73.90,48310.0,30608.0,137401.0,424.00,-30.58,75.0,X-SC,36.68,80.0,0.63,0.93,87.31,XY24,NTT,MISC

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.02,-24.61,57.93,19.06,148553.0,-83731.0,256435.0,452.00,-58.75,54.0,X-LC,12.18,1.0,-0.56,1.74,3.86,X40,NTT,FMCG
77,TCS,0.48,-27.83,72.09,24.20,241027.0,-128931.0,334342.0,4230.71,-39.04,74.0,X-LC,16.80,2.0,-0.53,2.27,24.68,X40,ATH,IT
45,INFY,1.78,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,66.0,X-LC,18.55,3.0,-0.37,1.70,19.37,X40,NTT,IT
79,TMPV,0.79,-24.34,80.51,36.58,216768.0,-86597.0,269244.0,600.00,-84.72,44.0,X-LC,6.83,4.0,-0.40,1.83,13.15,XY24,NTT,AUTO
58,PIDILITIND,0.46,15.31,1.92,17.52,3124.0,21600.0,162710.0,1658.32,-19.26,64.0,X-LC,8.29,5.0,6.91,1.10,28.68,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.40,-25.56,78.52,32.89,45128.0,-19734.0,57473.0,1800.00,-370.31,54.0,L-MC,14.44,258.0,-0.44,0.39,41.69,XR,NTT,BANKS
63,RELAXO,3.84,-47.29,188.94,52.31,144569.0,-68644.0,76516.0,1176.00,-43.86,55.0,X-SC,9.36,92.0,-0.47,0.52,71.08,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-0.56,-23.30,151.03,92.54,116956.0,-23524.0,77439.0,4520.85,-17.90,48.0,H-SC,12.93,142.0,-0.20,0.53,47.05,SR,ATH,CHEMICALS
81,TTKPRESTIG,-1.56,-13.35,15.51,0.09,13544.0,-13452.0,87325.0,770.00,102.77,61.0,M-SC,13.01,250.0,-0.99,0.59,57.17,OX40N,NTT,DURABLES
70,SIS,-0.69,-1.81,23.49,21.26,25610.0,-2007.0,109025.0,528.00,2601.55,47.0,H-SC,23.92,168.0,-0.08,0.74,62.10,OX40N,NTT,MISC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.46,-11.49,35.89,20.28,76852.0,-27792.0,214132.0,1853.42,-6.95,78.0,X-LC,15.49,8.0,-0.36,1.45,33.23,X40,ATH,IT
77,TCS,0.48,-27.83,72.09,24.20,241027.0,-128931.0,334342.0,4230.71,-39.04,74.0,X-LC,16.80,2.0,-0.53,2.27,24.68,X40,ATH,IT
71,SONACOMS,4.46,30.20,6.52,38.69,8587.0,30546.0,131705.0,801.69,3.16,78.0,M-MC,28.36,193.0,3.56,0.89,86.86,AR,ATH,AUTO
22,DIXON,0.79,4.82,31.58,37.92,86331.0,12574.0,273372.0,18931.72,-55.41,67.0,X-MC,11.41,54.0,0.15,1.86,48.74,X40N,ATH,IT
45,INFY,1.78,-19.93,67.66,34.24,169509.0,-62357.0,250531.0,1972.00,-36.87,66.0,X-LC,18.55,3.0,-0.37,1.70,19.37,X40,NTT,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.33
1     25       42.90
2     50       73.82

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    42.29
LC    31.76
MC    25.90
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.23
XY24     25.92
X40N     16.54
XR        9.23
AR        7.23
OX40N     7.16
XY25      6.73
SR        0.91
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.64
H-SC    20.75
X-MC    20.45
X-SC    10.66
M-SC    10.33
H-MC     2.77
M-MC     2.29
H-LC     1.23
M-LC     0.89
L-SC     0.55
L-MC     0.39
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                14.53        -23.58   66.93
IT                  11.23        -36.17  103.46
FINANCE              9.00        -18.13   67.55
MISC                 7.65        -18.78   69.74
AUTO                 7.07         -5.00   44.16
PAINTS               5.71        -17.09   37.06
BANKS                5.49        -12.32   64.22
INSURANCE            5.46         -2.75   37.41
PHARMA               5.46          7.93   19.93
ELECTRICAL           4.37         -9.66   48.06
CHEMICALS            2.25        -22.34   94.55
HEALTHCARE           2.21         -9.73   38.36
APPARELS             1.96          6.98   24.27
AC                   1.85        -17.08   48.82
BREWERIES            1.77         10.23    8.41
FOOTWEAR             1.77        -69.47  137.42
DURABLES             1.70        -53.89   91.33
TRAVEL               1.53        -98.65  198.11
CERAMICS             1.45        -43.25   86.77
ENGINEERING          1.29        -27.84   86.32
CABLES               1.24         19.08   68.24
JEWELLERY            1.18        -84.34  148.38
REFINERIES           1.13        -20.58   51.08
CEMENT               1.10        -65.70  189.66
ENTERTAINMENT        0.74        -78.08  184.29
TEXTILES             0.42        -50.49   93.39
HOTELS               0.39        -95.83  164.90

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3358422.0     20
X40       1796850.0     19
XR        1319473.0     13
AR        1104321.0      9
X40N      1023155.0     12
OX40N      736132.0     10
XY25       444170.0      5
SR         283082.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3293183.0     23
X-LC        1903002.0     21
X-MC        1440259.0     14
M-SC        1395263.0     14
X-SC        1230030.0      9
H-MC         288898.0      2
L-SC         210013.0      2
M-LC         161065.0      1
H-LC          50631.0      1
M-MC          48133.0      2
L-MC          45128.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                          sum  count
Conviction Criteria
H-SC       XY24      980602.0      5
X-LC       X40       946245.0     10
H-SC       AR        933039.0      5
M-SC       XY24      813752.0      6
H-SC       XR        788081.0      7
X-SC       XY24      730887.0      4
X-MC       X40       638748.0      7
X-LC       X40N      396166.0      6
           XY24      356117.0      2
X-MC       X40N      339703.0      3
M-SC       OX40N     313356.0      5
H-SC       OX40N     308379.0      4
X-SC       X40N      287286.0      3
H-SC       SR        283082.0      2
H-MC       XY24      252912.0      1
X-MC       XY25      237656.0      2
           XY24      224152.0      2
X-SC       X40       211857.0      2
M-SC       XR        192077.0      2
X-LC       XY25      166968.0      2
M-LC       XR        161065.0      1
L-SC       OX40N     114397.0      1
           XR         95616.0      1
M-SC       AR         76078.0      1
H-LC       AR         50631.0      1
L-MC       XR         45128.0      1
M-MC       XY25       39546.0      1
X-LC       XR         37506.0      1
H-MC       AR         35986.0      1
M-MC       AR          8587.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 33.0 seconds