<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-08 10:23:47
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 20.44 K (0.13%)
Current PnL: -30.82 L (-16.9%)
CY Booked + Current PnL: -28.74 L (-15.76%)
-------------------
Total profit:  2.26 L
Total loss:  -33.08 L
-------------------
Total Booked + Current PnL: 14.13 L (10.13%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.66%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,0.19,6.52,14.12,21.57,14737.0,6390.0,104370.0,397.04,-8.31,70.0,H-SC,4.39,167.0,0.43,0.69,34.87,XR,ATH,FINANCE
59,PIDILITIND,2.34,5.19,12.53,18.37,18598.0,7320.0,148430.0,1670.26,-26.30,69.0,X-LC,5.41,5.0,0.39,0.97,16.54,X40,ATH,CHEMICALS
53,M&M,-0.47,8.86,13.35,23.38,20153.0,12281.0,150962.0,3802.40,-7.83,62.0,X-LC,7.57,25.0,0.61,0.99,14.45,X40N,ATH,AUTO
51,KOTAKBANK,-0.74,0.63,20.35,21.11,28356.0,870.0,139342.0,453.24,-13.74,49.0,X-LC,7.48,12.0,0.03,0.91,6.56,X40,ATH,BANKS
83,TTKPRESTIG,-1.36,-31.57,46.26,0.09,31903.0,-31812.0,68965.0,770.00,60.09,58.0,M-SC,17.26,250.0,-1.00,0.45,22.80,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES
75,SURYODAY,5.71,-2.84,26.63,23.03,46331.0,-5090.0,173981.0,216.00,88.60,81.0,H-SC,9.51,166.0,-0.11,1.14,48.37,XR,NTT,BANKS
43,INDIGOPNTS,3.93,-31.73,46.51,0.02,55423.0,-55395.0,119164.0,1408.00,81.92,72.0,M-SC,21.03,222.0,-1.00,0.78,35.20,OX40N,NTT,PAINTS
11,BERGEPAINT,3.09,-7.24,35.09,25.32,83897.0,-18658.0,239091.0,680.00,-12.26,72.0,X-MC,12.80,68.0,-0.22,1.57,24.44,XY24,NTT,PAINTS
16,CERA,2.47,-26.89,69.45,23.89,89315.0,-47299.0,128604.0,9475.00,-29.36,70.0,H-SC,11.15,153.0,-0.53,0.84,23.59,OX40N,NTT,CERAMICS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-2.87,-57.42,294.88,68.16,167097.0,-76400.0,56666.0,2215.45,-65.51,64.0,H-SC,27.12,141.0,-0.46,0.37,35.00,SR,ATH,IT
88,VOLTAS,-2.20,4.35,39.14,45.20,78313.0,8343.0,200085.0,1856.00,19.51,41.0,X-MC,2.39,79.0,0.11,1.31,9.67,XY25,NTT,AC
6,AWL,-2.00,-28.48,133.51,67.02,340248.0,-101461.0,254848.0,485.00,-61.53,63.0,X-SC,20.06,81.0,-0.30,1.67,20.55,XY24,NTT,FMCG
89,WHIRLPOOL,-1.91,-23.06,136.46,81.92,120521.0,-26478.0,88320.0,2270.00,-54.92,59.0,M-SC,17.32,210.0,-0.22,0.58,24.06,XR,NTT,DURABLES
0,5PAISA,-1.78,-36.43,77.60,12.90,107788.0,-79594.0,138902.0,593.00,104.33,58.0,H-SC,8.37,170.0,-0.74,0.91,34.04,OX40N,NTT,FINANCE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,-0.17,-0.07,39.19,39.09,39617.0,-70.0,101089.0,804.02,-20.87,54.0,M-MC,19.75,193.0,-0.00,0.66,43.00,AR,ATH,AUTO
74,STARHEALTH,0.57,0.70,46.23,47.26,130876.0,1975.0,283098.0,761.00,59.02,63.0,H-SC,9.58,173.0,0.02,1.86,46.61,XY24,NTT,INSURANCE
91,ZYDUSLIFE,0.91,0.06,35.55,35.63,74547.0,122.0,209696.0,1286.17,-13.06,61.0,H-MC,3.53,120.0,0.00,1.38,10.25,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES
72,SIS,0.59,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.00,2430.57,76.0,H-SC,10.74,168.0,-0.27,0.67,51.85,OX40N,NTT,MISC
16,CERA,2.47,-26.89,69.45,23.89,89315.0,-47299.0,128604.0,9475.00,-29.36,70.0,H-SC,11.15,153.0,-0.53,0.84,23.59,OX40N,NTT,CERAMICS
50,KANSAINER,0.93,-28.74,59.24,13.47,113840.0,-77499.0,192168.0,340.00,-38.75,67.0,H-SC,16.05,162.0,-0.68,1.26,34.23,XY24,NTT,PAINTS
83,TTKPRESTIG,-1.36,-31.57,46.26,0.09,31903.0,-31812.0,68965.0,770.00,60.09,58.0,M-SC,17.26,250.0,-1.00,0.45,22.80,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,0.57,0.70,46.23,47.26,130876.0,1975.0,283098.0,761.00,59.02,63.0,H-SC,9.58,173.0,0.02,1.86,46.61,XY24,NTT,INSURANCE
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES
68,SATIN,0.39,13.37,33.93,51.83,106273.0,36928.0,313212.0,274.00,1.18,79.0,H-SC,16.66,159.0,0.35,2.06,52.58,XY24,NTT,FINANCE
55,MASFIN,0.19,6.52,14.12,21.57,14737.0,6390.0,104370.0,397.04,-8.31,70.0,H-SC,4.39,167.0,0.43,0.69,34.87,XR,ATH,FINANCE
91,ZYDUSLIFE,0.91,0.06,35.55,35.63,74547.0,122.0,209696.0,1286.17,-13.06,61.0,H-MC,3.53,120.0,0.00,1.38,10.25,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES
55,MASFIN,0.19,6.52,14.12,21.57,14737.0,6390.0,104370.0,397.04,-8.31,70.0,H-SC,4.39,167.0,0.43,0.69,34.87,XR,ATH,FINANCE
91,ZYDUSLIFE,0.91,0.06,35.55,35.63,74547.0,122.0,209696.0,1286.17,-13.06,61.0,H-MC,3.53,120.0,0.00,1.38,10.25,AR,ATH,PHARMA
73,SONACOMS,-0.17,-0.07,39.19,39.09,39617.0,-70.0,101089.0,804.02,-20.87,54.0,M-MC,19.75,193.0,-0.00,0.66,43.00,AR,ATH,AUTO
42,INDIAMART,-0.29,-10.41,130.74,106.72,144468.0,-12836.0,110500.0,4810.62,-59.57,46.0,H-SC,9.20,140.0,-0.09,0.73,6.16,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.10,-22.36,56.50,21.51,106127.0,-54089.0,187835.0,1872.35,-18.53,32.0,X-LC,12.34,8.0,-0.51,1.23,1.10,X40,ATH,IT
45,INFY,0.76,-20.25,68.33,34.24,170504.0,-63358.0,249530.0,1972.00,-37.23,37.0,X-LC,15.85,3.0,-0.37,1.64,1.68,X40,NTT,IT
79,TCS,-0.62,-29.94,80.66,26.57,261805.0,-138695.0,324578.0,4311.59,-40.68,38.0,X-LC,14.25,2.0,-0.53,2.13,1.30,X40,ATH,IT
28,GODREJCP,-0.08,-7.30,42.53,32.12,58590.0,-10853.0,137761.0,1476.34,-2.48,40.0,X-LC,6.36,32.0,-0.19,0.90,5.18,X40N,ATH,FMCG
88,VOLTAS,-2.20,4.35,39.14,45.20,78313.0,8343.0,200085.0,1856.00,19.51,41.0,X-MC,2.39,79.0,0.11,1.31,9.67,XY25,NTT,AC

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-2.20,4.35,39.14,45.20,78313.0,8343.0,200085.0,1856.00,19.51,41.0,X-MC,2.39,79.0,0.11,1.31,9.67,XY25,NTT,AC
84,UNITDSPR,-0.06,-6.05,28.54,20.77,62785.0,-14156.0,219988.0,1644.00,-16.64,42.0,X-MC,2.52,64.0,-0.23,1.44,4.94,X40N,NTT,BREWERIES
65,RELIANCE,-0.38,-8.16,36.44,25.30,67254.0,-16403.0,184560.0,1952.00,-10.42,58.0,X-LC,3.39,21.0,-0.24,1.21,9.67,XY25,BTT,REFINERIES
39,ICICIGI,-0.26,-2.25,22.08,19.34,43191.0,-4497.0,195612.0,2252.93,-17.87,59.0,X-MC,4.56,66.0,-0.10,1.28,9.25,X40,ATH,INSURANCE
19,COLPAL,0.30,-17.47,71.46,41.51,155325.0,-46005.0,217360.0,3726.84,-0.02,63.0,X-MC,5.13,62.0,-0.30,1.43,21.52,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.10,-22.36,56.50,21.51,106127.0,-54089.0,187835.0,1872.35,-18.53,32.0,X-LC,12.34,8.0,-0.51,1.23,1.10,X40,ATH,IT
79,TCS,-0.62,-29.94,80.66,26.57,261805.0,-138695.0,324578.0,4311.59,-40.68,38.0,X-LC,14.25,2.0,-0.53,2.13,1.30,X40,ATH,IT
45,INFY,0.76,-20.25,68.33,34.24,170504.0,-63358.0,249530.0,1972.00,-37.23,37.0,X-LC,15.85,3.0,-0.37,1.64,1.68,X40,NTT,IT
84,UNITDSPR,-0.06,-6.05,28.54,20.77,62785.0,-14156.0,219988.0,1644.00,-16.64,42.0,X-MC,2.52,64.0,-0.23,1.44,4.94,X40N,NTT,BREWERIES
28,GODREJCP,-0.08,-7.30,42.53,32.12,58590.0,-10853.0,137761.0,1476.34,-2.48,40.0,X-LC,6.36,32.0,-0.19,0.90,5.18,X40N,ATH,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.92,-60.10,281.76,52.31,163176.0,-87247.0,57913.0,1176.00,-57.51,56.0,X-SC,24.40,92.0,-0.53,0.38,29.49,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.28,-53.63,191.58,35.20,114306.0,-69005.0,59665.0,2096.00,-21.73,48.0,X-SC,26.14,91.0,-0.60,0.39,18.33,X40,NTT,FOOTWEAR
60,QUESS,0.27,-7.94,88.89,73.90,87395.0,-8475.0,98318.0,424.00,-50.41,74.0,X-SC,13.56,80.0,-0.10,0.65,34.03,XY24,NTT,MISC
28,GODREJCP,-0.08,-7.30,42.53,32.12,58590.0,-10853.0,137761.0,1476.34,-2.48,40.0,X-LC,6.36,32.0,-0.19,0.90,5.18,X40N,ATH,FMCG
51,KOTAKBANK,-0.74,0.63,20.35,21.11,28356.0,870.0,139342.0,453.24,-13.74,49.0,X-LC,7.48,12.0,0.03,0.91,6.56,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.00,-19.03,47.04,19.06,129562.0,-64736.0,275430.0,452.00,-55.52,50.0,X-LC,15.57,1.0,-0.50,1.81,6.85,X40,NTT,FMCG
79,TCS,-0.62,-29.94,80.66,26.57,261805.0,-138695.0,324578.0,4311.59,-40.68,38.0,X-LC,14.25,2.0,-0.53,2.13,1.30,X40,ATH,IT
45,INFY,0.76,-20.25,68.33,34.24,170504.0,-63358.0,249530.0,1972.00,-37.23,37.0,X-LC,15.85,3.0,-0.37,1.64,1.68,X40,NTT,IT
81,TMPV,-1.04,-19.08,68.78,36.58,198055.0,-67886.0,287955.0,600.00,-83.62,56.0,X-LC,5.17,4.0,-0.34,1.89,20.02,XY24,NTT,AUTO
59,PIDILITIND,2.34,5.19,12.53,18.37,18598.0,7320.0,148430.0,1670.26,-26.30,69.0,X-LC,5.41,5.0,0.39,0.97,16.54,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-0.21,-30.24,90.49,32.89,48740.0,-23344.0,53862.0,1800.00,-353.50,67.0,L-MC,5.83,258.0,-0.48,0.35,32.58,XR,NTT,BANKS
73,SONACOMS,-0.17,-0.07,39.19,39.09,39617.0,-70.0,101089.0,804.02,-20.87,54.0,M-MC,19.75,193.0,-0.00,0.66,43.00,AR,ATH,AUTO
72,SIS,0.59,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.00,2430.57,76.0,H-SC,10.74,168.0,-0.27,0.67,51.85,OX40N,NTT,MISC
55,MASFIN,0.19,6.52,14.12,21.57,14737.0,6390.0,104370.0,397.04,-8.31,70.0,H-SC,4.39,167.0,0.43,0.69,34.87,XR,ATH,FINANCE
5,ATULAUTO,-0.42,-15.27,71.81,45.57,119941.0,-30107.0,167025.0,844.00,3618.92,59.0,M-SC,6.28,248.0,-0.25,1.10,28.53,XY24,NTT,AUTO

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,0.59,-8.02,31.84,21.26,32518.0,-8904.0,102128.0,528.00,2430.57,76.0,H-SC,10.74,168.0,-0.27,0.67,51.85,OX40N,NTT,MISC
25,FINCABLES,5.94,45.98,42.43,107.91,91448.0,67883.0,215527.0,1641.55,31.41,83.0,M-SC,18.65,220.0,0.74,1.41,62.15,OX40N,ATH,CABLES
68,SATIN,0.39,13.37,33.93,51.83,106273.0,36928.0,313212.0,274.00,1.18,79.0,H-SC,16.66,159.0,0.35,2.06,52.58,XY24,NTT,FINANCE
77,TANLA,-1.06,-35.82,238.50,117.25,414458.0,-96984.0,173777.0,1922.32,-35.11,66.0,H-SC,16.89,147.0,-0.23,1.14,52.15,AR,ATH,IT
3,ALKYLAMINE,0.06,-26.06,161.87,93.63,120839.0,-26311.0,74652.0,4546.37,-20.73,71.0,H-SC,17.79,142.0,-0.22,0.49,40.96,SR,ATH,CHEMICALS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.03
1     25       42.33
2     50       72.61

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.03
LC    31.29
MC    25.69
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.41
X40      25.33
X40N     16.71
XR        9.19
OX40N     7.02
XY25      6.75
AR        6.74
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.13
H-SC    22.47
X-MC    20.78
M-SC    10.20
X-SC     9.81
H-MC     2.59
M-MC     1.97
H-LC     1.26
M-LC     0.90
L-SC     0.55
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.31        -13.40   53.40
FINANCE             10.84        -11.83   60.47
IT                  10.36        -42.61  114.41
MISC                 7.21        -22.39   75.56
AUTO                 6.62         -8.60   49.32
BANKS                5.66         -5.29   53.97
INSURANCE            5.34         -1.81   36.46
PAINTS               5.33        -21.29   42.35
PHARMA               4.84         -0.65   33.00
ELECTRICAL           4.00        -16.03   57.33
CHEMICALS            2.13        -25.05   99.58
HEALTHCARE           1.97        -19.51   50.69
AC                   1.84        -14.02   44.93
TRAVEL               1.72        -70.36  155.66
DURABLES             1.71        -47.85   83.82
APPARELS             1.71         -3.20   38.41
FOOTWEAR             1.69        -70.94  139.49
BREWERIES            1.44         -6.43   28.54
CABLES               1.41         31.50   42.43
REALTY               1.39         -4.72   21.93
CERAMICS             1.31        -53.15   99.67
ENGINEERING          1.26        -26.42   84.24
REFINERIES           1.21         -8.89   36.44
CEMENT               1.13        -55.94  172.59
JEWELLERY            1.07        -95.97  164.06
ENTERTAINMENT        0.74        -73.04  176.24
TEXTILES             0.43        -39.78   79.64
HOTELS               0.34       -122.08  200.41

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3423156.0     21
X40       1844539.0     19
XR        1284244.0     13
X40N      1179096.0     13
AR        1158531.0      9
OX40N      719134.0     10
XY25       411789.0      5
SR         287936.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3365903.0     24
X-LC        1861483.0     21
X-MC        1567474.0     15
M-SC        1361771.0     14
X-SC        1309981.0      9
H-MC         303433.0      2
L-SC         207159.0      2
M-LC         154670.0      1
M-MC          85989.0      2
L-MC          48740.0      1
H-LC          41822.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1063821.0      6
X-LC       X40       1001232.0     10
H-SC       AR         927585.0      5
M-SC       XY24       820529.0      6
X-SC       XY24       766722.0      4
H-SC       XR         765316.0      7
X-MC       X40        639034.0      7
           X40N       485100.0      4
X-LC       X40N       355010.0      6
X-SC       X40N       338986.0      3
X-LC       XY24       333496.0      2
H-SC       OX40N      321245.0      4
M-SC       OX40N      293200.0      5
H-SC       SR         287936.0      2
X-MC       XY25       233638.0      2
H-MC       XY24       228886.0      1
X-MC       XY24       209702.0      2
X-SC       X40        204273.0      2
M-SC       XR         173082.0      2
M-LC       XR         154670.0      1
X-LC       XY25       131779.0      2
L-SC       OX40N      104689.0      1
           XR         102470.0      1
M-SC       AR          74960.0      1
H-MC       AR          74547.0      1
L-MC       XR          48740.0      1
M-MC       XY25        46372.0      1
H-LC       AR          41822.0      1
X-LC       XR          39966.0      1
M-MC       AR          39617.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 37.0 seconds