<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-03-11 09:40:38
-------------------
qualified stocks: 86
with latest results: 26
still star stocks: 15
-------------------
Initial Investment:  1.36 C
CY Investment:  1.62 C
Reserve:  66.25 K
Current:  1.38 C
-------------------
Today PnL: 85.38 K (0.62%)
Current PnL: -38.69 L (-23.81%)
CY Booked + Current PnL: -23.01 L (-14.16%)
-------------------
Total profit:  1.21 L
Total loss:  -39.89 L
-------------------
Total Booked + Current PnL: 3.97 L (2.93%)
Total Booked PnL: 42.66 L (31.48%)
Curr Year Booked PnL: 15.68 L (11.34%)
Prev Year Booked PnL: 26.98 L (19.91%)
===================
Est FTT:  2.47 C
Est FTT PnL: 1.09 C (78.88%)
===================
Deployed:  1.36 C
Current:  1.38 C
CAGR/XIRR %: 1.01%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.67,9.80,7.17,17.67,11845.0,14744.0,165205.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.24,1.20,28.29,XY25,ATH,MINING
50,MASFIN,-0.06,-5.34,28.43,21.57,26367.0,-5235.0,92745.0,397.04,-18.25,42.0,H-SC,4.67,167.0,-0.20,0.67,29.41,XR,ATH,FINANCE
77,TTKPRESTIG,13.74,-28.37,39.73,0.09,28680.0,-28589.0,72188.0,770.00,67.56,55.0,M-SC,15.03,250.0,-1.00,0.52,21.97,OX40N,NTT,DURABLES
37,ICICIGI,-0.97,-0.89,20.41,19.34,40478.0,-1783.0,198326.0,2252.93,-16.65,44.0,X-MC,1.67,66.0,-0.04,1.44,13.11,X40,ATH,INSURANCE
78,UNITDSPR,-0.04,3.33,16.88,20.77,40839.0,7791.0,241935.0,1644.00,-8.32,55.0,X-MC,1.55,64.0,0.19,1.76,10.26,X40N,NTT,BREWERIES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
77,TTKPRESTIG,13.74,-28.37,39.73,0.09,28680.0,-28589.0,72188.0,770.00,67.56,55.0,M-SC,15.03,250.0,-1.00,0.52,21.97,OX40N,NTT,DURABLES
31,HAPPSTMNDS,10.46,-44.78,234.74,84.85,166140.0,-57389.0,70776.0,1480.71,-34.35,70.0,H-SC,28.36,152.0,-0.35,0.51,31.07,AR,ATH,IT
70,SYMPHONY,5.04,-36.25,56.81,-0.03,61981.0,-62038.0,109103.0,1306.00,-48.74,50.0,M-SC,13.17,205.0,-1.00,0.79,10.33,OX40N,NTT,DURABLES
67,SONACOMS,4.43,-7.55,50.45,39.09,47181.0,-7639.0,93520.0,804.02,-26.68,57.0,M-MC,10.32,193.0,-0.16,0.68,32.30,AR,ATH,AUTO
55,RAJESHEXPO,3.86,-78.09,356.79,0.07,107219.0,-107126.0,30051.0,518.00,1001.01,22.0,L-SC,18.89,268.0,-1.00,0.22,3.86,OX40N,NTT,JEWELLERY

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
21,COLPAL,-3.95,-19.83,76.50,41.51,161530.0,-52215.0,211150.0,3726.84,-2.94,42.0,X-MC,4.13,62.0,-0.32,1.53,3.17,XY25,ATH,FMCG
37,ICICIGI,-0.97,-0.89,20.41,19.34,40478.0,-1783.0,198326.0,2252.93,-16.65,44.0,X-MC,1.67,66.0,-0.04,1.44,13.11,X40,ATH,INSURANCE
24,DIXON,-0.83,-21.19,75.02,37.92,154183.0,-55275.0,205523.0,18931.72,-66.52,50.0,X-MC,25.55,54.0,-0.36,1.49,10.33,X40N,ATH,IT
53,PGHH,-0.80,-19.66,64.32,32.01,110332.0,-41984.0,171536.0,17616.87,-45.65,24.0,X-MC,11.30,57.0,-0.38,1.25,1.10,X40,ATH,FMCG
22,DABUR,-0.75,-6.68,53.99,43.70,124981.0,-16578.0,231490.0,735.00,-15.22,36.0,X-MC,1.01,70.0,-0.13,1.68,7.36,XY24,BTT,FMCG

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.54,17.03,77.66,107.91,134187.0,25144.0,172788.0,1641.55,5.53,62.0,M-SC,7.80,220.0,0.19,1.26,29.99,OX40N,ATH,CABLES
77,TTKPRESTIG,13.74,-28.37,39.73,0.09,28680.0,-28589.0,72188.0,770.00,67.56,55.0,M-SC,15.03,250.0,-1.00,0.52,21.97,OX40N,NTT,DURABLES
66,SIS,0.93,-32.71,80.20,21.26,59921.0,-36317.0,74715.0,528.00,1751.30,38.0,H-SC,10.00,168.0,-0.61,0.54,3.00,OX40N,NTT,MISC
70,SYMPHONY,5.04,-36.25,56.81,-0.03,61981.0,-62038.0,109103.0,1306.00,-48.74,50.0,M-SC,13.17,205.0,-1.00,0.79,10.33,OX40N,NTT,DURABLES
72,TATAELXSI,0.54,-36.88,109.16,32.03,90843.0,-48615.0,83220.0,9161.00,-21.03,31.0,H-SC,16.55,158.0,-0.54,0.60,1.77,OX40N,NTT,IT

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COALINDIA,0.67,9.80,7.17,17.67,11845.0,14744.0,165205.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.24,1.20,28.29,XY25,ATH,MINING
27,FINCABLES,-0.54,17.03,77.66,107.91,134187.0,25144.0,172788.0,1641.55,5.53,62.0,M-SC,7.80,220.0,0.19,1.26,29.99,OX40N,ATH,CABLES
1,ABB,1.16,15.53,26.00,45.57,78587.0,40637.0,302256.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.52,2.20,34.22,AR,NTT,ELECTRICAL

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
1,ABB,1.16,15.53,26.00,45.57,78587.0,40637.0,302256.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.52,2.20,34.22,AR,NTT,ELECTRICAL
27,FINCABLES,-0.54,17.03,77.66,107.91,134187.0,25144.0,172788.0,1641.55,5.53,62.0,M-SC,7.80,220.0,0.19,1.26,29.99,OX40N,ATH,CABLES
85,ZYDUSLIFE,0.80,-1.88,38.22,35.63,78596.0,-3934.0,205640.0,1286.17,-14.41,57.0,H-MC,5.03,120.0,-0.05,1.49,14.48,AR,ATH,PHARMA
40,INDIAMART,-0.17,-6.50,121.10,106.72,139649.0,-8019.0,115317.0,4810.62,-57.81,50.0,H-SC,9.10,140.0,-0.06,0.84,15.36,AR,ATH,MISC
67,SONACOMS,4.43,-7.55,50.45,39.09,47181.0,-7639.0,93520.0,804.02,-26.68,57.0,M-MC,10.32,193.0,-0.16,0.68,32.30,AR,ATH,AUTO

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.54,-59.90,279.84,52.31,162881.0,-86955.0,58205.0,1176.00,-57.31,22.0,X-SC,18.68,92.0,-0.53,0.42,0.54,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.85,-53.36,189.90,35.20,113957.0,-68661.0,60009.0,2096.00,-21.30,23.0,X-SC,25.46,91.0,-0.60,0.44,0.85,X40,NTT,FOOTWEAR
73,TCS,-0.74,-26.77,72.84,26.57,247111.0,-124021.0,339252.0,4311.59,-38.05,23.0,X-LC,13.78,2.0,-0.50,2.47,0.00,X40,ATH,IT
53,PGHH,-0.80,-19.66,64.32,32.01,110332.0,-41984.0,171536.0,17616.87,-45.65,24.0,X-MC,11.30,57.0,-0.38,1.25,1.10,X40,ATH,FMCG
8,AWL,0.98,-37.75,168.30,67.02,373298.0,-134504.0,221805.0,485.00,-66.49,26.0,X-SC,22.69,81.0,-0.36,1.61,2.94,XY24,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
22,DABUR,-0.75,-6.68,53.99,43.70,124981.0,-16578.0,231490.0,735.00,-15.22,36.0,X-MC,1.01,70.0,-0.13,1.68,7.36,XY24,BTT,FMCG
78,UNITDSPR,-0.04,3.33,16.88,20.77,40839.0,7791.0,241935.0,1644.00,-8.32,55.0,X-MC,1.55,64.0,0.19,1.76,10.26,X40N,NTT,BREWERIES
37,ICICIGI,-0.97,-0.89,20.41,19.34,40478.0,-1783.0,198326.0,2252.93,-16.65,44.0,X-MC,1.67,66.0,-0.04,1.44,13.11,X40,ATH,INSURANCE
75,TMPV,-0.35,-21.70,74.42,36.58,207364.0,-77201.0,278640.0,600.00,-83.62,39.0,X-LC,1.92,4.0,-0.37,2.03,3.61,XY24,NTT,AUTO
59,RELIANCE,-0.23,-9.78,38.88,25.30,70493.0,-19653.0,181310.0,1952.00,-11.96,47.0,X-LC,2.42,21.0,-0.28,1.32,21.05,XY25,BTT,REFINERIES

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,TCS,-0.74,-26.77,72.84,26.57,247111.0,-124021.0,339252.0,4311.59,-38.05,23.0,X-LC,13.78,2.0,-0.50,2.47,0.00,X40,ATH,IT
10,BAJAJHLDNG,0.16,-7.86,40.24,29.22,70494.0,-14940.0,175185.0,14451.52,-14.55,33.0,X-LC,11.98,28.0,-0.21,1.27,0.54,X40,ATH,FINANCE
58,RELAXO,0.54,-59.90,279.84,52.31,162881.0,-86955.0,58205.0,1176.00,-57.31,22.0,X-SC,18.68,92.0,-0.53,0.42,0.54,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.85,-53.36,189.90,35.20,113957.0,-68661.0,60009.0,2096.00,-21.30,23.0,X-SC,25.46,91.0,-0.60,0.44,0.85,X40,NTT,FOOTWEAR
45,ITC,0.00,-18.60,46.25,19.06,128070.0,-63257.0,276909.0,452.00,-55.52,38.0,X-LC,17.09,1.0,-0.49,2.01,1.00,X40,NTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
58,RELAXO,0.54,-59.90,279.84,52.31,162881.0,-86955.0,58205.0,1176.00,-57.31,22.0,X-SC,18.68,92.0,-0.53,0.42,0.54,X40N,NTT,FOOTWEAR
12,BATAINDIA,0.85,-53.36,189.90,35.20,113957.0,-68661.0,60009.0,2096.00,-21.30,23.0,X-SC,25.46,91.0,-0.60,0.44,0.85,X40,NTT,FOOTWEAR
54,QUESS,2.08,-20.72,119.35,73.90,101048.0,-22128.0,84665.0,424.00,-57.58,44.0,X-SC,17.92,80.0,-0.22,0.62,4.44,XY24,NTT,MISC
36,HONAUT,0.39,-19.92,88.95,51.31,137361.0,-38413.0,154425.0,58357.33,-33.36,45.0,X-SC,13.61,90.0,-0.28,1.12,3.99,X40N,ATH,ELECTRICAL
2,ABBOTINDIA,0.67,-9.46,30.40,18.07,49230.0,-16915.0,161940.0,35195.00,-23.01,49.0,X-MC,11.15,58.0,-0.34,1.18,2.66,X40,ATH,PHARMA

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
45,ITC,0.00,-18.60,46.25,19.06,128070.0,-63257.0,276909.0,452.00,-55.52,38.0,X-LC,17.09,1.0,-0.49,2.01,1.00,X40,NTT,FMCG
73,TCS,-0.74,-26.77,72.84,26.57,247111.0,-124021.0,339252.0,4311.59,-38.05,23.0,X-LC,13.78,2.0,-0.50,2.47,0.00,X40,ATH,IT
43,INFY,-0.46,-12.20,52.90,34.24,145319.0,-38182.0,274706.0,1972.00,-31.06,28.0,X-LC,12.08,3.0,-0.26,2.00,1.11,X40,NTT,IT
75,TMPV,-0.35,-21.70,74.42,36.58,207364.0,-77201.0,278640.0,600.00,-83.62,39.0,X-LC,1.92,4.0,-0.37,2.03,3.61,XY24,NTT,AUTO
34,HCLTECH,-0.20,-11.82,40.43,23.83,86250.0,-28592.0,213332.0,1908.19,-7.36,28.0,X-LC,9.47,8.0,-0.33,1.55,2.35,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
42,INDUSINDBK,-0.08,-33.70,100.45,32.89,51416.0,-26020.0,51186.0,1800.00,-340.90,43.0,L-MC,11.27,258.0,-0.51,0.37,40.96,XR,NTT,BANKS
67,SONACOMS,4.43,-7.55,50.45,39.09,47181.0,-7639.0,93520.0,804.02,-26.68,57.0,M-MC,10.32,193.0,-0.16,0.68,32.30,AR,ATH,AUTO
19,COALINDIA,0.67,9.80,7.17,17.67,11845.0,14744.0,165205.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.24,1.20,28.29,XY25,ATH,MINING
27,FINCABLES,-0.54,17.03,77.66,107.91,134187.0,25144.0,172788.0,1641.55,5.53,62.0,M-SC,7.80,220.0,0.19,1.26,29.99,OX40N,ATH,CABLES
82,VOLTAS,3.14,16.91,24.20,45.20,54247.0,32418.0,224160.0,1856.00,33.88,52.0,X-MC,9.72,79.0,0.60,1.63,24.85,XY25,NTT,AC

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
27,FINCABLES,-0.54,17.03,77.66,107.91,134187.0,25144.0,172788.0,1641.55,5.53,62.0,M-SC,7.80,220.0,0.19,1.26,29.99,OX40N,ATH,CABLES
31,HAPPSTMNDS,10.46,-44.78,234.74,84.85,166140.0,-57389.0,70776.0,1480.71,-34.35,70.0,H-SC,28.36,152.0,-0.35,0.51,31.07,AR,ATH,IT
1,ABB,1.16,15.53,26.00,45.57,78587.0,40637.0,302256.0,7934.00,-25.80,66.0,H-MC,10.07,125.0,0.52,2.20,34.22,AR,NTT,ELECTRICAL
11,BANDHANBNK,-0.30,-12.58,120.12,92.42,292498.0,-35054.0,243505.0,400.00,109.05,61.0,H-SC,10.01,174.0,-0.12,1.77,34.14,XY24,NTT,BANKS
19,COALINDIA,0.67,9.80,7.17,17.67,11845.0,14744.0,165205.0,478.51,31.99,61.0,L-LC,11.52,185.0,1.24,1.20,28.29,XY25,ATH,MINING

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       20.47
1     25       45.27
2     50       77.67

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    44.69
MC    30.44
LC    24.82
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.20
X40      23.69
X40N     15.18
AR        9.24
XY25      8.61
XR        8.32
OX40N     6.94
SR        0.77
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-MC    23.06
H-SC    21.70
X-LC    21.39
X-SC    12.17
M-SC    10.23
H-MC     4.98
M-MC     2.03
H-LC     1.21
L-LC     1.20
M-LC     1.02
L-SC     0.59
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.19        -19.43   61.84
FINANCE             12.80        -21.84   71.49
IT                  11.70        -39.72  110.82
MISC                 7.00        -39.34   99.87
ELECTRICAL           6.66         -5.75   46.24
PAINTS               5.20        -37.64   61.54
INSURANCE            4.64         -6.15   42.47
PHARMA               4.12         -3.72   36.37
AUTO                 3.79        -25.65   75.50
BANKS                3.15        -23.29   97.99
AC                   2.18         -6.75   35.70
HEALTHCARE           1.98        -31.72   66.09
DURABLES             1.90        -47.17   82.97
FOOTWEAR             1.84        -74.72  144.77
TRAVEL               1.81        -78.82  168.36
BREWERIES            1.76          3.22   16.88
APPARELS             1.62        -20.43   61.52
REALTY               1.45        -10.85   29.06
CERAMICS             1.33        -68.09  119.16
REFINERIES           1.32        -10.84   38.88
CEMENT               1.29        -50.73  163.49
CABLES               1.26         14.55   77.66
MINING               1.20          8.92    7.17
JEWELLERY            1.13       -106.43  178.15
ENGINEERING          1.10        -59.32  132.19
CHEMICALS            0.97        -97.79  259.15
ENTERTAINMENT        0.77        -84.43  194.42
TEXTILES             0.42        -59.34  104.78
HOTELS               0.37       -120.75  198.62

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3853687.0     21
X40       1614522.0     15
XR        1344587.0     12
AR        1300438.0     10
X40N      1211051.0     10
OX40N      836106.0     10
XY25       431950.0      6
SR         312068.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3801537.0     24
X-MC        1560945.0     15
X-LC        1531621.0     12
M-SC        1511519.0     14
X-SC        1508403.0     10
H-MC         392741.0      3
L-SC         209383.0      2
M-LC         151033.0      1
M-MC         106519.0      2
H-LC          67447.0      1
L-MC          51416.0      1
L-LC          11845.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1304613.0      6
           AR         952114.0      5
M-SC       XY24       898887.0      6
H-SC       XR         851948.0      7
X-SC       XY24       820950.0      4
X-LC       X40        797130.0      6
X-MC       X40        617612.0      7
           X40N       488660.0      4
X-SC       X40N       487673.0      4
H-SC       OX40N      380794.0      4
X-LC       XY24       354783.0      2
M-SC       OX40N      348093.0      5
H-SC       SR         312068.0      2
X-MC       XY24       238896.0      2
H-MC       XY24       235558.0      1
X-LC       X40N       234718.0      2
X-MC       XY25       215777.0      2
X-SC       X40        199780.0      2
M-SC       XR         188026.0      2
H-MC       AR         157183.0      2
M-LC       XR         151033.0      1
X-LC       XY25       144990.0      2
L-SC       OX40N      107219.0      1
           XR         102164.0      1
M-SC       AR          76513.0      1
H-LC       AR          67447.0      1
M-MC       XY25        59338.0      1
L-MC       XR          51416.0      1
M-MC       AR          47181.0      1
L-LC       XY25        11845.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 30.0 seconds