<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-12 13:55:04
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.60 C
-------------------
Today PnL: -95.67 K (-0.59%)
Current PnL: -31.72 L (-16.79%)
CY Booked + Current PnL: -27.50 L (-14.55%)
-------------------
Total profit:  4.32 L
Total loss:  -36.04 L
-------------------
Total Booked + Current PnL: 15.37 L (10.53%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.63%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.06 C (66.28%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.29%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-2.54,20.09,5.86,27.12,12422.0,35457.0,211974.0,1486.00,16.36,53.0,X-SC,16.39,87.0,2.85,1.34,46.06,XY24,NTT,HEALTHCARE
87,ZYDUSLIFE,0.62,26.37,7.23,35.51,19148.0,55272.0,264846.0,1285.01,9.91,70.0,H-MC,15.96,120.0,2.89,1.67,39.38,AR,ATH,PHARMA
80,UNITDSPR,-1.72,11.81,8.01,20.77,20970.0,27657.0,261801.0,1644.00,-0.77,65.0,X-MC,8.55,64.0,1.32,1.66,25.85,X40N,NTT,BREWERIES
69,SIS,0.59,1.09,19.96,21.26,22403.0,1206.0,112238.0,528.00,2681.35,58.0,H-SC,22.68,168.0,0.05,0.71,66.88,OX40N,NTT,MISC
79,TTKPRESTIG,-0.35,-23.58,30.97,0.09,23852.0,-23762.0,77015.0,770.00,78.66,38.0,M-SC,12.12,250.0,-1.00,0.49,38.62,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.37,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
11,BERGEPAINT,4.74,3.26,21.36,25.32,56848.0,8393.0,266142.0,680.00,-2.33,68.0,X-MC,2.92,68.0,0.15,1.68,39.56,XY24,NTT,PAINTS
58,QUESS,2.73,36.60,27.31,73.90,39839.0,39083.0,145876.0,424.00,-26.72,68.0,X-SC,40.63,80.0,0.98,0.92,100.78,XY24,NTT,MISC
66,SFL,2.25,-31.67,85.31,26.63,152859.0,-83037.0,179181.0,1287.00,35.77,40.0,M-SC,21.90,242.0,-0.54,1.13,49.54,XY24,NTT,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-10.74,-16.77,60.57,33.64,125793.0,-41855.0,207682.0,1469.04,-13.87,23.0,X-LC,5.04,32.0,-0.33,1.31,0.00,X40N,ATH,FMCG
75,TCS,-5.06,-31.83,82.20,24.20,259581.0,-147481.0,315792.0,4230.71,-42.31,50.0,X-LC,15.22,2.0,-0.57,2.00,17.76,X40,ATH,IT
29,GREENPANEL,-3.34,-52.70,202.60,43.14,175452.0,-96478.0,86600.0,537.00,93.80,33.0,M-SC,10.45,225.0,-0.55,0.55,4.30,XY24,NTT,MISC
73,TANLA,-3.26,-32.58,222.24,117.25,405686.0,-88217.0,182544.0,1922.32,-31.83,53.0,H-SC,15.14,147.0,-0.22,1.15,59.82,AR,ATH,IT
77,TMPV,-3.19,-19.94,78.31,42.75,260878.0,-82972.0,333135.0,600.00,-83.62,45.0,X-LC,5.06,4.0,-0.32,2.11,14.55,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
69,SIS,0.59,1.09,19.96,21.26,22403.0,1206.0,112238.0,528.00,2681.35,58.0,H-SC,22.68,168.0,0.05,0.71,66.88,OX40N,NTT,MISC
43,INDIGOPNTS,-0.47,-20.42,25.69,0.02,35685.0,-35654.0,138905.0,1408.00,112.05,60.0,M-SC,5.83,222.0,-1.00,0.88,57.60,OX40N,NTT,PAINTS
16,CERA,-1.56,-22.97,60.84,23.89,82434.0,-40410.0,135493.0,9475.00,-25.78,38.0,H-SC,12.35,153.0,-0.49,0.86,31.71,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-0.35,-23.58,30.97,0.09,23852.0,-23762.0,77015.0,770.00,78.66,38.0,M-SC,12.12,250.0,-1.00,0.49,38.62,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.62,26.37,7.23,35.51,19148.0,55272.0,264846.0,1285.01,9.91,70.0,H-MC,15.96,120.0,2.89,1.67,39.38,AR,ATH,PHARMA
55,MEDANTA,-2.54,20.09,5.86,27.12,12422.0,35457.0,211974.0,1486.00,16.36,53.0,X-SC,16.39,87.0,2.85,1.34,46.06,XY24,NTT,HEALTHCARE
58,QUESS,2.73,36.60,27.31,73.90,39839.0,39083.0,145876.0,424.00,-26.72,68.0,X-SC,40.63,80.0,0.98,0.92,100.78,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.59,1.09,19.96,21.26,22403.0,1206.0,112238.0,528.00,2681.35,58.0,H-SC,22.68,168.0,0.05,0.71,66.88,OX40N,NTT,MISC
70,STARHEALTH,-0.15,12.97,30.35,47.26,96388.0,36464.0,317587.0,761.00,78.26,50.0,H-SC,16.88,173.0,0.38,2.01,37.32,XY24,NTT,INSURANCE
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.62,26.37,7.23,35.51,19148.0,55272.0,264846.0,1285.01,9.91,70.0,H-MC,15.96,120.0,2.89,1.67,39.38,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.62,26.37,7.23,35.51,19148.0,55272.0,264846.0,1285.01,9.91,70.0,H-MC,15.96,120.0,2.89,1.67,39.38,AR,ATH,PHARMA
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
69,SIS,0.59,1.09,19.96,21.26,22403.0,1206.0,112238.0,528.00,2681.35,58.0,H-SC,22.68,168.0,0.05,0.71,66.88,OX40N,NTT,MISC
3,ALKYLAMINE,-2.13,-18.82,137.19,92.54,112438.0,-19005.0,81958.0,4520.85,-13.07,56.0,H-SC,13.82,142.0,-0.17,0.52,55.63,SR,ATH,CHEMICALS
42,INDIAMART,0.03,-23.30,161.95,100.92,153205.0,-28736.0,94600.0,4675.60,-65.43,42.0,H-SC,12.73,140.0,-0.19,0.60,2.40,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-10.74,-16.77,60.57,33.64,125793.0,-41855.0,207682.0,1469.04,-13.87,23.0,X-LC,5.04,32.0,-0.33,1.31,0.00,X40N,ATH,FMCG
34,HDFCBANK,-0.80,-11.68,48.38,31.05,125250.0,-34232.0,258888.0,1073.00,-26.46,32.0,X-LC,11.68,26.0,-0.27,1.64,0.49,X40,BTT,BANKS
57,PGHH,-0.09,-36.70,108.55,32.01,146716.0,-78360.0,135160.0,17616.87,-57.19,34.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.45,-8.49,52.06,39.15,119451.0,-21289.0,229448.0,811.41,-31.91,36.0,X-LC,16.25,31.0,-0.18,1.45,0.00,X40,ATH,INSURANCE
83,VBL,-0.32,-11.73,53.68,35.66,166721.0,-41261.0,310583.0,669.42,-22.34,36.0,X-LC,7.47,13.0,-0.25,1.96,14.35,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.34,-24.01,84.06,39.86,168221.0,-63245.0,200120.0,3683.41,-8.09,42.0,X-MC,1.52,62.0,-0.38,1.27,13.20,XY25,ATH,FMCG
23,DMART,-0.25,-1.40,33.29,31.42,102337.0,-4378.0,307412.0,5391.45,-18.00,52.0,X-LC,2.90,14.0,-0.04,1.94,10.93,X40N,ATH,FMCG
11,BERGEPAINT,4.74,3.26,21.36,25.32,56848.0,8393.0,266142.0,680.00,-2.33,68.0,X-MC,2.92,68.0,0.15,1.68,39.56,XY24,NTT,PAINTS
8,BAJAJHLDNG,-1.00,2.73,24.83,28.24,65304.0,7000.0,263005.0,14274.15,-5.41,63.0,X-LC,3.03,28.0,0.11,1.66,32.37,X40,ATH,FINANCE
50,KOTAKBANK,-0.36,2.90,15.57,18.92,38403.0,6943.0,246645.0,452.46,-10.27,52.0,X-LC,3.13,12.0,0.18,1.56,10.97,X40,ATH,BANKS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.45,-8.49,52.06,39.15,119451.0,-21289.0,229448.0,811.41,-31.91,36.0,X-LC,16.25,31.0,-0.18,1.45,0.00,X40,ATH,INSURANCE
28,GODREJCP,-10.74,-16.77,60.57,33.64,125793.0,-41855.0,207682.0,1469.04,-13.87,23.0,X-LC,5.04,32.0,-0.33,1.31,0.00,X40N,ATH,FMCG
57,PGHH,-0.09,-36.70,108.55,32.01,146716.0,-78360.0,135160.0,17616.87,-57.19,34.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
20,DABUR,-1.54,-20.56,80.90,43.70,159418.0,-51012.0,197056.0,735.00,-27.96,37.0,X-MC,9.48,70.0,-0.32,1.25,0.27,XY24,BTT,FMCG
34,HDFCBANK,-0.80,-11.68,48.38,31.05,125250.0,-34232.0,258888.0,1073.00,-26.46,32.0,X-LC,11.68,26.0,-0.27,1.64,0.49,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.33,-54.26,195.57,35.20,115111.0,-69811.0,58859.0,2096.00,-22.89,55.0,X-SC,13.29,91.0,-0.61,0.37,18.25,X40,NTT,FOOTWEAR
62,RELAXO,-1.35,-46.13,182.73,52.31,142893.0,-66961.0,78199.0,1176.00,-42.60,56.0,X-SC,12.44,92.0,-0.47,0.49,74.84,X40N,NTT,FOOTWEAR
57,PGHH,-0.09,-36.70,108.55,32.01,146716.0,-78360.0,135160.0,17616.87,-57.19,34.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,2.73,36.60,27.31,73.90,39839.0,39083.0,145876.0,424.00,-26.72,68.0,X-SC,40.63,80.0,0.98,0.92,100.78,XY24,NTT,MISC
2,ACC,-0.84,-40.54,194.02,74.81,309307.0,-108708.0,159420.0,3906.00,-57.90,42.0,X-SC,11.98,85.0,-0.35,1.01,6.50,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.20,-23.18,62.33,24.70,190219.0,-92097.0,305181.0,452.00,-59.56,40.0,X-LC,10.89,1.0,-0.48,1.93,1.05,X40,NTT,FMCG
75,TCS,-5.06,-31.83,82.20,24.20,259581.0,-147481.0,315792.0,4230.71,-42.31,50.0,X-LC,15.22,2.0,-0.57,2.00,17.76,X40,ATH,IT
45,INFY,-2.12,-17.03,69.20,40.38,216149.0,-64116.0,312354.0,1972.00,-37.59,58.0,X-LC,16.23,3.0,-0.30,1.98,18.29,X40,NTT,IT
77,TMPV,-3.19,-19.94,78.31,42.75,260878.0,-82972.0,333135.0,600.00,-83.62,45.0,X-LC,5.06,4.0,-0.32,2.11,14.55,XY24,NTT,AUTO
33,HCLTECH,-0.83,-9.43,36.87,23.97,103346.0,-29187.0,280299.0,1853.42,-7.78,66.0,X-LC,12.79,8.0,-0.28,1.77,32.27,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.31,-25.29,77.87,32.89,44919.0,-19522.0,57684.0,1800.00,-371.71,52.0,L-MC,13.84,258.0,-0.43,0.36,42.21,XR,NTT,BANKS
62,RELAXO,-1.35,-46.13,182.73,52.31,142893.0,-66961.0,78199.0,1176.00,-42.60,56.0,X-SC,12.44,92.0,-0.47,0.49,74.84,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.13,-18.82,137.19,92.54,112438.0,-19005.0,81958.0,4520.85,-13.07,56.0,H-SC,13.82,142.0,-0.17,0.52,55.63,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.67,-24.41,32.27,-0.01,31176.0,-31194.0,96611.0,2282.00,19660.87,84.0,M-SC,3.40,231.0,-1.00,0.61,64.45,OX40N,BTT,AC
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.37,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.67,-24.41,32.27,-0.01,31176.0,-31194.0,96611.0,2282.00,19660.87,84.0,M-SC,3.40,231.0,-1.00,0.61,64.45,OX40N,BTT,AC
25,FINCABLES,7.22,64.02,26.76,107.91,64803.0,94521.0,242165.0,1641.55,47.64,78.0,M-SC,17.89,220.0,1.46,1.53,82.19,OX40N,ATH,CABLES
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.37,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
68,SIEMENS,0.48,8.29,15.34,24.90,30912.0,15420.0,201515.0,4648.66,69.20,72.0,H-LC,12.21,51.0,0.50,1.27,42.18,AR,ATH,ELECTRICAL
11,BERGEPAINT,4.74,3.26,21.36,25.32,56848.0,8393.0,266142.0,680.00,-2.33,68.0,X-MC,2.92,68.0,0.15,1.68,39.56,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.64
1     25       44.75
2     50       76.83

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.45
LC    37.48
MC    23.06
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.30
XY24     24.90
X40N     18.30
XR        9.09
OX40N     7.21
XY25      7.20
AR        6.14
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.41
H-SC    19.26
X-MC    18.78
X-SC     9.89
M-SC     9.79
H-MC     2.73
H-LC     1.27
M-MC     1.19
M-LC     0.80
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.28        -23.35   67.77
IT                  11.03        -36.70  104.55
FINANCE              9.25        -16.65   65.68
AUTO                 8.25         -3.72   40.87
MISC                 6.92        -22.57   75.16
BANKS                6.07        -11.06   58.96
PHARMA               5.77          9.11   16.66
INSURANCE            5.58         -5.33   42.57
PAINTS               5.51        -12.96   32.23
ELECTRICAL           4.13         -7.95   45.76
HEALTHCARE           2.03        -11.14   40.15
AC                   1.83        -10.41   40.34
APPARELS             1.70          0.38   33.08
REFINERIES           1.70        -11.18   48.53
BREWERIES            1.66         10.56    8.01
FOOTWEAR             1.64        -69.28  137.16
CABLES               1.53         39.03   26.76
DURABLES             1.48        -66.08  106.48
TRAVEL               1.46        -94.04  191.20
CERAMICS             1.33        -46.11   90.49
CHEMICALS            1.22        -37.40  148.92
ENGINEERING          1.21        -26.90   84.95
CEMENT               1.01        -68.19  194.02
JEWELLERY            0.97       -108.80  181.35
ENTERTAINMENT        0.67        -80.18  187.63
TEXTILES             0.39        -51.28   94.41
HOTELS               0.37        -95.57  164.55

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3464072.0     20
X40       2065199.0     18
XR        1359817.0     13
X40N      1186878.0     12
AR        1058079.0      8
OX40N      653740.0     10
XY25       561631.0      5
SR         281824.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3305435.0     23
X-LC        2458228.0     20
X-MC        1486398.0     14
M-SC        1370253.0     14
X-SC        1237844.0      9
H-MC         265155.0      2
L-SC         210707.0      2
M-LC         164855.0      1
M-MC          56534.0      1
L-MC          44919.0      1
H-LC          30912.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1188557.0      9
H-SC       XY24       993649.0      5
           AR         931218.0      5
M-SC       XY24       856275.0      6
H-SC       XR         803536.0      7
X-SC       XY24       718151.0      4
X-MC       X40        660194.0      7
X-LC       X40N       527504.0      6
           XY24       433724.0      2
X-MC       X40N       356129.0      3
X-SC       X40N       303245.0      3
H-SC       OX40N      295208.0      4
           SR         281824.0      2
X-MC       XY25       253809.0      2
X-LC       XY25       251288.0      2
H-MC       XY24       246007.0      1
M-SC       OX40N      243364.0      5
X-SC       X40        216448.0      2
X-MC       XY24       216266.0      2
M-SC       XR         193813.0      2
M-LC       XR         164855.0      1
L-SC       OX40N      115168.0      1
           XR          95539.0      1
M-SC       AR          76801.0      1
X-LC       XR          57155.0      1
M-MC       XY25        56534.0      1
L-MC       XR          44919.0      1
H-LC       AR          30912.0      1
H-MC       AR          19148.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 34.0 seconds