<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-12 15:10:36
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -84.07 K (-0.52%)
Current PnL: -31.60 L (-16.73%)
CY Booked + Current PnL: -27.38 L (-14.49%)
-------------------
Total profit:  4.31 L
Total loss:  -35.91 L
-------------------
Total Booked + Current PnL: 15.49 L (10.61%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.63%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.06 C (66.16%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.32%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-3.01,19.50,6.37,27.12,13437.0,34430.0,210947.0,1486.00,15.88,52.0,X-SC,16.64,87.0,2.56,1.33,45.35,XY24,NTT,HEALTHCARE
87,ZYDUSLIFE,0.76,26.55,7.08,35.51,18778.0,55648.0,265222.0,1285.01,10.36,70.0,H-MC,15.82,120.0,2.96,1.68,39.57,AR,ATH,PHARMA
80,UNITDSPR,-1.69,11.85,7.97,20.77,20872.0,27743.0,261887.0,1644.00,-0.77,64.0,X-MC,9.00,64.0,1.33,1.65,25.89,X40N,NTT,BREWERIES
69,SIS,0.19,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,57.0,H-SC,22.08,168.0,0.03,0.71,66.22,OX40N,NTT,MISC
79,TTKPRESTIG,-0.51,-23.70,31.19,0.09,23982.0,-23887.0,76890.0,770.00,78.44,38.0,M-SC,12.11,250.0,-1.00,0.49,38.39,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,76.0,H-SC,4.51,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
11,BERGEPAINT,4.70,3.22,21.41,25.32,56961.0,8299.0,266048.0,680.00,-2.33,68.0,X-MC,3.21,68.0,0.15,1.68,39.51,XY24,NTT,PAINTS
58,QUESS,3.02,36.99,26.95,73.90,39426.0,39499.0,146292.0,424.00,-26.17,69.0,X-SC,40.65,80.0,1.00,0.92,101.35,XY24,NTT,MISC
0,5PAISA,2.29,-26.51,53.63,12.90,86117.0,-57920.0,160576.0,593.00,136.78,62.0,H-SC,10.81,170.0,-0.67,1.01,54.96,OX40N,NTT,FINANCE

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-11.25,-17.25,61.49,33.64,126978.0,-43035.0,206502.0,1469.04,-14.38,23.0,X-LC,5.05,32.0,-0.34,1.30,0.00,X40N,ATH,FMCG
75,TCS,-4.39,-31.36,80.93,24.20,257365.0,-145264.0,318009.0,4230.71,-41.99,52.0,X-LC,15.24,2.0,-0.56,2.01,18.59,X40,ATH,IT
73,TANLA,-3.51,-32.76,223.08,117.25,406162.0,-88691.0,182070.0,1922.32,-32.24,52.0,H-SC,15.34,147.0,-0.22,1.15,59.41,AR,ATH,IT
29,GREENPANEL,-3.45,-52.75,202.96,43.14,175556.0,-96580.0,86498.0,537.00,93.80,33.0,M-SC,10.39,225.0,-0.55,0.55,4.17,XY24,NTT,MISC
55,MEDANTA,-3.01,19.50,6.37,27.12,13437.0,34430.0,210947.0,1486.00,15.88,52.0,X-SC,16.64,87.0,2.56,1.33,45.35,XY24,NTT,HEALTHCARE

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.19,0.68,20.44,21.26,22850.0,760.0,111792.0,528.0,2669.95,57.0,H-SC,22.08,168.0,0.03,0.71,66.22,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
69,SIS,0.19,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,57.0,H-SC,22.08,168.0,0.03,0.71,66.22,OX40N,NTT,MISC
43,INDIGOPNTS,-0.55,-20.49,25.79,0.02,35795.0,-35766.0,138793.0,1408.00,111.50,59.0,M-SC,5.85,222.0,-1.00,0.88,57.47,OX40N,NTT,PAINTS
16,CERA,-1.58,-22.99,60.87,23.89,82461.0,-40433.0,135470.0,9475.00,-25.78,38.0,H-SC,12.48,153.0,-0.49,0.86,31.69,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-0.51,-23.70,31.19,0.09,23982.0,-23887.0,76890.0,770.00,78.44,38.0,M-SC,12.11,250.0,-1.00,0.49,38.39,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.76,26.55,7.08,35.51,18778.0,55648.0,265222.0,1285.01,10.36,70.0,H-MC,15.82,120.0,2.96,1.68,39.57,AR,ATH,PHARMA
58,QUESS,3.02,36.99,26.95,73.90,39426.0,39499.0,146292.0,424.00,-26.17,69.0,X-SC,40.65,80.0,1.00,0.92,101.35,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.19,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,57.0,H-SC,22.08,168.0,0.03,0.71,66.22,OX40N,NTT,MISC
70,STARHEALTH,0.01,13.15,30.14,47.26,95877.0,36981.0,318104.0,761.00,78.49,51.0,H-SC,16.89,173.0,0.39,2.01,37.54,XY24,NTT,INSURANCE
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.76,26.55,7.08,35.51,18778.0,55648.0,265222.0,1285.01,10.36,70.0,H-MC,15.82,120.0,2.96,1.68,39.57,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.76,26.55,7.08,35.51,18778.0,55648.0,265222.0,1285.01,10.36,70.0,H-MC,15.82,120.0,2.96,1.68,39.57,AR,ATH,PHARMA
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
69,SIS,0.19,0.68,20.44,21.26,22850.0,760.0,111792.0,528.00,2669.95,57.0,H-SC,22.08,168.0,0.03,0.71,66.22,OX40N,NTT,MISC
3,ALKYLAMINE,-2.62,-19.23,138.39,92.54,112850.0,-19418.0,81545.0,4520.85,-13.57,55.0,H-SC,13.43,142.0,-0.17,0.52,54.85,SR,ATH,CHEMICALS
42,INDIAMART,0.03,-23.30,161.95,100.92,153205.0,-28736.0,94600.0,4675.60,-65.43,42.0,H-SC,12.73,140.0,-0.19,0.60,2.40,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-11.25,-17.25,61.49,33.64,126978.0,-43035.0,206502.0,1469.04,-14.38,23.0,X-LC,5.05,32.0,-0.34,1.30,0.00,X40N,ATH,FMCG
34,HDFCBANK,0.02,-10.95,47.16,31.05,123105.0,-32084.0,261036.0,1073.00,-25.96,34.0,X-LC,11.65,26.0,-0.26,1.65,1.32,X40,BTT,BANKS
57,PGHH,-0.09,-36.70,108.56,32.01,146721.0,-78368.0,135152.0,17616.87,-57.19,34.0,X-MC,19.17,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
56,PAGEIND,-0.92,-0.66,34.48,33.59,91922.0,-1784.0,266595.0,51217.29,-28.78,35.0,X-MC,8.98,55.0,-0.02,1.68,26.61,X40,ATH,APPARELS
47,ITC,-0.86,-23.69,63.41,24.70,192230.0,-94124.0,303154.0,452.00,-59.97,37.0,X-LC,10.92,1.0,-0.49,1.92,0.38,X40,NTT,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.45,-24.10,84.26,39.86,168436.0,-63465.0,199900.0,3683.41,-8.09,41.0,X-MC,1.46,62.0,-0.38,1.26,13.07,XY25,ATH,FMCG
23,DMART,-0.45,-1.60,33.56,31.42,102958.0,-5001.0,306789.0,5391.45,-18.18,52.0,X-LC,2.79,14.0,-0.05,1.94,10.71,X40N,ATH,FMCG
50,KOTAKBANK,0.09,3.36,15.06,18.92,37311.0,8046.0,247748.0,452.46,-9.84,54.0,X-LC,2.95,12.0,0.22,1.57,11.47,X40,ATH,BANKS
8,BAJAJHLDNG,-0.48,3.27,24.18,28.24,63928.0,8380.0,264385.0,14274.15,-4.76,65.0,X-LC,3.19,28.0,0.13,1.67,33.06,X40,ATH,FINANCE
11,BERGEPAINT,4.70,3.22,21.41,25.32,56961.0,8299.0,266048.0,680.00,-2.33,68.0,X-MC,3.21,68.0,0.15,1.68,39.51,XY24,NTT,PAINTS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.12,-8.19,51.57,39.15,118714.0,-20537.0,230200.0,811.41,-31.69,37.0,X-LC,16.24,31.0,-0.17,1.45,0.00,X40,ATH,INSURANCE
28,GODREJCP,-11.25,-17.25,61.49,33.64,126978.0,-43035.0,206502.0,1469.04,-14.38,23.0,X-LC,5.05,32.0,-0.34,1.30,0.00,X40N,ATH,FMCG
57,PGHH,-0.09,-36.70,108.56,32.01,146721.0,-78368.0,135152.0,17616.87,-57.19,34.0,X-MC,19.17,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
47,ITC,-0.86,-23.69,63.41,24.70,192230.0,-94124.0,303154.0,452.00,-59.97,37.0,X-LC,10.92,1.0,-0.49,1.92,0.38,X40,NTT,FMCG
20,DABUR,-1.24,-20.32,80.35,43.70,158821.0,-50406.0,197662.0,735.00,-27.78,38.0,X-MC,9.52,70.0,-0.32,1.25,0.58,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.81,-54.04,194.18,35.20,114834.0,-69532.0,59138.0,2096.00,-22.45,56.0,X-SC,13.28,91.0,-0.61,0.37,18.81,X40,NTT,FOOTWEAR
62,RELAXO,-0.90,-45.88,181.44,52.31,142532.0,-66604.0,78556.0,1176.00,-42.41,57.0,X-SC,12.83,92.0,-0.47,0.50,75.64,X40N,NTT,FOOTWEAR
57,PGHH,-0.09,-36.70,108.56,32.01,146721.0,-78368.0,135152.0,17616.87,-57.19,34.0,X-MC,19.17,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,3.02,36.99,26.95,73.90,39426.0,39499.0,146292.0,424.00,-26.17,69.0,X-SC,40.65,80.0,1.00,0.92,101.35,XY24,NTT,MISC
2,ACC,-0.54,-40.36,193.13,74.81,308815.0,-108228.0,159900.0,3906.00,-57.90,42.0,X-SC,11.84,85.0,-0.35,1.01,6.82,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.86,-23.69,63.41,24.70,192230.0,-94124.0,303154.0,452.00,-59.97,37.0,X-LC,10.92,1.0,-0.49,1.92,0.38,X40,NTT,FMCG
75,TCS,-4.39,-31.36,80.93,24.20,257365.0,-145264.0,318009.0,4230.71,-41.99,52.0,X-LC,15.24,2.0,-0.56,2.01,18.59,X40,ATH,IT
45,INFY,-1.70,-16.68,68.49,40.38,214831.0,-62803.0,313667.0,1972.00,-37.23,59.0,X-LC,16.22,3.0,-0.29,1.98,18.79,X40,NTT,IT
77,TMPV,-1.51,-18.55,75.26,42.75,255076.0,-77181.0,338926.0,600.00,-83.62,50.0,X-LC,4.98,4.0,-0.30,2.14,16.54,XY24,NTT,AUTO
33,HCLTECH,-0.44,-9.08,36.34,23.97,102259.0,-28090.0,281396.0,1853.42,-7.36,68.0,X-LC,12.78,8.0,-0.27,1.78,32.79,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,1.19,-24.63,76.32,32.89,44411.0,-19016.0,58191.0,1800.00,-373.81,55.0,L-MC,13.65,258.0,-0.43,0.37,43.47,XR,NTT,BANKS
62,RELAXO,-0.90,-45.88,181.44,52.31,142532.0,-66604.0,78556.0,1176.00,-42.41,57.0,X-SC,12.83,92.0,-0.47,0.50,75.64,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,-2.62,-19.23,138.39,92.54,112850.0,-19418.0,81545.0,4520.85,-13.57,55.0,H-SC,13.43,142.0,-0.17,0.52,54.85,SR,ATH,CHEMICALS
12,BOSCH-HCIL,0.84,-25.03,33.36,-0.01,31966.0,-31983.0,95822.0,2282.00,19508.70,84.0,M-SC,3.59,231.0,-1.00,0.61,63.10,OX40N,BTT,AC
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,76.0,H-SC,4.51,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,0.84,-25.03,33.36,-0.01,31966.0,-31983.0,95822.0,2282.00,19508.70,84.0,M-SC,3.59,231.0,-1.00,0.61,63.10,OX40N,BTT,AC
25,FINCABLES,6.38,62.74,27.76,107.91,66701.0,92632.0,240276.0,1641.55,46.63,79.0,M-SC,17.71,220.0,1.39,1.52,80.77,OX40N,ATH,CABLES
82,VALIANTORG,4.99,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,76.0,H-SC,4.51,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
68,SIEMENS,0.08,7.86,15.80,24.90,31713.0,14620.0,200715.0,4648.66,68.58,72.0,H-LC,12.39,51.0,0.46,1.27,41.61,AR,ATH,ELECTRICAL
11,BERGEPAINT,4.70,3.22,21.41,25.32,56961.0,8299.0,266048.0,680.00,-2.33,68.0,X-MC,3.21,68.0,0.15,1.68,39.51,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.70
1     25       44.79
2     50       76.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.44
LC    37.55
MC    23.03
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.30
XY24     24.95
X40N     18.30
XR        9.09
OX40N     7.19
XY25      7.19
AR        6.15
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.48
H-SC    19.28
X-MC    18.72
X-SC     9.88
M-SC     9.78
H-MC     2.74
H-LC     1.27
M-MC     1.20
M-LC     0.80
L-SC     0.50
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.26        -23.50   67.97
IT                  11.05        -36.29  103.93
FINANCE              9.27        -16.33   65.21
AUTO                 8.28         -3.12   40.05
MISC                 6.91        -22.67   75.30
BANKS                6.12        -10.37   57.96
PHARMA               5.77          9.13   16.65
INSURANCE            5.58         -5.08   42.24
PAINTS               5.50        -13.39   32.73
ELECTRICAL           4.13         -8.16   46.03
HEALTHCARE           2.02        -11.81   40.99
AC                   1.82        -11.02   41.12
REFINERIES           1.70        -10.65   47.82
APPARELS             1.68         -0.67   34.48
FOOTWEAR             1.66        -68.26  135.74
BREWERIES            1.65         10.59    7.97
CABLES               1.52         38.55   27.76
DURABLES             1.47        -66.47  106.98
TRAVEL               1.46        -93.71  190.71
CERAMICS             1.33        -45.94   90.28
CHEMICALS            1.22        -37.69  149.45
ENGINEERING          1.21        -26.87   84.90
CEMENT               1.01        -67.68  193.13
JEWELLERY            0.97       -108.74  181.25
ENTERTAINMENT        0.68        -79.98  187.32
TEXTILES             0.39        -51.40   94.57
HOTELS               0.36        -97.13  166.67

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3454297.0     20
X40       2061925.0     18
XR        1358973.0     13
X40N      1186139.0     12
AR        1058826.0      8
OX40N      657049.0     10
XY25       559924.0      5
SR         282553.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3303183.0     23
X-LC        2444692.0     20
X-MC        1488069.0     14
M-SC        1373112.0     14
X-SC        1238716.0      9
H-MC         264785.0      2
L-SC         211375.0      2
M-LC         164603.0      1
M-MC          55027.0      1
L-MC          44411.0      1
H-LC          31713.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1183440.0      9
H-SC       XY24       991847.0      5
           AR         931471.0      5
M-SC       XY24       855652.0      6
H-SC       XR         802502.0      7
X-SC       XY24       718564.0      4
X-MC       X40        661999.0      7
X-LC       X40N       527009.0      6
           XY24       426445.0      2
X-MC       X40N       355464.0      3
X-SC       X40N       303666.0      3
H-SC       OX40N      294810.0      4
           SR         282553.0      2
X-MC       XY25       254824.0      2
X-LC       XY25       250073.0      2
M-SC       OX40N      246866.0      5
H-MC       XY24       246007.0      1
X-SC       X40        216486.0      2
X-MC       XY24       215782.0      2
M-SC       XR         193730.0      2
M-LC       XR         164603.0      1
L-SC       OX40N      115373.0      1
           XR          96002.0      1
M-SC       AR          76864.0      1
X-LC       XR          57725.0      1
M-MC       XY25        55027.0      1
L-MC       XR          44411.0      1
H-LC       AR          31713.0      1
H-MC       AR          18778.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 25.0 seconds