<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-11 13:45:39
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.61 C
-------------------
Today PnL: -10.11 K (-0.06%)
Current PnL: -30.93 L (-16.37%)
CY Booked + Current PnL: -26.71 L (-14.14%)
-------------------
Total profit:  3.87 L
Total loss:  -34.80 L
-------------------
Total Booked + Current PnL: 16.16 L (11.06%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.62%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.06 C (65.47%)
===================
Deployed:  1.46 C
Current:  1.61 C
CAGR/XIRR %: 4.52%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-2.97,22.53,3.74,27.12,8089.0,39775.0,216292.0,1486.00,18.74,59.0,X-SC,16.36,87.0,4.92,1.36,49.04,XY24,NTT,HEALTHCARE
80,UNITDSPR,1.07,12.29,7.55,20.77,19850.0,28775.0,262919.0,1644.00,-0.46,70.0,X-MC,8.03,64.0,1.45,1.65,26.38,X40N,NTT,BREWERIES
52,M&M,-1.11,9.82,8.19,18.82,21648.0,23639.0,264320.0,3762.88,-4.35,66.0,X-LC,5.03,25.0,1.09,1.66,19.90,X40N,ATH,AUTO
69,SIS,0.97,0.86,20.23,21.26,22654.0,951.0,111983.0,528.00,2674.61,59.0,H-SC,22.55,168.0,0.04,0.70,66.50,OX40N,NTT,MISC
79,TTKPRESTIG,-1.95,-22.81,29.67,0.09,23080.0,-22989.0,77788.0,770.00,80.58,39.0,M-SC,12.80,250.0,-1.00,0.49,40.01,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,6.74,-36.00,172.12,74.15,180215.0,-58902.0,104703.0,838.00,-288.40,69.0,H-SC,4.23,145.0,-0.33,0.66,55.81,XR,NTT,CHEMICALS
58,QUESS,6.46,35.82,28.04,73.90,40670.0,38251.0,145044.0,424.00,-26.72,67.0,X-SC,39.68,80.0,0.94,0.91,99.63,XY24,NTT,MISC
87,ZYDUSLIFE,3.95,22.66,10.47,35.51,26915.0,47493.0,257067.0,1285.01,6.76,63.0,H-MC,15.57,120.0,1.76,1.62,35.28,AR,ATH,PHARMA
25,FINCABLES,3.36,34.13,55.00,107.91,108923.0,50398.0,198042.0,1641.55,20.75,57.0,M-SC,17.27,220.0,0.46,1.25,48.99,OX40N,ATH,CABLES
3,ALKYLAMINE,3.35,-16.64,130.97,92.54,110230.0,-16799.0,84164.0,4520.85,-10.74,63.0,H-SC,13.33,142.0,-0.15,0.53,59.82,SR,ATH,CHEMICALS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
29,GREENPANEL,-3.71,-51.22,193.44,43.14,172750.0,-93774.0,89304.0,537.00,100.26,37.0,M-SC,10.31,225.0,-0.54,0.56,7.55,XY24,NTT,MISC
55,MEDANTA,-2.97,22.53,3.74,27.12,8089.0,39775.0,216292.0,1486.00,18.74,59.0,X-SC,16.36,87.0,4.92,1.36,49.04,XY24,NTT,HEALTHCARE
28,GODREJCP,-2.79,-7.15,43.92,33.64,101762.0,-17838.0,231699.0,1469.04,-3.99,39.0,X-LC,5.15,32.0,-0.18,1.46,4.16,X40N,ATH,FMCG
18,COFFEEDAY,-2.48,-48.77,164.03,35.27,95426.0,-55373.0,58176.0,80.00,-59.76,41.0,L-SC,4.55,266.0,-0.58,0.37,43.47,XR,NTT,HOTELS
59,RAJESHEXPO,-2.37,-84.24,534.80,0.07,115645.0,-115553.0,21624.0,518.00,692.93,34.0,L-SC,36.60,268.0,-1.00,0.14,6.79,OX40N,NTT,JEWELLERY

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.97,0.86,20.23,21.26,22654.0,951.0,111983.0,528.0,2674.61,59.0,H-SC,22.55,168.0,0.04,0.7,66.5,OX40N,NTT,MISC

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.36,34.13,55.00,107.91,108923.0,50398.0,198042.0,1641.55,20.75,57.0,M-SC,17.27,220.0,0.46,1.25,48.99,OX40N,ATH,CABLES
69,SIS,0.97,0.86,20.23,21.26,22654.0,951.0,111983.0,528.00,2674.61,59.0,H-SC,22.55,168.0,0.04,0.70,66.50,OX40N,NTT,MISC
43,INDIGOPNTS,1.04,-19.57,24.36,0.02,34200.0,-34166.0,140393.0,1408.00,114.29,63.0,M-SC,5.32,222.0,-1.00,0.88,59.29,OX40N,NTT,PAINTS
16,CERA,-0.82,-21.38,57.59,23.89,79640.0,-37615.0,138288.0,9475.00,-24.11,43.0,H-SC,12.64,153.0,-0.47,0.87,34.43,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-1.95,-22.81,29.67,0.09,23080.0,-22989.0,77788.0,770.00,80.58,39.0,M-SC,12.80,250.0,-1.00,0.49,40.01,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.36,34.13,55.00,107.91,108923.0,50398.0,198042.0,1641.55,20.75,57.0,M-SC,17.27,220.0,0.46,1.25,48.99,OX40N,ATH,CABLES
87,ZYDUSLIFE,3.95,22.66,10.47,35.51,26915.0,47493.0,257067.0,1285.01,6.76,63.0,H-MC,15.57,120.0,1.76,1.62,35.28,AR,ATH,PHARMA
55,MEDANTA,-2.97,22.53,3.74,27.12,8089.0,39775.0,216292.0,1486.00,18.74,59.0,X-SC,16.36,87.0,4.92,1.36,49.04,XY24,NTT,HEALTHCARE
58,QUESS,6.46,35.82,28.04,73.90,40670.0,38251.0,145044.0,424.00,-26.72,67.0,X-SC,39.68,80.0,0.94,0.91,99.63,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,0.97,0.86,20.23,21.26,22654.0,951.0,111983.0,528.00,2674.61,59.0,H-SC,22.55,168.0,0.04,0.70,66.50,OX40N,NTT,MISC
70,STARHEALTH,1.23,12.62,30.76,47.26,97389.0,35485.0,316608.0,761.00,77.79,50.0,H-SC,16.97,173.0,0.36,1.99,36.89,XY24,NTT,INSURANCE
25,FINCABLES,3.36,34.13,55.00,107.91,108923.0,50398.0,198042.0,1641.55,20.75,57.0,M-SC,17.27,220.0,0.46,1.25,48.99,OX40N,ATH,CABLES
87,ZYDUSLIFE,3.95,22.66,10.47,35.51,26915.0,47493.0,257067.0,1285.01,6.76,63.0,H-MC,15.57,120.0,1.76,1.62,35.28,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,3.95,22.66,10.47,35.51,26915.0,47493.0,257067.0,1285.01,6.76,63.0,H-MC,15.57,120.0,1.76,1.62,35.28,AR,ATH,PHARMA
25,FINCABLES,3.36,34.13,55.00,107.91,108923.0,50398.0,198042.0,1641.55,20.75,57.0,M-SC,17.27,220.0,0.46,1.25,48.99,OX40N,ATH,CABLES
69,SIS,0.97,0.86,20.23,21.26,22654.0,951.0,111983.0,528.00,2674.61,59.0,H-SC,22.55,168.0,0.04,0.70,66.50,OX40N,NTT,MISC
3,ALKYLAMINE,3.35,-16.64,130.97,92.54,110230.0,-16799.0,84164.0,4520.85,-10.74,63.0,H-SC,13.33,142.0,-0.15,0.53,59.82,SR,ATH,CHEMICALS
42,INDIAMART,1.71,-23.29,161.94,100.92,153203.0,-28731.0,94605.0,4675.60,-65.43,42.0,H-SC,12.22,140.0,-0.19,0.60,2.41,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
34,HDFCBANK,-0.18,-10.88,47.05,31.05,122910.0,-31887.0,261233.0,1073.00,-25.96,34.0,X-LC,11.34,26.0,-0.26,1.64,1.40,X40,BTT,BANKS
57,PGHH,-0.42,-36.60,108.21,32.01,146490.0,-78144.0,135376.0,17616.87,-57.06,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
56,PAGEIND,-0.70,0.13,33.41,33.59,89783.0,351.0,268730.0,51217.29,-28.15,37.0,X-MC,8.90,55.0,0.00,1.69,27.62,X40,ATH,APPARELS
35,HDFCLIFE,-0.81,-8.14,51.48,39.15,118574.0,-20407.0,230330.0,811.41,-31.58,37.0,X-LC,16.12,31.0,-0.17,1.45,0.00,X40,ATH,INSURANCE
28,GODREJCP,-2.79,-7.15,43.92,33.64,101762.0,-17838.0,231699.0,1469.04,-3.99,39.0,X-LC,5.15,32.0,-0.18,1.46,4.16,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-1.16,-23.81,83.57,39.86,167683.0,-62715.0,200650.0,3683.41,-7.87,42.0,X-MC,1.56,62.0,-0.37,1.26,13.50,XY25,ATH,FMCG
11,BERGEPAINT,1.27,-0.98,26.56,25.32,67786.0,-2532.0,255217.0,680.00,-6.43,62.0,X-MC,2.36,68.0,-0.04,1.61,33.83,XY24,NTT,PAINTS
8,BAJAJHLDNG,2.57,3.79,23.55,28.24,62577.0,9714.0,265719.0,14274.15,-4.76,67.0,X-LC,2.80,28.0,0.16,1.67,33.74,X40,ATH,FINANCE
23,DMART,0.17,-1.01,32.76,31.42,101109.0,-3154.0,308636.0,5391.45,-17.64,54.0,X-LC,2.98,14.0,-0.03,1.94,11.37,X40N,ATH,FMCG
50,KOTAKBANK,-0.51,2.90,15.57,18.92,38403.0,6943.0,246645.0,452.46,-10.27,52.0,X-LC,3.16,12.0,0.18,1.55,10.97,X40,ATH,BANKS

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.81,-8.14,51.48,39.15,118574.0,-20407.0,230330.0,811.41,-31.58,37.0,X-LC,16.12,31.0,-0.17,1.45,0.00,X40,ATH,INSURANCE
57,PGHH,-0.42,-36.60,108.21,32.01,146490.0,-78144.0,135376.0,17616.87,-57.06,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
34,HDFCBANK,-0.18,-10.88,47.05,31.05,122910.0,-31887.0,261233.0,1073.00,-25.96,34.0,X-LC,11.34,26.0,-0.26,1.64,1.40,X40,BTT,BANKS
47,ITC,-0.73,-22.59,61.08,24.70,187844.0,-89740.0,307538.0,452.00,-59.56,43.0,X-LC,10.90,1.0,-0.48,1.93,1.83,X40,NTT,FMCG
20,DABUR,-0.12,-19.12,77.66,43.70,155820.0,-47424.0,200644.0,735.00,-26.67,42.0,X-MC,9.31,70.0,-0.30,1.26,2.10,XY24,BTT,FMCG

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,-1.82,-54.85,199.47,35.20,115876.0,-70578.0,58092.0,2096.00,-23.90,51.0,X-SC,13.64,91.0,-0.61,0.37,16.71,X40,NTT,FOOTWEAR
62,RELAXO,-0.06,-45.19,177.88,52.31,141525.0,-65598.0,79562.0,1176.00,-41.63,60.0,X-SC,11.82,92.0,-0.46,0.50,77.89,X40N,NTT,FOOTWEAR
57,PGHH,-0.42,-36.60,108.21,32.01,146490.0,-78144.0,135376.0,17616.87,-57.06,34.0,X-MC,19.19,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,6.46,35.82,28.04,73.90,40670.0,38251.0,145044.0,424.00,-26.72,67.0,X-SC,39.68,80.0,0.94,0.91,99.63,XY24,NTT,MISC
2,ACC,-1.03,-39.64,189.61,74.81,306872.0,-106284.0,161844.0,3906.00,-57.01,46.0,X-SC,12.10,85.0,-0.35,1.02,8.12,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.73,-22.59,61.08,24.70,187844.0,-89740.0,307538.0,452.00,-59.56,43.0,X-LC,10.90,1.0,-0.48,1.93,1.83,X40,NTT,FMCG
75,TCS,0.65,-28.33,73.28,24.20,243322.0,-131229.0,332044.0,4230.71,-39.36,62.0,X-LC,15.43,2.0,-0.54,2.09,23.82,X40,ATH,IT
45,INFY,0.48,-15.38,65.90,40.38,209939.0,-57898.0,318572.0,1972.00,-36.14,64.0,X-LC,16.24,3.0,-0.28,2.00,20.64,X40,NTT,IT
77,TMPV,0.16,-17.29,72.59,42.75,249836.0,-71933.0,344174.0,600.00,-83.62,56.0,X-LC,5.11,4.0,-0.29,2.17,18.34,XY24,NTT,AUTO
33,HCLTECH,0.30,-8.95,36.15,23.97,101867.0,-27697.0,281789.0,1853.42,-7.36,69.0,X-LC,13.07,8.0,-0.27,1.77,32.97,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,-1.23,-25.48,78.32,32.89,45062.0,-19670.0,57536.0,1800.00,-371.01,52.0,L-MC,13.81,258.0,-0.44,0.36,41.85,XR,NTT,BANKS
62,RELAXO,-0.06,-45.19,177.88,52.31,141525.0,-65598.0,79562.0,1176.00,-41.63,60.0,X-SC,11.82,92.0,-0.46,0.50,77.89,X40N,NTT,FOOTWEAR
3,ALKYLAMINE,3.35,-16.64,130.97,92.54,110230.0,-16799.0,84164.0,4520.85,-10.74,63.0,H-SC,13.33,142.0,-0.15,0.53,59.82,SR,ATH,CHEMICALS
12,BOSCH-HCIL,1.71,-25.02,33.36,-0.01,31968.0,-31978.0,95827.0,2282.00,19508.70,86.0,M-SC,3.40,231.0,-1.00,0.60,63.11,OX40N,BTT,AC
82,VALIANTORG,6.74,-36.00,172.12,74.15,180215.0,-58902.0,104703.0,838.00,-288.40,69.0,H-SC,4.23,145.0,-0.33,0.66,55.81,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,1.71,-25.02,33.36,-0.01,31968.0,-31978.0,95827.0,2282.00,19508.70,86.0,M-SC,3.40,231.0,-1.00,0.60,63.11,OX40N,BTT,AC
33,HCLTECH,0.30,-8.95,36.15,23.97,101867.0,-27697.0,281789.0,1853.42,-7.36,69.0,X-LC,13.07,8.0,-0.27,1.77,32.97,X40,ATH,IT
68,SIEMENS,-0.47,4.68,19.32,24.90,37635.0,8705.0,194800.0,4648.66,63.58,64.0,H-LC,11.70,51.0,0.23,1.23,37.44,AR,ATH,ELECTRICAL
75,TCS,0.65,-28.33,73.28,24.20,243322.0,-131229.0,332044.0,4230.71,-39.36,62.0,X-LC,15.43,2.0,-0.54,2.09,23.82,X40,ATH,IT
58,QUESS,6.46,35.82,28.04,73.90,40670.0,38251.0,145044.0,424.00,-26.72,67.0,X-SC,39.68,80.0,0.94,0.91,99.63,XY24,NTT,MISC

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.81
1     25       44.88
2     50       76.79

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.27
LC    37.80
MC    22.93
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.39
XY24     24.89
X40N     18.52
XR        9.12
XY25      7.19
OX40N     6.91
AR        6.11
SR        0.87
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.77
H-SC    19.36
X-MC    18.70
X-SC     9.92
M-SC     9.48
H-MC     2.68
H-LC     1.23
M-MC     1.19
M-LC     0.80
L-SC     0.51
L-MC     0.36
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.45        -21.39   65.10
IT                  11.25        -33.19   99.29
FINANCE              9.26        -16.19   65.02
AUTO                 8.30         -2.55   39.27
MISC                 6.91        -21.86   74.15
BANKS                6.07        -10.50   58.16
PHARMA               5.67          8.08   17.99
INSURANCE            5.57         -5.00   42.13
PAINTS               5.46        -13.69   33.08
ELECTRICAL           4.11         -8.35   46.29
HEALTHCARE           2.07         -8.93   37.35
AC                   1.81        -10.90   40.98
REFINERIES           1.70        -10.35   47.42
APPARELS             1.69          0.13   33.41
BREWERIES            1.65         10.94    7.55
FOOTWEAR             1.65        -68.39  135.91
DURABLES             1.48        -64.41  104.40
TRAVEL               1.46        -92.23  188.49
CERAMICS             1.34        -43.69   87.34
CABLES               1.25         25.45   55.00
ENGINEERING          1.21        -26.08   83.75
CHEMICALS            1.19        -40.08  153.78
CEMENT               1.02        -65.67  189.61
JEWELLERY            0.99       -105.14  176.41
ENTERTAINMENT        0.68        -79.09  185.89
TEXTILES             0.39        -50.36   93.24
HOTELS               0.37        -95.18  164.03

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3445631.0     20
X40       2029270.0     18
XR        1350376.0     13
X40N      1138047.0     12
AR        1061725.0      8
OX40N      692186.0     10
XY25       556600.0      5
SR         278773.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3276198.0     23
X-LC        2373862.0     20
X-MC        1481334.0     14
M-SC        1409354.0     14
X-SC        1225777.0      9
H-MC         271729.0      2
L-SC         211071.0      2
M-LC         164082.0      1
M-MC          56504.0      1
L-MC          45062.0      1
H-LC          37635.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1156222.0      9
H-SC       XY24       986659.0      5
           AR         920487.0      5
M-SC       XY24       854793.0      6
H-SC       XR         798840.0      7
X-SC       XY24       713653.0      4
X-MC       X40        656405.0      7
X-LC       X40N       495019.0      6
           XY24       422106.0      2
X-MC       X40N       347547.0      3
X-SC       X40N       295481.0      3
H-SC       OX40N      291439.0      4
M-SC       OX40N      285102.0      5
H-SC       SR         278773.0      2
X-MC       XY25       253776.0      2
X-LC       XY25       246320.0      2
H-MC       XY24       244814.0      1
X-MC       XY24       223606.0      2
X-SC       X40        216643.0      2
M-SC       XR         192771.0      2
M-LC       XR         164082.0      1
L-SC       OX40N      115645.0      1
           XR          95426.0      1
M-SC       AR          76688.0      1
M-MC       XY25        56504.0      1
X-LC       XR          54195.0      1
L-MC       XR          45062.0      1
H-LC       AR          37635.0      1
H-MC       AR          26915.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 27.0 seconds