<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-08-12 12:29:44
-------------------
qualified stocks: 88
with latest results: 30
still star stocks: 19
-------------------
Initial Investment:  1.46 C
CY Investment:  1.89 C
Reserve:  2.24 L
Current:  1.60 C
-------------------
Today PnL: -1.33 L (-0.82%)
Current PnL: -31.75 L (-16.8%)
CY Booked + Current PnL: -27.53 L (-14.57%)
-------------------
Total profit:  4.32 L
Total loss:  -36.07 L
-------------------
Total Booked + Current PnL: 15.34 L (10.51%)
Total Booked PnL: 47.09 L (32.24%)
Curr Year Booked PnL: 4.22 L (2.63%)
Prev Year Booked PnL: 42.87 L (29.35%)
===================
Est FTT:  2.67 C
Est FTT PnL: 1.06 C (66.31%)
===================
Deployed:  1.46 C
Current:  1.60 C
CAGR/XIRR %: 4.28%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MEDANTA,-4.23,20.94,5.11,27.12,10909.0,36967.0,213484.0,1486.00,17.15,56.0,X-SC,15.93,87.0,3.39,1.35,47.10,XY24,NTT,HEALTHCARE
87,ZYDUSLIFE,0.44,26.15,7.42,35.51,19617.0,54808.0,264382.0,1285.01,9.91,70.0,H-MC,15.95,120.0,2.79,1.67,39.13,AR,ATH,PHARMA
80,UNITDSPR,-1.70,11.83,7.99,20.77,20922.0,27709.0,261853.0,1644.00,-0.77,65.0,X-MC,8.55,64.0,1.32,1.66,25.87,X40N,NTT,BREWERIES
69,SIS,3.02,1.11,19.93,21.26,22374.0,1232.0,112264.0,528.00,2681.87,58.0,H-SC,22.64,168.0,0.06,0.71,66.92,OX40N,NTT,MISC
79,TTKPRESTIG,-2.96,-23.60,31.02,0.09,23882.0,-23788.0,76989.0,770.00,78.66,38.0,M-SC,12.75,250.0,-1.00,0.49,38.57,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.20,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
69,SIS,3.02,1.11,19.93,21.26,22374.0,1232.0,112264.0,528.00,2681.87,58.0,H-SC,22.64,168.0,0.06,0.71,66.92,OX40N,NTT,MISC
58,QUESS,2.59,36.23,27.65,73.90,40226.0,38689.0,145482.0,424.00,-26.72,68.0,X-SC,40.48,80.0,0.96,0.92,100.24,XY24,NTT,MISC
11,BERGEPAINT,2.48,2.38,22.40,25.32,59110.0,6137.0,263886.0,680.00,-3.12,68.0,X-MC,2.38,68.0,0.10,1.67,38.38,XY24,NTT,PAINTS

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-11.16,-16.52,60.08,33.64,125157.0,-41219.0,208318.0,1469.04,-13.54,24.0,X-LC,5.19,32.0,-0.33,1.32,0.00,X40N,ATH,FMCG
75,TCS,-5.20,-31.93,82.47,24.20,260053.0,-147943.0,315330.0,4230.71,-42.31,50.0,X-LC,15.22,2.0,-0.57,1.99,17.59,X40,ATH,IT
55,MEDANTA,-4.23,20.94,5.11,27.12,10909.0,36967.0,213484.0,1486.00,17.15,56.0,X-SC,15.93,87.0,3.39,1.35,47.10,XY24,NTT,HEALTHCARE
64,REPCOHOME,-3.35,-20.60,139.07,89.82,316365.0,-59019.0,227486.0,880.00,-60.51,33.0,H-SC,1.34,161.0,-0.19,1.44,9.36,XY24,NTT,FINANCE
77,TMPV,-3.12,-19.88,78.17,42.75,260605.0,-82725.0,333382.0,600.00,-83.62,45.0,X-LC,5.06,4.0,-0.32,2.11,14.63,XY24,NTT,AUTO

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

Empty DataFrame
Columns: [Symbol, Today P/L%, Current P/L%, FTT%, OTT%, FTT Amt, Current P/L, Current, FTT, Dev%_PE, RSI_14, Conviction, Spread%, CumlRnk, RRR Ind, CurrAlloc%, Gained%, Criteria, Strategy, Category]
Index: []

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
69,SIS,3.02,1.11,19.93,21.26,22374.0,1232.0,112264.0,528.00,2681.87,58.0,H-SC,22.64,168.0,0.06,0.71,66.92,OX40N,NTT,MISC
43,INDIGOPNTS,-1.76,-20.36,25.59,0.02,35574.0,-35543.0,139016.0,1408.00,112.05,61.0,M-SC,5.41,222.0,-1.00,0.88,57.72,OX40N,NTT,PAINTS
16,CERA,-2.44,-23.04,60.98,23.89,82554.0,-40525.0,135378.0,9475.00,-25.78,38.0,H-SC,12.46,153.0,-0.49,0.86,31.60,OX40N,NTT,CERAMICS
79,TTKPRESTIG,-2.96,-23.60,31.02,0.09,23882.0,-23788.0,76989.0,770.00,78.66,38.0,M-SC,12.75,250.0,-1.00,0.49,38.57,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.44,26.15,7.42,35.51,19617.0,54808.0,264382.0,1285.01,9.91,70.0,H-MC,15.95,120.0,2.79,1.67,39.13,AR,ATH,PHARMA
55,MEDANTA,-4.23,20.94,5.11,27.12,10909.0,36967.0,213484.0,1486.00,17.15,56.0,X-SC,15.93,87.0,3.39,1.35,47.10,XY24,NTT,HEALTHCARE
58,QUESS,2.59,36.23,27.65,73.90,40226.0,38689.0,145482.0,424.00,-26.72,68.0,X-SC,40.48,80.0,0.96,0.92,100.24,XY24,NTT,MISC

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
69,SIS,3.02,1.11,19.93,21.26,22374.0,1232.0,112264.0,528.00,2681.87,58.0,H-SC,22.64,168.0,0.06,0.71,66.92,OX40N,NTT,MISC
70,STARHEALTH,-0.35,12.75,30.61,47.26,97022.0,35839.0,316962.0,761.00,78.03,50.0,H-SC,16.87,173.0,0.37,2.00,37.05,XY24,NTT,INSURANCE
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
87,ZYDUSLIFE,0.44,26.15,7.42,35.51,19617.0,54808.0,264382.0,1285.01,9.91,70.0,H-MC,15.95,120.0,2.79,1.67,39.13,AR,ATH,PHARMA

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
87,ZYDUSLIFE,0.44,26.15,7.42,35.51,19617.0,54808.0,264382.0,1285.01,9.91,70.0,H-MC,15.95,120.0,2.79,1.67,39.13,AR,ATH,PHARMA
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
69,SIS,3.02,1.11,19.93,21.26,22374.0,1232.0,112264.0,528.00,2681.87,58.0,H-SC,22.64,168.0,0.06,0.71,66.92,OX40N,NTT,MISC
3,ALKYLAMINE,-2.21,-18.89,137.39,92.54,112507.0,-19074.0,81889.0,4520.85,-13.07,56.0,H-SC,13.81,142.0,-0.17,0.52,55.50,SR,ATH,CHEMICALS
42,INDIAMART,0.38,-23.03,161.05,100.92,152882.0,-28408.0,94928.0,4675.60,-65.23,43.0,H-SC,12.72,140.0,-0.19,0.60,2.76,AR,ATH,MISC

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
28,GODREJCP,-11.16,-16.52,60.08,33.64,125157.0,-41219.0,208318.0,1469.04,-13.54,24.0,X-LC,5.19,32.0,-0.33,1.32,0.00,X40N,ATH,FMCG
34,HDFCBANK,-0.78,-11.66,48.35,31.05,125198.0,-34179.0,258941.0,1073.00,-26.46,32.0,X-LC,11.68,26.0,-0.27,1.64,0.51,X40,BTT,BANKS
57,PGHH,-0.55,-36.79,108.85,32.01,146904.0,-78560.0,134960.0,17616.87,-57.19,33.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
35,HDFCLIFE,-0.69,-8.71,52.43,39.15,120007.0,-21848.0,228889.0,811.41,-32.03,36.0,X-LC,16.26,31.0,-0.18,1.45,0.00,X40,ATH,INSURANCE
83,VBL,-0.43,-11.83,53.85,35.66,167057.0,-41618.0,310226.0,669.42,-22.34,36.0,X-LC,7.47,13.0,-0.25,1.96,14.22,X40N,ATH,FMCG

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
19,COLPAL,-0.30,-23.99,84.00,39.86,168160.0,-63175.0,200190.0,3683.41,-8.09,42.0,X-MC,1.52,62.0,-0.38,1.27,13.24,XY25,ATH,FMCG
11,BERGEPAINT,2.48,2.38,22.40,25.32,59110.0,6137.0,263886.0,680.00,-3.12,68.0,X-MC,2.38,68.0,0.10,1.67,38.38,XY24,NTT,PAINTS
23,DMART,-0.45,-1.60,33.56,31.42,102958.0,-5001.0,306789.0,5391.45,-18.18,52.0,X-LC,2.90,14.0,-0.05,1.94,10.71,X40N,ATH,FMCG
8,BAJAJHLDNG,-0.72,3.02,24.48,28.24,64564.0,7736.0,263741.0,14274.15,-5.41,64.0,X-LC,3.04,28.0,0.12,1.67,32.74,X40,ATH,FINANCE
26,GILLETTE,-0.70,-10.22,44.50,29.72,101433.0,-25956.0,227940.0,10978.86,-31.02,41.0,X-SC,3.31,83.0,-0.26,1.44,4.75,X40,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
35,HDFCLIFE,-0.69,-8.71,52.43,39.15,120007.0,-21848.0,228889.0,811.41,-32.03,36.0,X-LC,16.26,31.0,-0.18,1.45,0.00,X40,ATH,INSURANCE
28,GODREJCP,-11.16,-16.52,60.08,33.64,125157.0,-41219.0,208318.0,1469.04,-13.54,24.0,X-LC,5.19,32.0,-0.33,1.32,0.00,X40N,ATH,FMCG
57,PGHH,-0.55,-36.79,108.85,32.01,146904.0,-78560.0,134960.0,17616.87,-57.19,33.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
20,DABUR,-1.49,-20.52,80.81,43.70,159319.0,-50916.0,197152.0,735.00,-27.96,37.0,X-MC,9.48,70.0,-0.32,1.25,0.32,XY24,BTT,FMCG
34,HDFCBANK,-0.78,-11.66,48.35,31.05,125198.0,-34179.0,258941.0,1073.00,-26.46,32.0,X-LC,11.68,26.0,-0.27,1.64,0.51,X40,BTT,BANKS

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
10,BATAINDIA,1.74,-54.07,194.38,35.20,114871.0,-69574.0,59096.0,2096.00,-22.45,56.0,X-SC,13.28,91.0,-0.61,0.37,18.73,X40,NTT,FOOTWEAR
62,RELAXO,2.30,-43.77,170.84,52.31,139457.0,-63530.0,81630.0,1176.00,-40.08,64.0,X-SC,12.25,92.0,-0.46,0.52,82.51,X40N,NTT,FOOTWEAR
57,PGHH,-0.55,-36.79,108.85,32.01,146904.0,-78560.0,134960.0,17616.87,-57.19,33.0,X-MC,19.25,57.0,-0.53,0.85,0.00,X40,ATH,FMCG
58,QUESS,2.59,36.23,27.65,73.90,40226.0,38689.0,145482.0,424.00,-26.72,68.0,X-SC,40.48,80.0,0.96,0.92,100.24,XY24,NTT,MISC
2,ACC,-2.00,-40.45,193.57,74.81,309054.0,-108468.0,159660.0,3906.00,-57.90,42.0,X-SC,12.06,85.0,-0.35,1.01,6.66,XY24,BTT,CEMENT

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,-0.72,-23.58,63.18,24.70,191809.0,-93686.0,303592.0,452.00,-59.97,38.0,X-LC,10.92,1.0,-0.49,1.92,0.53,X40,NTT,FMCG
75,TCS,-5.20,-31.93,82.47,24.20,260053.0,-147943.0,315330.0,4230.71,-42.31,50.0,X-LC,15.22,2.0,-0.57,1.99,17.59,X40,ATH,IT
45,INFY,-2.03,-16.96,69.05,40.38,215865.0,-63848.0,312622.0,1972.00,-37.59,58.0,X-LC,16.22,3.0,-0.30,1.98,18.39,X40,NTT,IT
77,TMPV,-3.12,-19.88,78.17,42.75,260605.0,-82725.0,333382.0,600.00,-83.62,45.0,X-LC,5.06,4.0,-0.32,2.11,14.63,XY24,NTT,AUTO
33,HCLTECH,-0.70,-9.32,36.70,23.97,102999.0,-28835.0,280651.0,1853.42,-7.36,67.0,X-LC,12.79,8.0,-0.28,1.77,32.43,X40,ATH,IT

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.37,-25.24,77.76,32.89,44882.0,-19488.0,57718.0,1800.00,-371.71,53.0,L-MC,13.84,258.0,-0.43,0.37,42.30,XR,NTT,BANKS
3,ALKYLAMINE,-2.21,-18.89,137.39,92.54,112507.0,-19074.0,81889.0,4520.85,-13.07,56.0,H-SC,13.81,142.0,-0.17,0.52,55.50,SR,ATH,CHEMICALS
62,RELAXO,2.30,-43.77,170.84,52.31,139457.0,-63530.0,81630.0,1176.00,-40.08,64.0,X-SC,12.25,92.0,-0.46,0.52,82.51,X40N,NTT,FOOTWEAR
12,BOSCH-HCIL,-1.87,-26.51,36.06,-0.01,33869.0,-33882.0,93923.0,2282.00,19117.39,79.0,M-SC,3.07,231.0,-1.00,0.59,59.87,OX40N,BTT,AC
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.20,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
12,BOSCH-HCIL,-1.87,-26.51,36.06,-0.01,33869.0,-33882.0,93923.0,2282.00,19117.39,79.0,M-SC,3.07,231.0,-1.00,0.59,59.87,OX40N,BTT,AC
25,FINCABLES,7.99,65.20,25.85,107.91,63052.0,96269.0,243913.0,1641.55,48.66,79.0,M-SC,17.91,220.0,1.53,1.54,83.50,OX40N,ATH,CABLES
82,VALIANTORG,9.25,-32.40,157.61,74.15,174320.0,-53003.0,110602.0,838.00,-299.00,75.0,H-SC,4.20,145.0,-0.30,0.70,64.59,XR,NTT,CHEMICALS
68,SIEMENS,0.14,7.92,15.74,24.90,31611.0,14735.0,200830.0,4648.66,68.58,71.0,H-LC,12.19,51.0,0.47,1.27,41.70,AR,ATH,ELECTRICAL
11,BERGEPAINT,2.48,2.38,22.40,25.32,59110.0,6137.0,263886.0,680.00,-3.12,68.0,X-MC,2.38,68.0,0.10,1.67,38.38,XY24,NTT,PAINTS

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.60
1     25       44.73
2     50       76.84

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    39.46
LC    37.47
MC    23.09
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
X40      26.31
XY24     24.87
X40N     18.34
XR        9.12
OX40N     7.19
XY25      7.19
AR        6.15
SR        0.85
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    35.40
H-SC    19.28
X-MC    18.80
X-SC     9.90
M-SC     9.77
H-MC     2.73
H-LC     1.27
M-MC     1.19
M-LC     0.80
L-SC     0.51
L-MC     0.37
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.26        -23.64   68.17
IT                  11.03        -36.65  104.47
FINANCE              9.25        -17.00   66.17
AUTO                 8.26         -3.62   40.72
MISC                 6.91        -22.61   75.21
BANKS                6.08        -11.08   58.99
PHARMA               5.78          9.16   16.60
INSURANCE            5.58         -5.29   42.51
PAINTS               5.51        -13.13   32.43
ELECTRICAL           4.14         -7.89   45.67
HEALTHCARE           2.04        -10.60   39.47
AC                   1.81        -11.41   41.62
APPARELS             1.71          0.47   32.96
REFINERIES           1.69        -11.40   48.83
FOOTWEAR             1.67        -66.81  133.69
BREWERIES            1.66         10.58    7.99
CABLES               1.54         39.47   25.85
DURABLES             1.47        -66.75  107.31
TRAVEL               1.46        -93.06  189.73
CERAMICS             1.33        -46.16   90.57
CHEMICALS            1.22        -37.44  149.01
ENGINEERING          1.21        -26.58   84.47
CEMENT               1.01        -67.94  193.57
JEWELLERY            0.97       -108.19  180.53
ENTERTAINMENT        0.67        -80.34  187.89
TEXTILES             0.39        -51.46   94.65
HOTELS               0.37        -95.31  164.20

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3467145.0     20
X40       2065601.0     18
XR        1357579.0     13
X40N      1184465.0     12
AR        1058019.0      8
OX40N      656492.0     10
XY25       563194.0      5
SR         281752.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3302718.0     23
X-LC        2463335.0     20
X-MC        1486201.0     14
M-SC        1369923.0     14
X-SC        1236906.0      9
H-MC         265624.0      2
L-SC         210775.0      2
M-LC         165071.0      1
M-MC          57201.0      1
L-MC          44882.0      1
H-LC          31611.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
X-LC       X40       1191613.0      9
H-SC       XY24       992470.0      5
           AR         929893.0      5
M-SC       XY24       854001.0      6
H-SC       XR         802232.0      7
X-SC       XY24       719923.0      4
X-MC       X40        657684.0      7
X-LC       X40N       527351.0      6
           XY24       436315.0      2
X-MC       X40N       356435.0      3
X-SC       X40N       300679.0      3
H-SC       OX40N      296371.0      4
           SR         281752.0      2
X-MC       XY25       253653.0      2
X-LC       XY25       252340.0      2
H-MC       XY24       246007.0      1
M-SC       OX40N      244809.0      5
X-MC       XY24       218429.0      2
X-SC       X40        216304.0      2
M-SC       XR         194215.0      2
M-LC       XR         165071.0      1
L-SC       OX40N      115312.0      1
           XR          95463.0      1
M-SC       AR          76898.0      1
M-MC       XY25        57201.0      1
X-LC       XR          55716.0      1
L-MC       XR          44882.0      1
H-LC       AR          31611.0      1
H-MC       AR          19617.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 23.0 seconds