<a href="https://colab.research.google.com/github/ankit-rathi/Quantvesting_v2/blob/main/myStocks_Portfolio_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
!pip install pandas==2.2.2 -qq
!pip install pyxirr -qq
!pip install ta -qq
!pip install yfinance==0.2.59 -qq
'''

'\n!pip install pandas==2.2.2 -qq\n!pip install pyxirr -qq\n!pip install ta -qq\n!pip install yfinance==0.2.59 -qq\n'

In [2]:
# import libraries

import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
import yfinance as yfin
import ta
import matplotlib.pyplot as plt
import requests

In [3]:
# notebook start time
import time
import datetime
import pytz

start_time = time.time()

# function to print date timestamp
def print_date_time():
  tz_NY = pytz.timezone('Asia/Kolkata')
  datetime_NY = datetime.datetime.now(tz_NY)
  print("Run date time (IST):", datetime_NY.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
# function to get booked and reserved amount
def get_amt():
  # fetch the JSON data from the URL
  url = "https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioAmts.json"
  response = requests.get(url)
  pf_amts = response.json()  # parse the JSON data

  # extract values from the JSON
  py_booked_amt_dm = pf_amts["py_booked_amt_dm"]
  py_booked_amt_sv = pf_amts["py_booked_amt_sv"]
  cy_booked_amt_dm = pf_amts["cy_booked_amt_dm"]
  cy_booked_amt_sv = pf_amts["cy_booked_amt_sv"]
  reserve_amt_dm = pf_amts["reserve_amt_dm"]
  reserve_amt_sv = pf_amts["reserve_amt_sv"]

  # perform calculations
  py_booked_amt = py_booked_amt_dm + py_booked_amt_sv
  cy_booked_amt = cy_booked_amt_dm + cy_booked_amt_sv
  reserve_amt = reserve_amt_dm + reserve_amt_sv
  total_booked_amt = py_booked_amt + cy_booked_amt

  return total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt

gen_output = 0

In [5]:
# function to format the amount
def format_amt(number):
    abs_number = abs(number)

    if abs_number >= 1_00_00_000:  # Crores
        formatted_amt = f"{number / 1_00_00_000:.2f} C"
    elif abs_number >= 1_00_000:  # Lakhs
        formatted_amt = f"{number / 1_00_000:.2f} L"
    elif abs_number >= 1_000:  # Thousands
        formatted_amt = f"{number / 1_000:.2f} K"
    else:
        formatted_amt = f"{number:.2f}"

    return formatted_amt

# function to set start and end date
def get_start_end_date():
  start_date = (datetime.date.today() + datetime.timedelta(days=-365)).strftime('%Y-%m-%d')
  end_date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
  return start_date, end_date

# function to fetch my portfolio csv
def get_mypfs_df():
  mypfs_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myPortfolioStocks.csv')
  return mypfs_df

# function to fetch my prospects csv
def get_mypps_df():
  mypps_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myProspectsScrips.csv')
  return mypps_df

# function to fetch screener data
def get_myscreen_df():
  myscreen_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myScreenerDB.csv')
  return myscreen_df

# function to fetch momentum data
def get_myinvmt_df():
  myinvmt_df = pd.read_csv('https://raw.githubusercontent.com/ankit-rathi/Tradevesting_v1/main/data/myInvestments.csv')
  return myinvmt_df

# function to get the stock ids
def get_stock_ids(df_pf):
  stock_n100 = df_pf['Symbol'].unique()

  exclude = ['CADILAHC','MMTC', 'MASFIN']

  stock_ids = df_pf[~df_pf['Symbol'].isin(exclude) ]['Symbol'].unique()

  #mypf = mypf[mypf.Forecast.notnull()]
  #stock_ids = mypf['Symbol'].unique()

  #stock_ids.sort()
  return stock_ids

# get features from screener data
def get_screener_features():
  myscreen_df = get_myscreen_df()
  cols = ['Symbol', 'EPS', 'MedPE', 'ROCE%', 'ROE%', 'CapType']
  return myscreen_df[cols]

# get relative strength
def get_relative_strength(stock_list):

    # Dictionary to store stock tickers and their corresponding percentage price change
    stock_changes = {}

    # Loop through each stock and fetch its price data
    for stock in stock_list:
        try:
            # Download the stock data for the given date range
            stock_data = yfin.Ticker(stock + '.NS').history(period='1mo', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

            # Calculate the percentage change for the stock
            if len(stock_data) > 0:
                start_price = stock_data['Close'].iloc[0]
                end_price = stock_data['Close'].iloc[-1]
                percent_change = round(((end_price - start_price) / start_price) * 100, 2)
                stock_changes[stock] = percent_change
            else:
                stock_changes[stock] = np.nan  # If no data is available, set to NaN

        except Exception as e:
            print(f"Error fetching data for {stock}: {e}")
            stock_changes[stock] = np.nan

    # Create a DataFrame with stock tickers and their percentage changes
    df = pd.DataFrame(list(stock_changes.items()), columns=['Symbol', 'Percent_Change'])

    # Drop any stocks with missing data (NaN values)
    df = df.dropna()

    # Calculate the percentile rank based on percentage change
    df['RSP'] = round(df['Percent_Change'].rank(pct=True) * 100, 2)
    cols = ['Symbol', 'RSP']
    df = df[cols]
    # Sort by percentile rank (optional)
    df = df.sort_values(by='RSP', ascending=False).reset_index(drop=True)

    return df

In [6]:
# function to get stock technicals
def stock_prec_dev(stock_symbol):
    #stock_symbol = 'ULTRACEMCO.NS'
    short_window = 20
    mid_window = 50
    long_window = 200
    moving_avg = 'SMA'

    start = datetime.datetime(*map(int, start_date.split('-')))
    end = datetime.datetime(*map(int, end_date.split('-')))

    stock_df = yfin.Ticker(stock_symbol + '.NS').history(period='max', interval='1d')[map(str.title, ['open', 'close', 'low', 'high', 'volume'])]

    stock_df['Max'] = round(max(stock_df['Close']),2)
    stock_df = stock_df[(stock_df.index <= end_date) & (stock_df.index >= start_date)]
    stock_df['200_SMA'] = round(stock_df['Close'].rolling(window = 200, min_periods = 1).mean(),0)
    stock_df['Dev%_200'] = round((stock_df['Close'] - stock_df['200_SMA'])*100/stock_df['200_SMA'],2)
    stock_df.dropna(axis = 0, inplace = True) # remove any null rows

    stock_df['20_SMA'] = stock_df['Close'].rolling(window=20).mean()
    stock_df['50_SMA'] = stock_df['Close'].rolling(window=50).mean()
    stock_df['Symbol'] = stock_symbol

    stock_df['Close'] = round(stock_df['Close'],2)
    stock_df['Min'] = round(min(stock_df['Close']),2)
    stock_df['RSI_14'] = ta.momentum.RSIIndicator(close=stock_df['Close'], window=14).rsi()
    stock_df['RSI_14'] = round(stock_df['RSI_14'],0)
    stock_df['Prev_Close'] = stock_df['Close'].shift(1)
    stock_df.drop(['Open', 'Low', 'High', 'Volume'], axis=1, inplace=True)
    stock_df = stock_df.tail(1)

    max_SMA = max(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    min_SMA = min(stock_df['20_SMA'].item(), stock_df['50_SMA'].item(), stock_df['200_SMA'].item())
    ABS_Spread = max_SMA - min_SMA
    stock_df['Spread%'] = round((ABS_Spread / stock_df['200_SMA'].item()) * 100,2)

    return stock_df

# function to compute stock attributes
def get_common_features(stock_ids, df_mypf):

  df_prec_dev = pd.DataFrame()
  df_tmp = get_screener_features()
  df_rs = get_relative_strength(stock_ids)

  for stock_id in stock_ids:
      tmp = stock_prec_dev(stock_id)
      tmp = tmp.reset_index()
      df_prec_dev = pd.concat([df_prec_dev, tmp], ignore_index = True)
  df_prec_dev = pd.merge(df_prec_dev, df_mypf, on= 'Symbol')
  df_prec_dev = pd.merge(df_prec_dev, df_tmp, on= 'Symbol', how='left')
  df_prec_dev = pd.merge(df_prec_dev, df_rs, on= 'Symbol', how='left')
  #print(df_prec_dev.columns)
  df_prec_dev['Curr_PE'] = round(df_prec_dev['Close']/df_prec_dev['EPS'],1)
  df_prec_dev['Dev%_PE'] = round((df_prec_dev['Curr_PE'] - df_prec_dev['MedPE'])*100/df_prec_dev['MedPE'],2)
  df_prec_dev['Conviction'] = df_prec_dev['Conviction'] + '-' + df_prec_dev['CapType']
  return df_prec_dev

# function to arrange stock features
def arrange_features(df_stocks, common_cols, diff_cols):
  df_stocks_common = df_stocks[common_cols].drop_duplicates()
  df_stocks_diff = df_stocks[diff_cols]
  df_stocks_diff['Investment'] = df_stocks_diff['AvgCost'] * df_stocks_diff['Shares']
  df_stocks_diff = df_stocks_diff.groupby(['Symbol'])[['Shares', 'Investment']].aggregate(['sum']).reset_index()
  df_stocks_diff.columns = ['Symbol', 'Shares', 'Investment']
  df_stocks_diff['AvgCost'] = round(df_stocks_diff['Investment']/df_stocks_diff['Shares'],2)
  df_stocks = pd.merge(df_stocks_diff, df_stocks_common, on='Symbol')
  return df_stocks

# plot fact distribution across dimension
def plot_pie_chart(df, dimension, fact):
  # grouping the data by category and calculating the sum of fact for each type
  grouped_data = df.groupby(dimension)[fact].sum()

  # sorting the grouped data in descending order
  grouped_data = grouped_data.sort_values(ascending=False)

  # creating a pie chart
  grouped_data.plot.pie(autopct='%1.1f%%', startangle=90, figsize=(6, 6))

  # adding a title and displaying the plot
  plt.title(f'{dimension} {fact} Distribution')
  plt.ylabel('')  # To hide the y-label
  plt.show()

In [7]:
# function to get portfolio features

def get_portfolio_features(df_common_features):

  print_date_time()
  print('-------------------')

  #df_common_features["Target"] = df_common_features["Target"].fillna(df_common_features["Max"])
  df_common_features['NTT'] = np.where(df_common_features['Strategy']== 'NTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['LTT'] = np.where(df_common_features['Strategy']== 'BTT', df_common_features["Target"], df_common_features['Max'])
  df_common_features['BOL'] = df_common_features['Min']

  tmp_df = df_common_features[df_common_features['Symbol'].isin(mypf_df[mypf_df['InPortfolio'] != 'NA'].Symbol.values)]
  print('qualified stocks: '+str(len(tmp_df['Symbol'].unique())))
  tmp_df1 = tmp_df[tmp_df['LatestQtr'] == 1]
  print('with latest results: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df1 = tmp_df1[tmp_df1['StarStock'] == 1]
  print('still star stocks: '+str(len(tmp_df1['Symbol'].unique())))
  tmp_df['Investment'] = tmp_df['AvgCost'] * tmp_df['Shares']
  tmp_df['Current'] = round(tmp_df['Close'] * tmp_df['Shares'],0)
  tmp_df['Previous'] = tmp_df['Prev_Close'] * tmp_df['Shares']
  tmp_df['EstimatedST'] = tmp_df['NTT'] * tmp_df['Shares']
  tmp_df['EstimatedLT'] = tmp_df['LTT'] * tmp_df['Shares']
  tmp_df['Current P/L'] = round((tmp_df['Current'] - tmp_df['Investment']),0)
  tmp_df['Today P/L%'] = round((tmp_df['Current'] - tmp_df['Previous'])*100/tmp_df['Previous'],2)
  tmp_df['Current P/L%'] = round((tmp_df['Current'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedST P/L%'] = round((tmp_df['EstimatedST'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['EstimatedLT P/L%'] = round((tmp_df['EstimatedLT'] - tmp_df['Investment'])*100/tmp_df['Investment'],2)
  tmp_df['NTT%'] = round((tmp_df['NTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['LTT%'] = round((tmp_df['LTT'] - tmp_df['Close'])*100/tmp_df['Close'],2)
  tmp_df['Gained%'] = round((tmp_df['Close'] - tmp_df['BOL'])*100/tmp_df['BOL'],2)
  investment = round(sum(tmp_df['AvgCost']*tmp_df['Shares']),0)
  current = round(sum(tmp_df['Close']*tmp_df['Shares']),0)
  tmp_df['InitAlloc%'] = round(tmp_df['Investment']*100/investment,2)
  tmp_df['CurrAlloc%'] = round(tmp_df['Current']*100/current,2)
  tmp_df['FTT'] = tmp_df['LTT']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT'] = tmp_df['NTT']
  tmp_df['FTT%'] = tmp_df['LTT%']
  tmp_df.loc[tmp_df['Strategy'] == 'NTT', 'FTT%'] = tmp_df['NTT%']
  tmp_df['FTT Amt'] = round(tmp_df['FTT%'] * tmp_df['Current']/100,0)
  tmp_df['OTT%'] = round((tmp_df['FTT'] - tmp_df['AvgCost'])*100/tmp_df['AvgCost'],2)
  tmp_df['RRR Ind'] = round(tmp_df['Current P/L']/tmp_df['FTT Amt'],2)
  tmp_df['Risk Ind'] = round(tmp_df['Current P/L%']*tmp_df['CurrAlloc%'],0)

  return tmp_df

# function to print portfolio features
def print_portfolio_stats(df_portfolio_features, myinvmt_df):
  from pyxirr import xirr

  total_booked_amt, reserve_amt, cy_booked_amt, py_booked_amt = get_amt()

  dates = myinvmt_df['Date'].values
  dates = np.append(dates, datetime.date.today().strftime('%d-%b-%y'))
  investment = myinvmt_df['Investment'].values
  dates= pd.to_datetime(dates)

  current = round(sum(df_portfolio_features['Close']*df_portfolio_features['Shares']),0) + reserve_amt
  investment_xirr = np.append(investment, current)
  cagr = round(xirr(pd.DataFrame({"dates": dates, "amounts": investment_xirr}))*100,2)

  investment = -sum(investment)
  invested = round(sum(df_portfolio_features['AvgCost']*df_portfolio_features['Shares']),0) + reserve_amt
  previous = round(sum(df_portfolio_features['Prev_Close']*df_portfolio_features['Shares']),0) + reserve_amt
  cy_invested = investment + py_booked_amt

  today_pnl_amount = current-previous
  today_pnl_percentage = round((current-previous)*100/previous,2)

  curr_pnl_amount = current-invested
  curr_pnl_percentage = round((curr_pnl_amount)*100/(cy_invested),2)

  cy_pnl_amount = cy_booked_amt + curr_pnl_amount
  cy_pnl_percentage = round((cy_pnl_amount)*100/cy_invested,2)

  overall_pnl_amount = total_booked_amt + curr_pnl_amount
  overall_pnl_percentage = round((overall_pnl_amount)*100/investment,2)

  estimate_st = round(sum(df_portfolio_features['FTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_st_pnl_amount = estimate_st-current
  est_st_pnl_percentage = round((est_st_pnl_amount)*100/current,2)

  estimate_lt = round(sum(df_portfolio_features['LTT']*df_portfolio_features['Shares']),0)  + reserve_amt
  est_lt_pnl_amount = estimate_lt-current
  est_lt_pnl_percentage = round((est_lt_pnl_amount)*100/current,2)

  total_profit = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] > 0]['Investment']),0)
  total_loss = round(sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Current']) - sum(df_portfolio_features[df_portfolio_features['Current P/L%'] < 0]['Investment']),0)

  cy_booked_percentage = round((cy_booked_amt)*100/current,2)
  py_booked_percentage = round((py_booked_amt)*100/investment,2)
  total_booked_percentage = round((total_booked_amt)*100/investment,2)

  print('-------------------')
  print('Initial Investment: ', format_amt(investment))
  print('CY Investment: ', format_amt(cy_invested))
  print('Reserve: ', format_amt(reserve_amt))
  print('Current: ',  format_amt(current))
  print('-------------------')
  print('Today PnL: '+ '{} ({}%)'.format(format_amt(today_pnl_amount), today_pnl_percentage))
  print('Current PnL: '+ '{} ({}%)'.format(format_amt(curr_pnl_amount), curr_pnl_percentage))
  print('CY Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(cy_pnl_amount), cy_pnl_percentage))
  print('-------------------')
  print('Total profit: ', format_amt(total_profit))
  print('Total loss: ', format_amt(total_loss))
  print('-------------------')
  print('Total Booked + Current PnL: '+ '{} ({}%)'.format(format_amt(overall_pnl_amount), overall_pnl_percentage))
  print('Total Booked PnL: '+ '{} ({}%)'.format(format_amt(total_booked_amt), total_booked_percentage))
  print('Curr Year Booked PnL: '+ '{} ({}%)'.format(format_amt(cy_booked_amt), cy_booked_percentage))
  print('Prev Year Booked PnL: '+ '{} ({}%)'.format(format_amt(py_booked_amt), py_booked_percentage))
  print('===================')
  print('Est FTT: ',  format_amt(estimate_st))
  print('Est FTT PnL: '+ '{} ({}%)'.format(format_amt(est_st_pnl_amount), est_st_pnl_percentage))

  print('===================')
  print('Deployed: ', format_amt(investment))

  print('Current: ', format_amt(current))

  print('CAGR/XIRR %: '+'{}%'.format(cagr))

In [8]:
# get start and end date
start_date, end_date = get_start_end_date()

# get portfolio and prospects data
mypfs_df = get_mypfs_df()
mypps_df = get_mypps_df()
myinvmt_df = get_myinvmt_df()

# merge above datasets
mypf_df = pd.merge(mypfs_df, mypps_df, on="Symbol")

# seggregate dm and sv portfolio
dm_pf = mypf_df[mypf_df['InPortfolio'] == 'DM']
sv_pf = mypf_df[mypf_df['InPortfolio'] == 'SV']

# build portfolio stock dataframe
dm_stocks = get_stock_ids(dm_pf)
sv_stocks = get_stock_ids(sv_pf)
df_stocks = pd.concat([dm_pf,sv_pf], ignore_index = True)

# arrange common and diff stock features
common_cols = ['Symbol', 'Target', 'Criteria', 'Strategy', 'CumlRnk', 'LatestQtr', 'StarStock', 'Conviction', 'Category', 'InFolio', 'XIRR', 'MBQ']
diff_cols = ['Symbol', 'AvgCost', 'Shares']
df_stocks = arrange_features(df_stocks, common_cols, diff_cols)

# get common features
stock_ids = df_stocks['Symbol'].values
df_common_features = get_common_features(stock_ids, df_stocks)

df_common_features.reset_index(drop=True, inplace=True)
df_common_features.drop(['Date'], axis=1, inplace=True)
# get and print portfolio features
df_portfolio_features = get_portfolio_features(df_common_features)

print_portfolio_stats(df_portfolio_features, myinvmt_df)

df = df_portfolio_features
#plot_pie_chart(df, 'CapType', 'Current')
list_ox40n = list(df[df['MBQ'].str.contains('OX40N', na=False)]['Symbol'].values)

Run date time (IST): 2026-05-08 13:51:32
-------------------
qualified stocks: 92
with latest results: 31
still star stocks: 20
-------------------
Initial Investment:  1.40 C
CY Investment:  1.82 C
Reserve:  1.49 K
Current:  1.52 C
-------------------
Today PnL: 19.82 K (0.13%)
Current PnL: -30.83 L (-16.9%)
CY Booked + Current PnL: -28.75 L (-15.76%)
-------------------
Total profit:  2.19 L
Total loss:  -33.02 L
-------------------
Total Booked + Current PnL: 14.12 L (10.12%)
Total Booked PnL: 44.95 L (32.22%)
Curr Year Booked PnL: 2.08 L (1.37%)
Prev Year Booked PnL: 42.87 L (30.73%)
===================
Est FTT:  2.55 C
Est FTT PnL: 1.03 C (67.67%)
===================
Deployed:  1.40 C
Current:  1.52 C
CAGR/XIRR %: 4.36%

In [9]:
# top 5 near their targets
cols = ['Symbol', 'Today P/L%', 'Current P/L%', 'FTT%', 'OTT%', 'FTT Amt', 'Current P/L', 'Current', 'FTT', 'Dev%_PE', 'RSI_14','Conviction', 'Spread%',  'CumlRnk', 'RRR Ind', 'CurrAlloc%', 'Gained%', 'Criteria', 'Strategy', 'Category']
df_tmp = df_portfolio_features[~df_portfolio_features['Symbol'].isin(['ENRIN','BLUSPRING','DIGITIDE'])]
df_tmp = df_tmp.sort_values(by = 'FTT Amt', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
55,MASFIN,-0.09,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.41,0.68,34.50,XR,ATH,FINANCE
59,PIDILITIND,2.68,5.54,12.15,18.37,18095.0,7820.0,148930.0,1670.26,-26.08,69.0,X-LC,5.41,5.0,0.43,0.98,16.94,X40,ATH,CHEMICALS
53,M&M,-1.11,8.16,14.07,23.38,21105.0,11322.0,150003.0,3802.40,-8.17,60.0,X-LC,7.58,25.0,0.54,0.98,13.73,X40N,ATH,AUTO
51,KOTAKBANK,-0.55,0.81,20.13,21.11,28102.0,1128.0,139601.0,453.24,-13.31,50.0,X-LC,7.47,12.0,0.04,0.92,6.76,X40,ATH,BANKS
83,TTKPRESTIG,-1.94,-31.97,47.13,0.09,32312.0,-32218.0,68559.0,770.00,59.23,57.0,M-SC,17.27,250.0,-1.00,0.45,22.08,OX40N,NTT,DURABLES

In [10]:
# top 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
75,SURYODAY,8.02,-0.72,23.92,23.03,42526.0,-1285.0,177786.0,216.00,92.98,83.0,H-SC,9.59,166.0,-0.03,1.17,51.62,XR,NTT,BANKS
11,BERGEPAINT,6.18,-4.47,31.17,25.32,76753.0,-11509.0,246240.0,680.00,-9.74,76.0,X-MC,12.91,68.0,-0.15,1.62,28.16,XY24,NTT,PAINTS
20,DABUR,4.03,-4.40,50.32,43.70,119329.0,-10927.0,237141.0,735.00,-13.19,69.0,X-MC,9.44,70.0,-0.09,1.56,19.13,XY24,BTT,FMCG
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES
62,RAJOOENG,3.73,-39.77,131.78,39.61,81361.0,-40760.0,61740.0,143.10,-59.29,50.0,H-SC,22.77,136.0,-0.50,0.41,32.26,AR,ATH,MISC

In [11]:
# bottom 5 today
df_tmp = df_portfolio_features.sort_values(by = 'Today P/L%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
67,ROUTE,-3.68,-57.77,298.18,68.16,167565.0,-76870.0,56196.0,2215.45,-65.82,62.0,H-SC,27.14,141.0,-0.46,0.37,33.88,SR,ATH,IT
88,VOLTAS,-2.82,3.69,40.03,45.20,79584.0,7068.0,198810.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.31,8.97,XY25,NTT,AC
66,REPCOHOME,-2.37,-12.80,117.69,89.82,294020.0,-36679.0,249826.0,880.00,-56.78,53.0,H-SC,5.85,161.0,-0.12,1.64,20.10,XY24,NTT,FINANCE
89,WHIRLPOOL,-2.26,-23.34,137.31,81.92,120837.0,-26795.0,88003.0,2270.00,-55.05,58.0,M-SC,17.32,210.0,-0.22,0.58,23.62,XR,NTT,DURABLES
22,DIXON,-2.24,-21.31,75.28,37.92,154489.0,-55579.0,205219.0,18931.72,-66.52,47.0,X-MC,22.63,54.0,-0.36,1.35,11.66,X40N,ATH,IT

In [12]:
# top 5 to exit based on CumlRnk
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > -1) & (df_tmp['Current P/L%'] < 1)].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
73,SONACOMS,0.23,0.34,38.62,39.09,39199.0,341.0,101500.0,804.02,-20.47,55.0,M-MC,19.77,193.0,0.01,0.67,43.59,AR,ATH,AUTO
75,SURYODAY,8.02,-0.72,23.92,23.03,42526.0,-1285.0,177786.0,216.00,92.98,83.0,H-SC,9.59,166.0,-0.03,1.17,51.62,XR,NTT,BANKS
91,ZYDUSLIFE,0.08,-0.76,36.67,35.63,76263.0,-1602.0,207972.0,1286.17,-13.51,59.0,H-MC,3.55,120.0,-0.02,1.37,9.35,AR,ATH,PHARMA

In [13]:
# OX40N stocks to exit
df_tmp = df_portfolio_features[(df_portfolio_features['Symbol'].isin(list_ox40n))].sort_values(by = 'Current P/L%', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES
72,SIS,-0.11,-8.66,32.76,21.26,33223.0,-9618.0,101414.0,528.00,2412.95,75.0,H-SC,10.72,168.0,-0.29,0.67,50.79,OX40N,NTT,MISC
16,CERA,3.05,-26.48,68.50,23.89,88590.0,-46574.0,129329.0,9475.00,-29.12,71.0,H-SC,11.14,153.0,-0.53,0.85,24.28,OX40N,NTT,CERAMICS
50,KANSAINER,1.48,-28.35,58.38,13.47,112797.0,-76455.0,193212.0,340.00,-38.33,68.0,H-SC,16.04,162.0,-0.68,1.27,34.96,XY24,NTT,PAINTS
83,TTKPRESTIG,-1.94,-31.97,47.13,0.09,32312.0,-32218.0,68559.0,770.00,59.23,57.0,M-SC,17.27,250.0,-1.00,0.45,22.08,OX40N,NTT,DURABLES

In [14]:
# top 5 to book for rotation
df_tmp = df_portfolio_features[(df_portfolio_features['Current P/L%'] > 20) ].sort_values(by = 'CumlRnk', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES

In [15]:
# top 5 to monitor for exit
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['Current P/L%'] > 0) ].sort_values(by = 'Dev%_PE', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
74,STARHEALTH,2.27,2.41,43.80,47.26,126094.0,6762.0,287885.0,761.00,61.57,67.0,H-SC,9.68,173.0,0.05,1.89,49.09,XY24,NTT,INSURANCE
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES
68,SATIN,0.95,14.00,33.19,51.83,104534.0,38673.0,314957.0,274.00,2.50,79.0,H-SC,16.69,159.0,0.37,2.07,53.43,XY24,NTT,FINANCE
55,MASFIN,-0.09,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.41,0.68,34.50,XR,ATH,FINANCE
73,SONACOMS,0.23,0.34,38.62,39.09,39199.0,341.0,101500.0,804.02,-20.47,55.0,M-MC,19.77,193.0,0.01,0.67,43.59,AR,ATH,AUTO

In [16]:
# top 5 to book for rotation from weak conviction
df_tmp = df_portfolio_features[~df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[~df_tmp['Criteria'].isin(['XY25','XY24','X40', 'X40N'])].sort_values(by = 'RRR Ind', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES
55,MASFIN,-0.09,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.41,0.68,34.50,XR,ATH,FINANCE
73,SONACOMS,0.23,0.34,38.62,39.09,39199.0,341.0,101500.0,804.02,-20.47,55.0,M-MC,19.77,193.0,0.01,0.67,43.59,AR,ATH,AUTO
91,ZYDUSLIFE,0.08,-0.76,36.67,35.63,76263.0,-1602.0,207972.0,1286.17,-13.51,59.0,H-MC,3.55,120.0,-0.02,1.37,9.35,AR,ATH,PHARMA
75,SURYODAY,8.02,-0.72,23.92,23.03,42526.0,-1285.0,177786.0,216.00,92.98,83.0,H-SC,9.59,166.0,-0.03,1.17,51.62,XR,NTT,BANKS

In [17]:
# top 5 to accumulate based on lowest RSI_14
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'RSI_14', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
33,HCLTECH,1.12,-22.35,56.47,21.51,106088.0,-54058.0,187866.0,1872.35,-18.53,32.0,X-LC,12.34,8.0,-0.51,1.23,1.12,X40,ATH,IT
79,TCS,-0.81,-30.07,81.01,26.57,262434.0,-139321.0,323952.0,4311.59,-40.68,37.0,X-LC,14.25,2.0,-0.53,2.13,1.10,X40,ATH,IT
45,INFY,1.09,-19.98,67.77,34.24,169669.0,-62528.0,250360.0,1972.00,-36.87,38.0,X-LC,15.84,3.0,-0.37,1.64,2.02,X40,NTT,IT
88,VOLTAS,-2.82,3.69,40.03,45.20,79584.0,7068.0,198810.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.31,8.97,XY25,NTT,AC
84,UNITDSPR,-0.09,-6.07,28.57,20.77,62836.0,-14208.0,219936.0,1644.00,-16.64,42.0,X-MC,2.52,64.0,-0.23,1.44,4.91,X40N,NTT,BREWERIES

In [18]:
# top 5 to accumulate based on Spread and CumlRnk
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])]
df_tmp = df_tmp[(df_tmp['CumlRnk'] < 100)].sort_values(by = 'Spread%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
88,VOLTAS,-2.82,3.69,40.03,45.20,79584.0,7068.0,198810.0,1856.00,18.70,40.0,X-MC,2.43,79.0,0.09,1.31,8.97,XY25,NTT,AC
84,UNITDSPR,-0.09,-6.07,28.57,20.77,62836.0,-14208.0,219936.0,1644.00,-16.64,42.0,X-MC,2.52,64.0,-0.23,1.44,4.91,X40N,NTT,BREWERIES
65,RELIANCE,-0.75,-8.50,36.94,25.30,67924.0,-17086.0,183877.0,1952.00,-10.80,57.0,X-LC,3.40,21.0,-0.25,1.21,9.26,XY25,BTT,REFINERIES
39,ICICIGI,-1.62,-3.58,23.77,19.34,45865.0,-7157.0,192952.0,2252.93,-18.85,54.0,X-MC,4.62,66.0,-0.16,1.27,7.77,X40,ATH,INSURANCE
19,COLPAL,0.76,-17.10,70.69,41.51,154345.0,-45025.0,218340.0,3726.84,0.43,64.0,X-MC,5.12,62.0,-0.29,1.43,22.07,XY25,ATH,FMCG

In [19]:
# top 5 to accumulate based on lowest Gained%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'Gained%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
79,TCS,-0.81,-30.07,81.01,26.57,262434.0,-139321.0,323952.0,4311.59,-40.68,37.0,X-LC,14.25,2.0,-0.53,2.13,1.10,X40,ATH,IT
33,HCLTECH,1.12,-22.35,56.47,21.51,106088.0,-54058.0,187866.0,1872.35,-18.53,32.0,X-LC,12.34,8.0,-0.51,1.23,1.12,X40,ATH,IT
45,INFY,1.09,-19.98,67.77,34.24,169669.0,-62528.0,250360.0,1972.00,-36.87,38.0,X-LC,15.84,3.0,-0.37,1.64,2.02,X40,NTT,IT
84,UNITDSPR,-0.09,-6.07,28.57,20.77,62836.0,-14208.0,219936.0,1644.00,-16.64,42.0,X-MC,2.52,64.0,-0.23,1.44,4.91,X40N,NTT,BREWERIES
1,ABBOTINDIA,-0.17,-10.58,32.04,18.07,51242.0,-18925.0,159930.0,35195.00,-23.83,63.0,X-MC,11.23,58.0,-0.37,1.05,5.86,X40,ATH,PHARMA

In [20]:
# top 5 to accumulate based on lowest CurrAlloc%
df_tmp = df_portfolio_features[df_portfolio_features['Conviction'].isin(['X-LC','H-LC','X-MC','X-SC'])].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
64,RELAXO,0.43,-60.30,283.62,52.31,163453.0,-87529.0,57631.0,1176.00,-57.70,55.0,X-SC,24.40,92.0,-0.54,0.38,28.86,X40N,NTT,FOOTWEAR
10,BATAINDIA,-1.11,-53.55,191.09,35.20,114203.0,-68906.0,59764.0,2096.00,-21.59,48.0,X-SC,26.14,91.0,-0.60,0.39,18.53,X40,NTT,FOOTWEAR
60,QUESS,0.38,-7.84,88.70,73.90,87298.0,-8374.0,98419.0,424.00,-50.41,74.0,X-SC,13.56,80.0,-0.10,0.65,34.17,XY24,NTT,MISC
28,GODREJCP,1.01,-6.29,40.99,32.12,57084.0,-9350.0,139264.0,1476.34,-1.47,43.0,X-LC,6.34,32.0,-0.16,0.91,6.33,X40N,ATH,FMCG
51,KOTAKBANK,-0.55,0.81,20.13,21.11,28102.0,1128.0,139601.0,453.24,-13.31,50.0,X-LC,7.47,12.0,0.04,0.92,6.76,X40,ATH,BANKS

In [21]:
# top 5 to accumulate based on CumlRnk
df_tmp = df_portfolio_features.sort_values(by = 'CumlRnk', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
47,ITC,0.08,-18.96,46.92,19.06,129337.0,-64512.0,275654.0,452.00,-55.52,51.0,X-LC,15.57,1.0,-0.50,1.81,6.93,X40,NTT,FMCG
79,TCS,-0.81,-30.07,81.01,26.57,262434.0,-139321.0,323952.0,4311.59,-40.68,37.0,X-LC,14.25,2.0,-0.53,2.13,1.10,X40,ATH,IT
45,INFY,1.09,-19.98,67.77,34.24,169669.0,-62528.0,250360.0,1972.00,-36.87,38.0,X-LC,15.84,3.0,-0.37,1.64,2.02,X40,NTT,IT
81,TMPV,-0.99,-19.03,68.68,36.58,197879.0,-67724.0,288117.0,600.00,-83.62,56.0,X-LC,5.16,4.0,-0.34,1.89,20.09,XY24,NTT,AUTO
59,PIDILITIND,2.68,5.54,12.15,18.37,18095.0,7820.0,148930.0,1670.26,-26.08,69.0,X-LC,5.41,5.0,0.43,0.98,16.94,X40,ATH,CHEMICALS

In [22]:
# top 5 for average up
df_tmp = df_portfolio_features[(df_portfolio_features['Dev%_200'] > 5)].sort_values(by = 'CurrAlloc%', ascending=True)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
44,INDUSINDBK,0.03,-30.07,90.02,32.89,48604.0,-23214.0,53993.0,1800.00,-354.20,68.0,L-MC,5.84,258.0,-0.48,0.35,32.90,XR,NTT,BANKS
12,BOSCH-HCIL,-0.57,-36.99,58.69,-0.01,47262.0,-47277.0,80528.0,2282.00,16378.26,61.0,M-SC,4.79,231.0,-1.00,0.53,37.07,OX40N,BTT,AC
72,SIS,-0.11,-8.66,32.76,21.26,33223.0,-9618.0,101414.0,528.00,2412.95,75.0,H-SC,10.72,168.0,-0.29,0.67,50.79,OX40N,NTT,MISC
73,SONACOMS,0.23,0.34,38.62,39.09,39199.0,341.0,101500.0,804.02,-20.47,55.0,M-MC,19.77,193.0,0.01,0.67,43.59,AR,ATH,AUTO
55,MASFIN,-0.09,6.23,14.44,21.57,15030.0,6105.0,104085.0,397.04,-8.31,69.0,H-SC,4.37,167.0,0.41,0.68,34.50,XR,ATH,FINANCE

In [23]:
# top 5 RSP
df_tmp = df_portfolio_features.sort_values(by = 'RSP', ascending=False)
df_tmp[cols].head()

,Symbol,Today P/L%,Current P/L%,FTT%,OTT%,FTT Amt,Current P/L,Current,FTT,Dev%_PE,RSI_14,Conviction,Spread%,CumlRnk,RRR Ind,CurrAlloc%,Gained%,Criteria,Strategy,Category
72,SIS,-0.11,-8.66,32.76,21.26,33223.0,-9618.0,101414.0,528.00,2412.95,75.0,H-SC,10.72,168.0,-0.29,0.67,50.79,OX40N,NTT,MISC
25,FINCABLES,3.87,43.12,45.27,107.91,95660.0,63666.0,211310.0,1641.55,28.87,81.0,M-SC,18.51,220.0,0.67,1.39,58.98,OX40N,ATH,CABLES
68,SATIN,0.95,14.00,33.19,51.83,104534.0,38673.0,314957.0,274.00,2.50,79.0,H-SC,16.69,159.0,0.37,2.07,53.43,XY24,NTT,FINANCE
75,SURYODAY,8.02,-0.72,23.92,23.03,42526.0,-1285.0,177786.0,216.00,92.98,83.0,H-SC,9.59,166.0,-0.03,1.17,51.62,XR,NTT,BANKS
77,TANLA,-1.13,-35.86,238.73,117.25,414567.0,-97106.0,173655.0,1922.32,-35.11,66.0,H-SC,16.89,147.0,-0.23,1.14,52.04,AR,ATH,IT

In [24]:
# Top N allocation
df_tmp = df_portfolio_features.sort_values(by = 'CurrAlloc%', ascending=False)
top_n_values = [10, 25, 50]

sum_df = pd.DataFrame({
    'Top_N': top_n_values,
    'Sum_Alloc%': [df_tmp['CurrAlloc%'].head(n).sum() for n in top_n_values]
})

sum_df

   Top_N  Sum_Alloc%
0     10       19.02
1     25       42.41
2     50       72.64

In [25]:
# market-cap-wise allocation
df_tmp = df_portfolio_features[cols]
df_tmp.groupby(df_tmp['Conviction'].str[-2:])['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
SC    43.01
LC    31.29
MC    25.75
Name: CurrAlloc%, dtype: float64

In [26]:
# criteria-wise allocation
df_portfolio_features.groupby('Criteria')['CurrAlloc%'].sum().sort_values(ascending=False)

Criteria
XY24     27.48
X40      25.40
X40N     16.62
XR        9.20
OX40N     6.99
AR        6.75
XY25      6.75
SR        0.86
Name: CurrAlloc%, dtype: float64

In [27]:
# conviction-wise allocation
df_portfolio_features.groupby('Conviction')['CurrAlloc%'].sum().sort_values(ascending=False)

Conviction
X-LC    29.14
H-SC    22.56
X-MC    20.85
M-SC    10.15
X-SC     9.76
H-MC     2.58
M-MC     1.97
H-LC     1.25
M-LC     0.90
L-SC     0.54
L-MC     0.35
Name: CurrAlloc%, dtype: float64

In [28]:
# sector-wise stats
df_tmp = df_portfolio_features.groupby('Category')[['CurrAlloc%', 'Current', 'Current P/L', 'FTT Amt']].sum().sort_values(by=['Current', 'Current P/L'], ascending=False)
df_tmp['Current P/L%'] = round(df_tmp['Current P/L'] * 100 / df_tmp['Current'], 2)
df_tmp['FTT%'] = round(df_tmp['FTT Amt'] * 100 / df_tmp['Current'], 2)
cols = ['CurrAlloc%', 'Current P/L%', 'FTT%']
df_tmp[cols].sort_values(by=['CurrAlloc%'], ascending=False)

               CurrAlloc%  Current P/L%    FTT%
Category
FMCG                15.39        -12.90   52.73
FINANCE             10.81        -11.97   60.68
IT                  10.32        -43.26  115.39
MISC                 7.18        -22.94   76.34
AUTO                 6.63         -8.25   48.83
BANKS                5.69         -4.88   53.38
PAINTS               5.39        -20.01   40.86
INSURANCE            5.38         -1.03   35.41
PHARMA               4.83         -0.81   33.21
ELECTRICAL           3.98        -16.66   58.18
CHEMICALS            2.14        -25.06   99.59
HEALTHCARE           1.95        -20.48   51.92
AC                   1.84        -14.39   45.41
TRAVEL               1.72        -70.78  156.29
DURABLES             1.71        -48.28   84.35
FOOTWEAR             1.70        -70.08  138.27
APPARELS             1.70         -3.87   39.31
BREWERIES            1.44         -6.46   28.57
REALTY               1.40         -4.13   21.23
CABLES               1.39         30.13   45.27
CERAMICS             1.33        -52.18   98.41
ENGINEERING          1.26        -26.45   84.29
REFINERIES           1.21         -9.29   36.94
CEMENT               1.10        -60.17  180.00
JEWELLERY            1.07        -96.09  164.21
ENTERTAINMENT        0.73        -74.11  177.96
TEXTILES             0.43        -40.15   80.11
HOTELS               0.33       -125.38  204.88

In [29]:
# money to be made criteria-wise
df_portfolio_features.groupby('Criteria')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                sum  count
Criteria
XY24      3413704.0     21
X40       1834680.0     19
XR        1280544.0     13
X40N      1192669.0     13
AR        1159045.0      9
OX40N      726223.0     10
XY25       413150.0      5
SR         288950.0      2

In [30]:
# money to be made conviction-wise
df_portfolio_features.groupby('Conviction')['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                  sum  count
Conviction
H-SC        3355222.0     24
X-LC        1858351.0     21
X-MC        1561135.0     15
M-SC        1370886.0     14
X-SC        1315826.0      9
H-MC         305697.0      2
L-SC         207948.0      2
M-LC         154634.0      1
M-MC          87185.0      2
L-MC          48604.0      1
H-LC          43477.0      1

In [31]:
# money to be made criteria and conviction-wise
df_portfolio_features.groupby(['Conviction', 'Criteria'])['FTT Amt'].agg(['sum', 'count']).sort_values(by='sum', ascending=False)

                           sum  count
Conviction Criteria
H-SC       XY24      1059366.0      6
X-LC       X40        994173.0     10
H-SC       AR         924459.0      5
M-SC       XY24       821536.0      6
X-SC       XY24       772712.0      4
H-SC       XR         761084.0      7
X-MC       X40        638799.0      7
           X40N       492325.0      4
X-LC       X40N       358938.0      6
X-SC       X40N       341406.0      3
X-LC       XY24       334574.0      2
H-SC       OX40N      321363.0      4
M-SC       OX40N      300133.0      5
H-SC       SR         288950.0      2
X-MC       XY25       233929.0      2
H-MC       XY24       229434.0      1
X-SC       X40        201708.0      2
X-MC       XY24       196082.0      2
M-SC       XR         173570.0      2
M-LC       XR         154634.0      1
X-LC       XY25       131235.0      2
L-SC       OX40N      104727.0      1
           XR         103221.0      1
H-MC       AR          76263.0      1
M-SC       AR          75647.0      1
L-MC       XR          48604.0      1
M-MC       XY25        47986.0      1
H-LC       AR          43477.0      1
X-LC       XR          39431.0      1
M-MC       AR          39199.0      1

In [32]:
# notebook execution time

end_time = time.time()
execution_time = round(end_time - start_time, 0)
print(f"Notebook execution time: {execution_time} seconds")

Notebook execution time: 31.0 seconds